### PR TITLE
Merge v1.2.3 master

### PR DESCRIPTION
**Pull request by emilevauge**
### Description

This PR reports tag `v1.2.3` into master.
Cherry picked:

https://github.com/containous/traefik/commit/40afd641a9488db6b02a09d8eaf18eaa1e935d5b
https://github.com/containous/traefik/commit/b3e6c7f598be510befab97b3b9fdc707604d89aa
https://github.com/containous/traefik/commit/fa4d2d325dbd56d68183ebe69b944f6cd529fe04
https://github.com/containous/traefik/commit/0ecfbb8279d5d3c1e3c5c1c83834f73ad8cb5698
https://github.com/containous/traefik/commit/e21feae56163217674c3406bcf7f724f48521d0f
https://github.com/containous/traefik/commit/37b44cc706ebf28e9f255fc6220418c49ec7d84e

### CODE REVIEW

**Comment by timoreimann** [comment]
@emilevauge AFAICS, the vendored files should not be touched.

Please double-check they do not contain changes which should have gone into the non-vendored copy. git might have been confused (`-X find-renames` is your friend).

**Comment by emilevauge** [comment]
@timoreimann Indeed, that's why there is still a `WIP` label :)
FYI, `git cherry-pick -Xrename-threshold=10%` was not enough, I had to remove temporarily `integration/vendor`, cherry pick all commits and finally rebase interactively to remove the temp commit.
We need to merge https://github.com/containous/traefik/pull/1541 before this one, to avoid merge conflicts in `server.go`.

**Comment by timoreimann** [comment]
Reading the `git diff` documentation again, it looks like you need to actually _increase_ the threshold in order to force git to be more strict.

Good to know for the next time. :-)

**Comment by emilevauge** [comment]
I tried with 10, 30, 50 and 80 :)

**Comment by timoreimann** [comment]
Aww, damn!

**Comment by ldez** [comment]
@emilevauge you have my commit in your branch...

**Comment by emilevauge** [comment]
@ldez I know I know, I'm waiting for https://github.com/containous/traefik/pull/1541 to be merged :)

**Pull request merged**
