### PR TITLE
Add requirements.txt for netlify

### PR DESCRIPTION
**Pull request by emilevauge**
This PR allows to preview the generated documentation website:

capture du 2016-07-29 17 08 44

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

**Comment by emilevauge** [comment]
Deploy preview processing.

Built with commit 656bca9d0eb1ab53f566e90a9bab2d5d8bb8231b

https://app.netlify.com/sites/goal-keeper-object-86848/builds/579b5e4671e20a514004d788

**Comment by errm** [comment]
should I now be able to click the Details link on the status? it 404s for me...

**Comment by vdemeester** [comment]
A little bit like @errm, I have 404s for other pages that the home/index

**Comment by emilevauge** [comment]
It should work now ;)

**Comment by vdemeester** [comment]
It's working !!
LGTM 🐸

**Comment by errm** [comment]
LGTM

**Comment by vdemeester** [comment]
Needs a rebase :angel:

**Pull request merged**
