### PR TITLE
Updating Toml to sure PathPrefix instead of Path

### PR DESCRIPTION
**Pull request by Russell-IO**
This works out of the box with zero changes.
As per: http://www.gorillatoolkit.org/pkg/mux

Once can use PathPrefix instead of Path, which provides much more predictable usage.
I.e. when i push /web here and / over there, I expect sub directories to work as well.

Tested with Latest & KV

### CODE REVIEW

**Comment by samber** [comment]
LGTM

**Comment by emilevauge** [comment]
Thanks @Russell-IO :)
Once rebased, LGTM
/cc @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐸 but needs a rebase :sweat_smile:

**Comment by emilevauge** [comment]
@samber, could you rebase your PR please?

**Comment by samber** [comment]
@emilevauge euuuh...

it's not mine ;-)

=> @Russell-IO

**Comment by emilevauge** [comment]
Sorry @samber :smile:

**Pull request closed without merging**
