### PR TITLE
Rename health check URL parameter to path.

### PR DESCRIPTION
**Pull request by timoreimann**
Also improve documentation.

@emilevauge @dtomcej as discussed on Slack.

### CODE REVIEW

**Comment by timoreimann** [comment]
CI green, this is ready for review: @containous/traefik

**Comment by timoreimann** [comment]
@vdemeester the feature wasn't available in the previous release yet. We kind of agreed on Slack that changing in the v1.2 branch is still acceptable and doesn't count as a "breaking API change".

WDYT?

**Comment by vdemeester** [comment]
@timoreimann ohhh 👼 right, nevermind.. didn't see that it was the branch, etc…

**Comment by emilevauge** [comment]
@timoreimann great job, thanks :)
LGTM

**Pull request merged**
