### PR TITLE
Check for dynamic tls updates on configuration preload

### PR DESCRIPTION
**Pull request by ffilippopoulos**
### What does this PR do?
Changes to look for tls certificate changes during `preLoadConfiguration` function. The aim is to solve issue: https://github.com/containous/traefik/issues/3272 and make reload configuration because of cert changes when `touch` toml files.

### Motivation

We are hitting this issue because we run an HA traefik setup in a kubernetes cluster and we use `cert-manager` to manage/update certificates. Each time a certificate is updated we have to go and restart traefik instances atm.

### More

- [x] Added/updated tests
added one test `TestListenProvidersPublishWhenTLSCertChange` under server/server_tests.go that loads a conf that includes `TLS`, then provides the same conf 2 times and expect no changes and finally rewrite new certs and provide the same conf that should trigger a reload.

### CODE REVIEW

**Comment by ffilippopoulos** [comment]
semaphoreci looks like is having issues with docker:
```
docker build  "--build-arg=DOCKER_VERSION=18.06.1" -t "traefik-dev:master" -f build.Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by dbachrach** [comment]
We are running into a similar issue where cert-manager updates the secrets but the Traefik pods need to be explicitly killed. I had a question on this part though:

> The aim is to solve issue: #3272 and make reload configuration because of cert changes when touch toml files.

Should you have to touch the toml file at all? Should a modification to the TLS files be all that's needed? If not, what aspect in the cert-manager update process will touch the toml file to trigger a reload in traefik?

**Comment by ffilippopoulos** [comment]
@dbachrach that is proposed/discussed here: https://github.com/containous/traefik/issues/3083 and is more of an enhancement. If you read through the issue there is a small explanation on why this mechanism (touching the toml file) was picked. This PR is just trying to solve the bug that is linked in the description.

Arguably this is still not going to be the ideal approach in our (and your) case as you still have to run a sidecar to watch the certs (i am using `inotify` for that) and `touch` the toml file in case of change.

**Comment by ffilippopoulos** [comment]
Is there anything we can do to help this one progress? We are happy to review code if there are any concerns or anything similar. It is just holding us to migrate from tls termination on elbs as we would have to go and manually restart traefiks every couple of months which can be disturbing.

**Comment by juliens** [comment]
Thank you for your PR.

I think that this is better to replace file path with the content directly in the provider file. With this, it will fix the bug because the `loadConfiguration` will see the content modification.

I did the modification in order to merge it in the next bug fix release.

**Pull request merged**
