### PR TITLE
Set cookie name for docker backends

### PR DESCRIPTION
**Pull request by richardjq**
### Description

Modification to allow you to specify the cookie name for a docker container using `traefik.backend.loadbalancer.cookiename=somecookie`.

Addresses issue #1574 for docker backends.

### CODE REVIEW

**Comment by timoreimann** [comment]
Sounds reasonable to me. @emilevauge, WDYT?

**Comment by emilevauge** [comment]
Instead of using a specific Docker label, WDYT of using a cookie named `_TRAEFIK_BACKEND_{backend-name}={server-name}` ?

**Comment by emilevauge** [comment]
@richardjq it should also covers the use case in #1574 :)

**Comment by kleinsasserm** [comment]
Yes, this will cover my issue also. The only requirement is, that the cookie is uniqe per Traefik instance. If {server-name} reflects the dynamic Traefik docker container hostname, it will be a valid cookie naming.

**Comment by richardjq** [comment]
@emilevauge - so do you want to reject this PR and I'll see if I can generate a new PR to generate a new one with `_TRAEFIK_BACKEND_{backend-name}`?

Or do you prefer to keep the option to set the cookie name and make an additional change for the default to be `_TRAEFIK_BACKEND_{backend-name}`?

**Comment by ldez** [comment]
@richardjq 👍  we close this PR and you create a new PR.

**Comment by richardjq** [comment]
Done. See #1716.

Thanks!

**Pull request closed without merging**
