### PR TITLE
Normalize backend even if is user-defined

### PR DESCRIPTION
**Pull request by WTFKr0**
Signed-off-by: WTFKr0 <thomas.kovatchitch@gmail.com>

### CODE REVIEW

**Comment by WTFKr0** [comment]
Hi,

This pull request to normalize user defined backend by label.
I have an automatic labelling process so the label is a version like : myapp-1.0.2
Traefik backends don't like the dots

Are you OK with that ?

**Comment by emilevauge** [comment]
Thanks @WTFKr0!
@containous/traefik, shouldn't we push this on branch v1.1 instead?

**Comment by vdemeester** [comment]
The diff is not that big of a deal so yeah, we could put it into a 1.1.1 😇
LGTM 🐸

**Comment by emilevauge** [comment]
@WTFKr0 could you change the base of this PR to branch v1.1 please?

**Comment by emilevauge** [comment]
@WTFKr0 I'm sorry but you will have to rebase your PR. There are too much commits here ^^

**Comment by WTFKr0** [comment]
Don't know how to that... :/
Should i create new PR ?

**Comment by WTFKr0** [comment]
Or is it something like : 
git fetch origin
git rebase origin/v1.1
?

**Comment by emilevauge** [comment]
Create a new local branch from v1.1 and push force to Github. Or create a new pr if you prefer :)

**Comment by WTFKr0** [comment]
I think it's OK now !!
#Galère

**Pull request merged**
