### PR TITLE
Add global InsecureSkipVerify option to disable certificate checking

### PR DESCRIPTION
**Pull request by stuart-c**
Signed-off-by: Stuart Clark <stuart.clark@Jahingo.com>

### CODE REVIEW

**Comment by errm** [comment]
Hi Stuart,

Thanks for the PR :)

Could you gofmt your code please.

**Comment by stuart-c** [comment]
Sorry for taking a while to respond. That is now fixed

**Comment by emilevauge** [comment]
Thanks @stuart-c !
Could you add some documentation in https://github.com/containous/traefik/blob/master/traefik.sample.toml, and in https://github.com/containous/traefik/blob/master/docs/toml.md ?
And you need a new rebase ;)

**Comment by emilevauge** [comment]
Deploy preview processing.

Built with commit 4a88cbde3a7df6899977e99517390f9494735878

https://app.netlify.com/sites/traefik-docs/builds/579e207dd6865d7184e7597a

**Comment by stuart-c** [comment]
Done

**Comment by emilevauge** [comment]
LGTM
thanks @stuart-c :)
/cc @containous/traefik

**Comment by vdemeester** [comment]
My only question is about the name of the flag that feels a little bit weird : I would either have a `Insecure` one (like the `--insecure` flag of `curl`) or a `TLSSktipVerify` or `CertificateSkipVerify` or.. 

I'm bad at naming things though :sweat_smile:

**Comment by stuart-c** [comment]
I just used the Go naming, but that's easily changed...

**Comment by emilevauge** [comment]
We already use this naming in providers, I think we should stay consistent and leave it :)

**Comment by vdemeester** [comment]
> We already use this naming in providers, I think we should stay consistent and leave it :) 

Good point, LGTM then :angel:

**Pull request merged**
