### PR TITLE
feat(constraint): Supports kv backends

### PR DESCRIPTION
**Pull request by samber**
Related to #311

- BoltDB
- Consul KV
- Zookeeper
- Etcd

### CODE REVIEW

**Comment by keis** [comment]
In this one the check is triggered from the template and while not inheritly bad I think that for the sake of consistency the filter should happen before the template like in the others.

**Comment by emilevauge** [comment]
@samber thanks a lot :)
I tend to agree with @keis on the filtering :)

**Comment by samber** [comment]
Corrected ;-)

**Comment by vdemeester** [comment]
LGTM 🐋

**Comment by emilevauge** [comment]
@samber, thanks a lot :)
- There is an issue in toml documentation on constraints: https://github.com/containous/traefik/issues/451#issuecomment-227387522
- `traefik.sample.toml` should be updated too

Other than that, looks great :)

**Comment by emilevauge** [comment]
Hi @samber, I'm planning to get this PR in the 1.1 releases. Do you think it's possible ?

**Comment by emilevauge** [comment]
PR carried in #689 because of inactivity.

**Pull request closed without merging**
