### PR TITLE
Split a joint-rule into individual rules.

### LINKED ISSUE #1663: Rule priorities are based on total rule length, not individual path prefix
### Do you want to request a feature or report a bug?

A bug. I believe Traefik uses incorrect logic to decide on routing rules priority.

### What did you do?

Consider Traefik is configured to watch for Docker containers (a very basic config that essentially boils down to `[docker] watch = true`), and observes the following configuration in their labels (as a snippet from Docker Compose file):

    web:
        ...
        labels:
            traefik.enable: "true"
            traefik.backend: "web"
            traefik.frontend.rule: "Host:one.example.org,one.example.net,old.one.example.net,old.one.example.org"

    web-ng:
        ...
        labels:
            traefik.enable: "true"
            traefik.backend: "web-ng"
            traefik.frontend.rule: "Host:one.example.org,one.example.net,PathPrefix:/api/v2/,/o/"

### What did you expect to see? What did you see instead?

I've expected a request to `one.example.org/api/v2/` to be routed to the `web-ng` container, as it has more specific `PathPrefix`.

However, requests were sent to `web` instead. This was the case until I've made the `web-ng`'s rule look like `"Host:one.example.org,one.example.net,PathPrefix:/api/,/o/,/a-long-string-to-make-this-rule-more-specific/"`.

I've expected Traefik to compare path prefixes of all matching rules rather than rules themselves. I.e. compare "" (longest PathPrefix that matches from the `web`'s rules - empty in this case) vs "/api/" (longest PathPrefix that matches from the `web-ng`'s rules). I haven't looked at the code but it seems that this isn't the case. I've experimented a little and can tell that traffic is routed to `web-ng` only when the whole rule's length is greater *or equal* to the `web`'s frontend rule's length.

### Output of `traefik version`:

    Version:      v1.3.0-rc3
    Codename:     raclette
    Go version:   go1.8.2
    Built:        2017-05-24_01:39:53PM
    OS/Arch:      linux/amd64

### PR DESCRIPTION
**Pull request by yue9944882**
1. Split joint rules such as `PathPrefix:/v1,/v2` into splited individual rules `PathPrefix:/v1` and `PathPrefix:/v2`)
2. Every individual rule's priority is measured by the length of its own substring
3. Take all the splited individual rules as the subrouter of `serverRoute.route`. And the priority of this parent route (`serverRoute.route`) is only assigned by frontend.Rule

### Description

It works fine and solved #1663 and its related problems. Corresponding unit test is also added.

As is stated in the commit message, it works by giving every sub-route a individual priority which is calculated by the length of args. E.g. in the expression `PathPrefix:/v1,/v2345`, it will be split into 2 sub-route which is `PathPrefix:/v1` and `PathPrefix:/v2345`, and their priority is 3 and 6.

So in the case of `PathPrefix:/,/v2/webhook,/v2/token` and `PathPrefix:/v2`, a request with `/v2` will match `/v2` becase the priority of `/v2` is 3 and `/` is `1`,`/v2/webhook` and `/v2/token` not matched. Or rather, it solves #1962 also. 

#1876 is also related.

Fixes #1663

### CODE REVIEW

**Comment by yue9944882** [comment]
So wierd?

CI failed on provider/file/file_test.go, but my commit have no relation to this?

Any one can provide help? Thx

**Comment by aantono** [comment]
Can you add an updated documentation to reflect the change in logic?

**Comment by ldez** [comment]
@aantono the PR is in Design review: no changes are required in this state.

**Comment by yue9944882** [comment]
@aantono I tried to add some descriptive documentation to my commit. But truly I don't know where to start with. Because this commit simply added some repeating simple codes.

The BUG referenced in #1663 and #1962 is caused by following line of code. Assigning the priority of route with the sum of priority set by frontend and the length of "rule string" itself is neither mathematical nor reasonable. And it is certainly the cause of related BUGs.
 
```
 -	newRoute.Priority(serverRoute.route.GetPriority() + len(route.Rule))
 +	newRoute.Priority(serverRoute.route.GetPriority())
```

So my PR is to transform the route assigned priority of (serverRoute.route.GetPriority() + len(route.Rule)) into a two-layered routes. The priority of parent route is given by its pre-set value from frontend rule and the priority of child routes are given by their spilt individual rules. 

As for how the rule is split into individual child rules, please refer to my commit message and description above. Thx :-)

**Comment by emilevauge** [comment]
@ldez @Juliens Any thoughts on this ?

**Comment by Juliens** [comment]
Thx for your PR. 

In fact, the Priority is ignored in SubRoute.
So in your modification, all the priorities you set are ignored. The order become in "declaration order"

If you try to inverse your rules declarations in your test, you will see that it will fail.

As it means a full refactor, I propose to close this PR, you can then create another one with a new implementation. WDYT ?

**Comment by yue9944882** [comment]
Thx. I'll try some another implementation. 


Close this PR.

**Pull request closed without merging**
