### PR TITLE
Add libkv Username and Password

### PR DESCRIPTION
**Pull request by tcolgate**

### CODE REVIEW

**Comment by tcolgate** [comment]
This lets you configure the username/password params in libkv. This is definitely useful for etcd, but may not be obvious for others. The struct embedding makes it hard to hide in the other KV providers where it may not be so relevant.

**Comment by timoreimann** [comment]
Refs #1075.

**Comment by tcolgate** [comment]
@emilevauge Docs updated.

**Comment by tcolgate** [comment]
@emilevauge rebased on master

**Pull request merged**
