### PR TITLE
Fix panic if listContainers fails…

### LINKED ISSUE #442: container dropped out when connecting to Docker Swarm
I configured a container to connect to swarm. It connected and then bombed out.

An example of the error can be seen here - http://hastebin.com/osoratenud.hs

### PR DESCRIPTION
**Pull request by vdemeester**
… and also share context accross API call, as this is how it's meant to be used (and it allows to skip some calls if `cancel` is called).

Fixes #442 

/cc @samber @emilevauge 

PS: this need a little bit of testing though :angel: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by emilevauge** [comment]
@vdemeester entering light speed PR fixing

**Comment by vdemeester** [comment]
Ok it's green, at least I did not break anything easily detected :sweat_smile: 
But still need some exercices :smile_cat:

**Comment by emilevauge** [comment]
@vdemeester doesn't seem risky to me.
LGTM :)

**Comment by samber** [comment]
Sharing context seems good but i think it's not enough. What about doing the ```append(.....)``` in an else condition in ```listContainers()``` ?

```
for _, container := range containerList {
		containerInspected, err := dockerClient.ContainerInspect(ctx, container.ID)
		if err != nil {
			log.Warnf("Failed to inpsect container %s, error: %s", container.ID, err)
		} else {
			containersInspected = append(containersInspected, containerInspected)
		}
	}
```

**Comment by vdemeester** [comment]
@samber oh definitely, I thought it was in the else… I guess I needed a nap today :smiley: 
I'll update :wink:

**Comment by emilevauge** [comment]
@samber OK to merge this one ?

**Comment by samber** [comment]
yes ;-)

**Pull request merged**
