### PR TITLE
Update documentation in kubernetes setup

### PR DESCRIPTION
**Pull request by matthew-marchetti**
### Description

This PR updates the docs to use a daemonset for deployments, and adds missing annotations to the kubernetes example files.

### CODE REVIEW

**Comment by ldez** [comment]
Seems a duplicate of  #1706

**Comment by matthew-marchetti** [comment]
@ldez i don't agree -- His missing 2 files out of his commit that also need to be updated. Sure -- The main file is very similar, but If anything, this is a more completed version of what needs to be updated.

**Comment by ldez** [comment]
@matthew-marchetti You can do a review in #1706 and suggest your changes.

**Comment by ldez** [comment]
We (maintainers) are currently speaking about the better way to document k8s.
News coming soon.

**Comment by matthew-marchetti** [comment]
@ldez not to chain onto this, but the https://docs.traefik.io/user-guide/kubernetes/ docs are generated directly from this correct ?? I'm noticing a discrepancy between the two for the     "traefik.frontend.rule.type: PathPrefixStrip" option. The online docs seems to be ignoring the case, which breaks it when used in the lowercase form. Any idea on what that would be ? -- The value looks correct in my PR ?

**Comment by timoreimann** [comment]
@matthew-marchetti the case sensitivity used to be irrelevant for Kubernetes, but it's not anymore.

thanks for pointing out! we need to fix that too.

**Pull request closed without merging**
