### PR TITLE
Upgrade directives name since we use angular-ui-bootstrap

### PR DESCRIPTION
**Pull request by micaelmbagira**
Fixes https://github.com/containous/traefik/issues/577

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks a lot @micaelmbagira, tabs are fixed :)
LGTM! But needs a rebase :)

**Comment by micaelmbagira** [comment]
Rebased !

**Comment by errm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/containous/traefik/578#-:-KOOrKdqUsNGz20_xOP4:bnfp4nl)*

**Comment by vdemeester** [comment]
@micaelmbagira needs another rebase :sweat:

**Pull request merged**
