### PR TITLE
feat(rancher): added constraint management for rancher provider

### PR DESCRIPTION
**Pull request by yyekhlef**
Added constraint management for the Rancher provider. This enables filtering capabilities like described in the documentation https://docs.traefik.io/toml/#constraints

### CODE REVIEW

**Comment by yyekhlef** [comment]
Thx ! My first PR ! :-)
I've already updated docs/toml.md. Just pointed out that Rancher provider now supports constraints. You need more details ?

**Comment by yyekhlef** [comment]
@ldez : it was probably my eyes... i'm updating the Rancher part. :-)

**Comment by ldez** [comment]
I speak about: https://github.com/containous/traefik/blob/master/docs/toml.md#rancher-backend

**Comment by emilevauge** [comment]
Hey @yyekhlef, welcome on board :heart: !
Could you squash your commits and push force to your branch instead of using a revert commit ? 
Thanks a lot :)
Love your PR :+1:

**Comment by yyekhlef** [comment]
Hello @emilevauge thanks. :-)

Squash done.

**Comment by yyekhlef** [comment]
Thx @SantoDE

**Comment by SantoDE** [comment]
Haha @yyekhlef. I was actually just about to rebase your PR :) Can you now squash the merge again please again? Once tests are green, I'll merge

**Comment by yyekhlef** [comment]
Sorry @SantoDE I do it now. :-)

**Pull request merged**
