### PR TITLE
Merge changes for logging of frontend, backend, and total time.

### PR DESCRIPTION
**Pull request by KevinRandolph**
Emile, this is a work in progress to support the logging of additional information, as outlined in issue #155.  It supports the frontend name and elapsed time, but I still need to get the backend host information.

We are soliciting comments to see if you are in agreement with way in which the changes are being implemented, or we need to do it a different way.

Thanks,
Kevin

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @KevinRandolph, Thanks for the contribution!
Here is an idea to set backends url in context:

- create a new middleware:
```
package middlewares

import (
	"net/http"

	"github.com/gorilla/context"
	"fmt"
)

type Backend struct {
	handler http.Handler
}

func NewBackend(handler http.Handler) *Backend {
	return &Backend{handler:handler}
}


func (b *Backend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	b.handler.ServeHTTP(rw, r)
	context.Set(r, "backend", r.URL.String())
}
```

- in `server.go`, change `	rr, _ := roundrobin.New(fwd)` in `rr, _ := roundrobin.New(middlewares.NewBackend(fwd))`

This will set backend URL into context ;)

**Comment by KevinRandolph** [comment]
@emilevauge, thank you for your reply.

Unfortunately, this does not work as intended.  The context is saved in the request object, and the fwd object has a new request object with the backend URL.  As such, the backend information cannot be propagated back to the logger middleware.

**Comment by KevinRandolph** [comment]
As an experiment, I modified rr.ServeHTTP where there is both the original request object and the new backend URL.  I set the backend in the context, but the context is clear when we get to the next handler.  I don't understand why the context has been cleared.

**Comment by emilevauge** [comment]
Great news! Well done @KevinRandolph :clap: 
 I was despairing of finding a simple way to achieve that...

**Comment by KevinRandolph** [comment]
@emilevauge, the gorilla/mux package automatically clears the context unless a flag is set:

```go	
router := mux.NewRouter()
router.NotFoundHandler = http.HandlerFunc(notFoundHandler)
router.KeepContext = true  // Keeps context from being cleared
```

**Comment by emilevauge** [comment]
Do you think there is a good reason for clearing context like that?

**Comment by KevinRandolph** [comment]
I suspect it is to prevent unintended memory leaks.  I specifically clear the context in the logger middleware, so there are no such memory leaks in this logging enhancement.

**Comment by emilevauge** [comment]
https://github.com/vulcand/oxy/pull/31
Simpler way :)

**Comment by tooda02** [comment]
@emilevauge I've taken this on while Kevin is on vacation and have made updates to synchronize with the current containous/traefik master and to remove the need for any changes to oxy.  IMO, the PR is ready to merge.   Please resume reviewing it when you get a chance.

**Comment by tooda02** [comment]
##### Overview of Update

* The main package `server.go` creates a map enabling the conversion of a URL to the symbolic name of the associated backend server.  This map is updated each time the configuration changes (such as after a Marathon notification of a new deployment) and is stored in the logger middleware with a call to method `logger.SetURLmap()`.  See `server.go:mapURL2backend()` and `middlewares/logger.go`.

* Middleware `logger` creates a unique request ID for each request by incrementing a common counter.  It stores the request ID in a new custom header, `X-Traefik-Reqid` that can be accessed when subsequent middleware methods call method `logger.saveNameForLogger()`.  The reqid provides a context for storing names.  Note that the HTTP request pointer cannot be used as a context key (making Gorilla context unsuitable) because oxy replaces the HTTP request with a shallow copy when assigning a backend.

* Middleware `routes` stores the frontend name.

* Middleware `saveBackend` stores the backend name

A quick way to test the update is to run command `example/runExample.sh` from the top directory.  This script restarts the Traefik server and also starts three simple HTTP servers.  Then use command `curl http://127.0.0.1:80/test{1,2,2}` to send requests to two of the servers.  This results in Traefik appending lines similar to the following to the end of log/access.log:

        127.0.0.1 - - [04/Mar/2016:16:58:40 -0800] "GET /test1 HTTP/1.1" 200 34 "" "curl/7.43.0" "frontend1" "backend1" 128.683002ms
        127.0.0.1 - - [04/Mar/2016:16:58:40 -0800] "GET /test2 HTTP/1.1" 200 34 "" "curl/7.43.0" "frontend2" "backend2.server1" 90.516359ms
        127.0.0.1 - - [04/Mar/2016:16:58:40 -0800] "GET /test2 HTTP/1.1" 200 34 "" "curl/7.43.0" "frontend2" "backend2.server2" 93.031987ms

**Comment by emilevauge** [comment]
Hi @tooda02, first, thanks for uour contribution and sorry for the waiting time.
I made a review of your code and I have few comments:

- could you squash your commits?
- rather than a bash script test, I would prefer integration or unit tests of your code ;)
- I would rename `routes` to `saveFrontend` to stay homogeneous
- have you made benchmarks on traefik using that (using ab, or wrk), to test high loads?

@vdemeester any comment?

**Comment by tooda02** [comment]
@emilevauge Thanks very much for the review.  I'll make the changes you're requesting and look into obtaining a benchmark.  Do you have previous benchmarks that you want to compare or can share?  Is an example available of a process that's been used in the past?

Also, what is the definition of "high load" in this context?  I have been running this version on a production server for the last five days, with about 190000 queries processed.  This works out to about 1580/hour.  Does that qualify?

**Comment by emilevauge** [comment]
Hi @tooda02, you can check the [benchmark](https://github.com/containous/traefik/blob/master/docs/index.md#benchmarks) section in the documentation ;)
A bench with +1000/s during 1h would be better, the idea is to validate that you don't have a concurrency issue, nor  a memory leak.

**Comment by KevinRandolph** [comment]
@emilevauge, I am closing this PR.  A new one will be opened by my colleague @tooda02.

**Pull request closed without merging**
