### PR TITLE
Fix missing value for k8s watch request parameter

### PR DESCRIPTION
**Pull request by codablock**
Fixes: #732

### CODE REVIEW

**Comment by emilevauge** [comment]
@codablock Thanks a lot for this one :) Could you base your PR on `v1.1` branch? We will push this in `v1.1.1` release :)

**Comment by codablock** [comment]
@emilevauge Do you want me to rebase on v1.1 and still merge into master or should I rebase and recreate a PR that goes into v.1.1?

**Comment by emilevauge** [comment]
@codablock you change the base of the current PR to v1.1 without creating a new one. Or create a new one, as you wish :)

**Comment by codablock** [comment]
@emilevauge Just changing the base was not enough. Had to create a branch based on v1.1 and recreate a PR that goes into v.1.1: #874

**Pull request closed without merging**
