### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by timoreimann** [comment]
I'm okay with this, though at some point we may want to maintain a list of blog posts / external articles and just point to it from the quick start.

@emilevauge @ldez thoughts?

**Comment by marcosnils** [comment]
Thx guys, it there some other tutorial that you think it would be worth to showcase for your users to play with?.    We think it's pretty cool that traefik users can learn by leveraging an interactive playground.

**Comment by emilevauge** [comment]
@marcosnils indeed, we love interactive playgrounds. I'm thinking for example at play-with-k8s ;)

**Comment by marcosnils** [comment]
@emilevauge got it. We're setting up training.play-with-k8s.com the same as Docker's tutorials. Do you have some content I can use to setup a K8s traefik tutorial?

**Comment by emilevauge** [comment]
@marcosnils Awesome :heart_eyes: 
Here we go:
http://docs.traefik.io/user-guide/kubernetes
https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948

**Pull request merged**
