### PR TITLE
Document accepted values for logLevel.

### PR DESCRIPTION
**Pull request by jimmycuadra**
I wanted to know what the acceptable log levels are for Traefik. I had to read the source code and then go look at the docs for logrus to get the answer to question. Let's not make the next person do all that! :}

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :frog: 
/cc @containous/traefik

**Comment by errm** [comment]
LGTM

**Comment by vdemeester** [comment]
arf, needs a rebase :sweat:

**Comment by jimmycuadra** [comment]
Rebased!

**Pull request merged**
