### PR TITLE
Implement native kubernetes acme storage

### PR DESCRIPTION
**Pull request by dtomcej**
### What does this PR do?

This PR will implement native storage of ACME data in native kubernetes objects, so that file or KV storage is not required.

Based on proposal https://github.com/containous/traefik/issues/2542

### Motivation

Kubernetes users have access to kubernetes object storage. Traefik should be able to leverage this, and allow certs to be used for other projects.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by emilevauge** [comment]
As discussed with @dtomcej, we will discuss more deeply about this topic at KubeCon.
Closing this one then. Thanks @dtomcej

**Comment by camflan** [comment]
@emilevauge Any information on this? I'm hoping you meant KubeCon Europe and not KubeCon US :)

**Comment by scher200** [comment]
@emilevauge @dtomcej please let us know when we can expect this.

**Comment by camflan** [comment]
@emilevauge @dtomcej bump

**Pull request closed without merging**
