### PR TITLE
New web ui

### PR DESCRIPTION
**Pull request by jkuri**
First of all, sorry for making PR this huge, I did read the contributing guide but in that case I believe small PR is not possible.

Hi guys, I really like the project and I decided to help you with transition to latest version of Angular rather than using first version. 

screen shot 2017-10-08 at 18 11 30

I also updated UI and started to working on be a slightly more modern but didn't finish things already. First, I would like to know if you guys are even interested of upgrading and improving user interface?
If so, this PR is not finished yet, its a work in progress, but can be done in a day. 

I have question if there is a reason why you are sending xhr requests to server in time interval (3000ms)? I believe this is a more or less anti-pattern and should be done with websockets. 
All live data on Web UI should transfer data through websockets and if someone is interested of creating server I can update the frontend accordingly. 

TODO:
- [x] health
- [ ] frondend implementation of reconnecting websocket
- [ ] e2e tests
- [ ] karma tests

Cheers, Jan

### CODE REVIEW

**Comment by emilevauge** [comment]
@jkuri Wow, that's awesome :tada: Thanks a lot for this :+1: 

>First, I would like to know if you guys are even interested of upgrading and improving user interface?

Definitely :heart_eyes_cat: !

>I believe this is a more or less anti-pattern and should be done with websockets.

I suggest to do this in another PR if you don't mind ;)

**Comment by jkuri** [comment]
@emilevauge thanks for that feedback 👍 

I will continoue now with live charts and use current implementation of API as you suggested.
Will come back later with new screenshots and commits :)

**Comment by errm** [comment]
I wonder if we have considered if angular is the correct framework to use, if as I understand upgrading to the latest angular will involve rewriting much of the frontend code.

* Angular doesn't seem to be quite so popular now as it was a few years ago.
* The Web UI is (currently) quite simple, perhaps we can make something simpler with a lighter weight framework.

I have no particular preference as to what the best option is, and I am totally willing to be told by anyone who will actually work on this that Angular is indeed still the best tool for the job. I just think it might be wise to at least consciously decide to use Angular or something else if time is going to be spent on reworking this code.

Honestly though @jkuri if you are happy with the direction you are taking this in, please feel free to ignore me :)

**Comment by jkuri** [comment]
I am not sure about popularity because I am not following statistics about this, I think is irrelevant. What I can say is that is definitely the fastest and the size of the bundle is relevant to how and in which case you include some part of Angular parts. If you have included all packages that it provides then its definitely not the lightest. Also, I think you said that without a solid foundation of knowledge of web frameworks, don't get me wrong, afterall you can do it in jQuery if you like. 

I like this project a lot and wanted to help with this thing how I can and where I see that it can be improved. And I got this refactor almost done, in the evening I will push the changes then please check again. Thanks.

**Comment by ldez** [comment]
@jkuri Please no jQuery 😄 
What do think about VueJS ?

**Comment by jkuri** [comment]
@ldez Vue.js is fast and easy to learn, that's what I heard. 
If the issue is maintaing the UI in the future I am also interested to help with the new features.

**Comment by SantoDE** [comment]
Hey @jkuri ,

first of : Thanks! :) I really like the effort you've put into this.

On technical part, I got to agree that vue.js might be a good starter compared in weight and stuff to angular. 

Knowing to you might be up to help is very good to know. Thanks! :)

**Comment by jkuri** [comment]
no problem at all. for what I have now currently the bundle size (gzipped) is `172 kB` for production build and will not increase much in the future as its already have `d3` included.

**Comment by jkuri** [comment]
I think that's not so hardcore and every mobile connection can handle this.

**Comment by emilevauge** [comment]
IMHO, the framework we will use is not significant here. Regardless which one we will choose, it will be outdated in the coming months :smile: Besides, I don't think the bundle size is something we should really care about as: 
- this UI is not intended to exposed
- the current size seems reasonable
To my mind, the current refactor is really welcomed, even with the latest & less-hyped Angular ;)

**Comment by timoreimann** [comment]
I'm with @emilevauge here. One thing we may want to pay attention to at some point is performance: We have one environment with ~300 backends, and the web UI already takes 2-3 secs to load. Scrolling feels a bit sluggish too.

I guess that's more a matter of redesigning the UI than choosing a particular framework, however.

**Comment by jkuri** [comment]
Emile and Timo thanks for support there.

This is how it looks currently, still status code bar chart and tests missing.

screen shot 2017-10-09 at 21 27 49
screen shot 2017-10-09 at 21 27 44

Btw, I made this thing [here](https://github.com/jkuri/traefik/blob/76dcade07b6ca28bf17fa95b100912c7a581c60f/webui/src/components/health/health.component.ts#L30-L32) as @emilevauge suggested; making request every 3 second, so this is a subject that is going to change in the future prs.

**Comment by ldez** [comment]
@jkuri don't forget the dashboard filter 😉

**Comment by ldez** [comment]
@jkuri any news?

**Comment by jkuri** [comment]
@ldez I'll try to finish it today. Sorry but been real busy lately.

**Comment by jkuri** [comment]
@ldez sorry for that question but is there any sample configuration of multiple providers ready, so I can check search and implement UI for providers?

**Comment by ldez** [comment]
@jkuri Do you want API response sample or a Traefik configuration?

**Comment by jkuri** [comment]
can be API response but I am fine with both, just need at least 3 providers.

**Comment by ldez** [comment]
@jkuri Sorry for the delay.

I have generated some dumb json data: https://gist.github.com/ldez/f02adbaac15897e495fb1afcef6a5d48

**Comment by Stibbons** [comment]
Hello. I also back the usage of vue.js it is very lightweight even if angular 4 seems to be lighter than the previous versions.

May I add 2 requests in this UI rework:
- ease the readability of the link between the frontend and the backend? If we do not use the filter, it's kind of difficult to tell straight which frontend is connected to which backend. Do you think it is possible to have a small visualization on the front page such as: 
image
- provide the ingress URL if all information are provided, with the current UI, we need to copy paste quickly enought between two automatic refresh ....

If you need help, I can give a hand on this ui

Thanks
PS: please provide a fallback for websocket, using HTTP polling

**Comment by jkuri** [comment]
@Stibbons would you help or continue work on this PR or you would like to make it from scratch?

**Comment by jkuri** [comment]
btw, I was experimenting with Closure compilers advanced optimizations and got Angular build like really light, but didn't have time yet unfortunately to get this working with included `d3` library. also that would need Java installed inside build container. let me know what you think about it.

**Comment by Stibbons** [comment]
What is missing to finish this effort?

**Comment by errm** [comment]
@jkuri I think we should continue with this PR... your work is amazing so far and the refresh to the UI is looking good...

I don't think we have any concerns about the overall weight of the JS bundle, the UI is mostly an internal tool and would I imagine mostly be accessed by users on fast connections, there seems very little value in spending much of your time just to get a smaller js bundle.  If it becomes an issue raised by anyone I am sure we can look at it, but it seems like premature optimisation.

@Stibbons by all means feel free to make suggestions, but I think we have already decided to go with angular4 for now...  The UI idea sounds interesting, but probably would be better as a separate pr once this refactoring is over...  perhaps in addition to the existing UI as a second view...

**Comment by jkuri** [comment]
@errm 👍 then I will squeeze this and finish asap!

**Comment by Stibbons** [comment]
@errm I agree with you. I'll try to see what I can do on this pr

**Comment by Stibbons** [comment]
It is indeed very elegant. I like it :) Just checked it out and tried on my traefik setup. Here are some issue I found:
- please add a filter, i have a setup with several dozen of frontends/backend, it is always useful
- for unknown reason, the tab "file" cannot be clicked (it does nothing) while on the old ui it displayed my toml frontend
- can you also add the mini labels (wrr, https, PassHostHeader,...), they do provide some information. Maybe as hint or foldable section.

I'll try to see what I can do this week, last time I did angular was on 1.0, now I mainly does vue.js, so I might not be able to do something interesting quickly

**Comment by jkuri** [comment]
no problem, I will risk this night to finish that finally and also thanks for waking me up on that pr.

**Comment by jkuri** [comment]
thanks for you patience guys! seems like we see a light in the end of the tunnel now. 
also, thank you very much @ldez for providing me all possible data from the API, this has been really helpful as I wasn't aware of half of this key value pairs.
Can you guys please check and comment on this one, I am accepting negative comments also :) we can still make fixes before this goes in. 

@Stibbons: if you'd still like to help there are plenty of tests to be make still. otherwise I would prefer to do it in the next iteration if that's acceptable.

Currently, filter searches only through the `id` property, should we improve the search?

btw, this is what I came up with:

screenshot-2017-11-28 traefik 1 copy
screenshot-2017-11-28 traefik 1

**Comment by shadycuz** [comment]
Been following for a while now, can't wait to try this out. Looks great. In the future I think it might be nice to have a chart per front end in the health tab.

**Comment by jkuri** [comment]
thanks. yes, would be good. also I think some more interesting charts can ne added like live chart about bytes transferred over each frontend, total bytes transferred and so on. this live chart is reusable and it would not be such a effort to make this done. just an idea I got while making frontend.

**Comment by ldez** [comment]
@jkuri Sorry for the delay (small team and a lot of work).
It seems that some features are missing, can you evaluate that.
Thank you.

**Comment by mavimo** [comment]
@jkuri @ldez do you need some help? Can you give me some indication what's missing and how I can help you to finalize this PR?

**Comment by jkuri** [comment]
@ldez no problem. I will check.

**Comment by RomainWilbert** [comment]
The constant UI refresh is painful, in case you want to copy/paste urls. What about using Websockets or SSE to refresh UI data ?

**Comment by ldez** [comment]
@RomainWilbert issue fixed in #2871

**Comment by ldez** [comment]
@jkuri any news? Do you need some help?

**Comment by jkuri** [comment]
hi @ldez. I can do it today at night so you can check tomorrow morning. sorry but similar issues at this side also, small team and a lot of work so I need to code from C to frontend at work.

**Comment by jkuri** [comment]
I am on it right now, sorry for delay again but didn't find time earlier. Excpect an update in the next hours.

**Comment by mavimo** [comment]
@emilevauge @ldez can I suggest to move UI in a different repo and include it into traefik (like https://github.com/drone/drone and https://github.com/drone/drone-ui ) this make really easy contribute in each project and also allow to:
 - Have custom UI (eg branded version)
 - Potentially we should have traefik without UI (reducing the bin size) and expose a different application with UI

**Comment by ldez** [comment]
@mavimo for now we prefer use a mono-repository.

**Comment by jkuri** [comment]
@ldez I updated PR with missing features. Please check if existing features are now covered. I joined traefik slack, you can find me under name `jkuri`. 
btw, I have vacations till Friday, would be nice if you can check the PR till then. In the meanwhile I will try to bump some e2e tests, maybe I would need some help building the whole project and run that on CI before Chrome is launched.

**Comment by ldez** [comment]
@jkuri I will look at this soon, I hope next week.

**Comment by jkuri** [comment]
@ldez ok thanks, please check it when you can.


On 2 March 2018 at 10:54:13, Ludovic Fernandez (notifications@github.com)
wrote:

@jkuri <https://github.com/jkuri> I will look at this soon, I hope next
week.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/containous/traefik/pull/2226#issuecomment-369876064>,
or mute the thread

**Comment by irmana** [comment]
Looking forward to see this PR in, great job @jkuri

**Comment by matthiasbaldi** [comment]
Is it planned to get a possibility to get the request log directly in the UI? Or should I create an issue for that?
That is at the moment a feature I miss in the actual UI.

**Comment by ldez** [comment]
I have review/change the UI.

I still have an issue: there is no refresh.

@jkuri What was your plan about it?

**Comment by jkuri** [comment]
I will check right off.

**Comment by ldez** [comment]
@jkuri it's done :smile:

**Comment by jkuri** [comment]
I see, great 👍 btw there are minor issues with "Total Status Code Count", ocasionally I get some errors in console about svg rect.

**Comment by jkuri** [comment]
screen shot 2018-04-24 at 16 09 49

**Comment by jkuri** [comment]
whats up with semaphore ci?

**Comment by ldez** [comment]
For the CI, it's a google/golang issue https://github.com/golang/lint/issues/397

**Comment by shadycuz** [comment]
Amazing, when can we get a docker image to test?

**Comment by kachkaev** [comment]
screen shot 2018-04-27 at 13 02 56 screen shot 2018-04-27 at 13 02 56 screen shot 2018-04-27 at 13 02 56

Does the merge finally clear path for 1.6.0?

**Comment by ldez** [comment]
@kachkaev it's in 1.6 :smile_cat:

**Pull request merged**
