### PR TITLE
Wf multiple frontends consulcatalog

### PR DESCRIPTION
**Pull request by hsmade**
### What does this PR do?

This adds support for multiple frontends in the consul catalog provider.

### Motivation

To implement this feature request:
https://github.com/containous/traefik/issues/3597

### Additional Notes

I'm wondering if it's preferred to drop the single frontend support (which will make it possible to clean up the code, and remove the 'hacks' for backwards compatibility), and maybe make this a V3?

### CODE REVIEW

**Comment by ldez** [comment]
I see several design issues:
- the signature of the method `getFrontendRule` has been changed: it's breaking
- the duplication of the code in the template and the construction logic placed in the template goes against the work that has been done on [the homogenization of templates](https://github.com/containous/traefik/issues/2785).
- using the syntax used by the segment labels, without having real support, does not suit me. (And I do not think it's a good idea to add support for segments)

**Comment by hsmade** [comment]
After looking at the docker provider (I'm completely new to traefik and it's code), I start to see why this doesn't really fit what is there already. I will refactor my PR to work somewhat the same way (have a `Frontends` var in `templateObjects` instead of trying to put that logic into the template) and thus also get rid of the extra funcs I added to the template.

**Comment by ldez** [comment]
Could you fix:
```
---> Making bundle: validate-autogen (in .)
checking autogen is up-to-date with templates...
The result of 'go generate' differs

 M autogen/gentemplates/gen.go
```

**Comment by hsmade** [comment]
@ldez Done

**Comment by hsmade** [comment]
This PR has been replaced by https://github.com/containous/traefik/pull/3781 which implements this in a much simpler way and closer to the original source

**Pull request closed without merging**
