### PR TITLE
Add support for maximum connections for backends.

### LINKED ISSUE #300: Feature Request: Support Oxy ConnLimiter in Traefik
**Problem**
By stress testing Traefik, we've noticed that it is possible for Traefik to overwhelm downstream services with too many requests. This causes services hosted in Marathon to constantly thrash via stopping and starting again because they cannot handle the load from Traefik.

**Proposal**
Many loadbalancers support a notion of "maximum connections" to a service in order to safeguard services behind the loadbalancer from being overwhelmed by heavy traffic. I see that Traefik is already using the oxy library and leveraging features such as roundrobin and circuitbreakers. It seems very feasible to add another feature for connection limit which the oxy library has support for https://github.com/vulcand/oxy/blob/master/connlimit/connlimit.go.

We would simply need to add another configuration for Traefik for maxConnections and presumably wire it up where the oxy decorators are being wrapped and constructed here https://github.com/containous/traefik/blob/6308ce2740b7c92e3c50b70eb82dd94ea89425a4/server.go?ts=2#L330

### PR DESCRIPTION
**Pull request by kevioke**
Fixes #300

### CODE REVIEW

**Comment by kevioke** [comment]
This is for https://github.com/containous/traefik/issues/300

**Comment by emilevauge** [comment]
Thanks @kevioke, great contribution :+1: 
Could you just rebase and add a description in the PR (we will use descriptions to generate a release note later ;) ).
Other than that, LGTM for me.
/cc @vdemeester

**Comment by vdemeester** [comment]
@kevioke needs a rebase, but yay, so cool :sunglasses: 
LGTM 🐹

**Comment by kevioke** [comment]
@vdemeester rebased gtg.

**Comment by vdemeester** [comment]
@kevioke thx :wink:

**Pull request merged**
