### PR TITLE
Healthcheck tests and doc

### PR DESCRIPTION
**Pull request by Juliens**

### CODE REVIEW

**Comment by shouze** [comment]
@Juliens ok so, to make it clear, what about providers? #708 Do we have to redefine healthchecks trhough labels? Maybe it could be described in the doc?

**Comment by rogeriollacerda** [comment]
@Juliens is possible to use healthcheck feature as a Marathon label? Something like this:

traefik.HealthCheck.Interval=10
traefik.HealthCheck.URL=/health

Tks!

**Comment by timoreimann** [comment]
@rogeriollacerda could you please create a new issue for your request? Thanks!

**Comment by rogeriollacerda** [comment]
@timoreimann Sure! Thanks

**Comment by timoreimann** [comment]
@rogeriollacerda's follow-up is at #1232.

**Pull request merged**
