### PR TITLE
Sort nodes before creating consul catalog config

### PR DESCRIPTION
**Pull request by keis**
I noticed traefik was reload constantly from config changes when nothing had actually changed and while I got to the point where the config produced is the same it is still reloading. Any ideas?

The watch of consul can return for various reasons and not of all of
them require a reload of the config. The order of nodes provided by
consul is not stable so to ensure a identical config is generated for an
identical server set the nodes needs to be sorted before creating the
config.

### CODE REVIEW

**Comment by emilevauge** [comment]
@keis: great :+1: 
Tests are failing ;)

**Comment by keis** [comment]
oops :sweat: tests should work now

I'm still trying figure out why the deep equal check is not working, I tried writing the json blobs to disk and they are the exact same to the checksum. I saw you where changing some other stuff in the area so maybe I'll wait for that and see if that changes anything.

**Comment by vdemeester** [comment]
hum this is weird, it's only failing on docker 1.10 :sweat: 
@keis you need to rebase too :angel: :sweat_smile:

**Comment by keis** [comment]
Some random timing issue with the integration tests I think.

**Comment by emilevauge** [comment]
@keis : 
> I'm still trying figure out why the deep equal check is not working, I tried writing the json blobs to disk and they are the exact same to the checksum. I saw you where changing some other stuff in the area so maybe I'll wait for that and see if that changes anything.

I made a fix on that. The deepEquals is made earlier, and the entrypoints from defaultEntryPoints are added to the configuration BEFORE the deepEquals now.

You can test the PR using image `containous/traefik/pr-477` if you want.

**Comment by emilevauge** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by keis** [comment]
Hmm. that did still not fix it :'(

but writing even more json to the disk I found that the "old" config also have `loadBalancer` blocks in the backend config where the new from the provider does not

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            },
            "loadBalancer": {
                "method": "wrr"
            }
        },
```

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            }
        },
```

**Pull request merged**
