### PR TITLE
Postgres provider for traefik

### PR DESCRIPTION
**Pull request by srshanmugam**
### Description

This PR is for adding postgres provider feature to traefik

### CODE REVIEW

**Comment by ldez** [comment]
@srshanmugam Thanks for the contribution 👍 

Could fix this problem:
```
These files are not properly gofmt'd:
 - provider/postgres/postgres.go
 - server/configuration.go
 - server/server.go
```
https://semaphoreci.com/containous/traefik/branches/pull-request-1856/builds/1

**Comment by ldez** [comment]
@srshanmugam please execute `make validate` in your computer to validate the code.

You can also run `make` to ensure your code build.

**Comment by srshanmugam** [comment]
Build is failing due to blank import in pq package. I added a comment stating why it is needed. Golint still fails on that file. What's the best way to comment to avoid blank import package errors?

**Comment by timoreimann** [comment]
The offending import is on line 13. You probably need to place the comment right before that.

**Comment by srshanmugam** [comment]
Unit test is failing - expecting lib/pq dependency package under vendor directory? Do I need to commit lib/pq dependency under vendor/github.com?

**Comment by ldez** [comment]
@srshanmugam see https://github.com/containous/traefik/blob/master/.github/CONTRIBUTING.md

**Comment by ldez** [comment]
@srshanmugam please run the command `make`, to ensure your code build on your computer, before push.

**Comment by ldez** [comment]
to add your dependency:
1. Revert `glide.yml`, `glide.lock` and `vendor`. After that you must have nothing in the git stage.
1. Use the [github.com/multiplay/glide-pin](https://github.com/multiplay/glide-pin) plugin: `glide pin --exact`
1. Commit the `glide.yml` with pinned version
1. Add dependency: `./script/glide.sh get YOUR/DEPENDENCY`
1. Commit `glide.yml`, `glide.lock` and `vendor`
1. Revert the pin commit: `git revert HASH_OF_PIN_COMMIT`
1. Edit manually `glide.yml` to add the dependency
1. Use [glide-hash](https://github.com/mattfarina/glide-hash) to get the manifest file hash and put it in the lock file to please `validate-glide`.
1. Commit `glide.yml` and `glide.lock`
1. Squash all previous commit: `git rebase -i HASH`

**Comment by emilevauge** [comment]
Hi @srshanmugam 
thanks a lot for your work !
We are currently working on [adding plugins support into Traefik](https://github.com/containous/traefik/pull/1865) and we think your proposal would fit perfectly into this, as a third party provider :)
I suggest that we close this PR and we open a new one as soon as plugin are merged into master. 
Looks good to you ?

**Comment by srshanmugam** [comment]
@emilevauge, would this change be merged in to master?

**Comment by ldez** [comment]
@srshanmugam 
> I suggest that we close this PR and we open a new one as soon as plugin are merged into master.
> Looks good to you ?

**Comment by srshanmugam** [comment]
does this mean, with the new PR opened for postgres support, there would be some changes needed on top of plugin support?

**Comment by emilevauge** [comment]
@srshanmugam Probably some few changes yes.
Closing this one for now.

**Pull request closed without merging**
