### PR TITLE
Switch to golang/dep.

### PR DESCRIPTION
**Pull request by timoreimann**
This is a WIP towards switching traefik from using glide as a dependency management tool to golang/dep.

Nothing serious yet. I was already positively surprised to see that I could run all provider tests locally without any problems. Let's see how the full CI does.

### CODE REVIEW

**Comment by timoreimann** [comment]
It's green! Omygodohmygodohmygod -- the CI is **GREEN**!

**Comment by emilevauge** [comment]
WOW, that's amazing 😎
I think it would be safer to keep house in addition to dep for a while. That's what is advised by Sam Boyer himself ;)

**Comment by timoreimann** [comment]
`make crossbinary` working too... reverting that change again.

**Comment by traefiker** [comment]
Closed by #2681.

**Pull request closed without merging**
