### PR TITLE
Use first port by default

### PR DESCRIPTION
**Pull request by guilhem**
This feature use first port (PORT0) by default when there is multiple of ports

### CODE REVIEW

**Comment by emilevauge** [comment]
@guilhem I'm not sure I understand your code ^^
Where to you choose the first port by default ?

**Comment by guilhem** [comment]
@emilevauge indeed, `getPort` was already doing it (badly) here: https://github.com/guilhem/traefik/blob/5641af437e9242dce64e121eeae10e5869fd4d52/provider/marathon.go#L325
I didn't change behavior to not introduce other bug.

I just change filter who was removing this case.

**Comment by emilevauge** [comment]
Oh indeed ;)

**Comment by vdemeester** [comment]
@guilhem @emilevauge question though, should we do that for other providers ? (like the `docker` one 👼)

**Comment by guilhem** [comment]
anything is ok for me. :)

**Comment by emilevauge** [comment]
@vdemeester 
>@guilhem @emilevauge question though, should we do that for other providers ? (like the docker one :angel:)

Maybe yes, we should stay consistent.

**Comment by vdemeester** [comment]
@emilevauge hum, should we do that for docker and other providers for 1.1 then ? 👼

**Comment by guilhem** [comment]
@emilevauge @vdemeester done in latest commit. to be used or not

**Comment by emilevauge** [comment]
@guilhem thanks for those additions :)
/cc @containous/traefik

**Pull request merged**
