### PR TITLE
 Move webui to FountainJS with Webpack

### PR DESCRIPTION
**Pull request by micaelmbagira**
- webui migrated to FountainJS
- now uses Webpack instead of Bower/Wiredep
- Some modifications in `src` regarding the import of modules since we use Webpack
- FountainJS webapps require Node4+ and NPM3+

### CODE REVIEW

**Comment by micaelmbagira** [comment]
Rebased 😉

**Comment by emilevauge** [comment]
@micaelmbagira thanks :)
It seems you removed `webui/readme.md`, is it intended ?

**Comment by micaelmbagira** [comment]
Right, it wasn't on purpose, I've just added it

**Comment by emilevauge** [comment]
There is an issue building the image, it seems gulp is not available: https://travis-ci.org/containous/traefik/jobs/147392567#L1611

**Comment by micaelmbagira** [comment]
Yes, we should replace `gulp` with `npm run build` in Makefile and so npm will use the local gulp. Even on your laptop, you need to run `npm run build` if you don't want to install gulp globally

**Comment by emilevauge** [comment]
OK I tried using in Makefile:
```
generate-webui: build-webui
	if [ ! -d "static" ]; then \
		mkdir -p static; \
		docker run --rm -v "$$PWD/static":'/src/static' traefik-webui npm run build; \
		echo 'For more informations show `webui/readme.md`' > $$PWD/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md; \
	fi
```
but I got :
```
[11:52:25] Loading /src/webui/gulp_tasks/browsersync.js
[11:52:25] Loading /src/webui/gulp_tasks/karma.js
[11:52:26] Loading /src/webui/gulp_tasks/misc.js
[11:52:26] Loading /src/webui/gulp_tasks/webpack.js
[11:52:27] Using gulpfile /src/webui/gulpfile.js
[11:52:27] Starting 'default'...
[11:52:27] Starting 'clean'...
[11:52:27] 'clean' errored after 9.89 ms
[11:52:27] Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (/src/webui/node_modules/del/index.js:19:9)
    at /src/webui/node_modules/del/index.js:35:5
    at Array.map (native)
    at /src/webui/node_modules/del/index.js:33:28
    at run (/src/webui/node_modules/core-js/modules/es6.promise.js:87:22)
    at /src/webui/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/src/webui/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[11:52:27] 'default' errored after 13 ms
```

**Comment by micaelmbagira** [comment]
Does it work now ? I needed to force deleting a folder in parent directory, same than https://github.com/containous/traefik/blob/master/webui/gulp/build.js#L95

**Comment by emilevauge** [comment]
LGTM!
Great job @micaelmbagira ! Thanks a lot :)

**Pull request merged**
