### PR TITLE
[Bugfix] "storageFile" instead of "storage"

### PR DESCRIPTION
**Pull request by jensneuber**
Hi,
it took me 2 hours to notice, that it should say "storageFile" instead of just "storage".

### CODE REVIEW

**Comment by SantoDE** [comment]
LGTM! 👼 

Thanks for your contribution :-)

**Comment by emilevauge** [comment]
Hum, storagefile is deprecated. It should work with storage. Did you have an issue with storage?

**Comment by qmx** [comment]
I'm using `storage` fine here, saw the deprecation notice on debugging logs - traefik v1.1.0-rc3

**Comment by emilevauge** [comment]
Ping @jensneuber, I'm closing this PR, as you can still use `storagefile` but it has been deprecated in favor of `storage`. Thanks for this contribution anyway :)

**Pull request closed without merging**
