### PR TITLE
Add ppc64le platform support

### PR DESCRIPTION
**Pull request by mkumatag**
### What does this PR do?

This PR is for supporting ppc64le platform support

### Motivation

Recently I attended a talk about traefik in [devconf 2018 event](https://devconfin2018.sched.com/event/FA7c/traefik-the-cloud-native-edge-router) by @dduportal , I liked the project and felt needed for ppc64le platform, hence sending this PR for making it availble on ppc64le platform.

Thanks,
Manjunath.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by mkumatag** [comment]
@ldez may I know the reason for that? What exactly the difference between these two files?

**Comment by emilevauge** [comment]
@mkumatag 
Our day-to-day CI (in PRs) is only testing with the script `crossbinary-default`, in order to save time. We only test `amd64` architecture at each PR as generating every architectures binaries takes a lot of time.
Other architectures should be put in `crossbinary-others` then.
Makes sense ?

**Comment by mkumatag** [comment]
> @mkumatag
> Our day-to-day CI (in PRs) is only testing with the script crossbinary-default, in order to save time. We only test amd64 architecture at each PR as generating every architectures binaries takes a lot of time.
> Other architectures should be put in crossbinary-others then.
> Makes sense ?

make sense lemme move the content to crossbinary-others script.

**Comment by mkumatag** [comment]
@emilevauge @ldez made necessary changes, PTAL..

**Comment by ldez** [comment]
@mkumatag you don't need to create a new PR, we manage this with some "merge-back" https://github.com/containous/traefik/pulls?q=is%3Apr+in%3Atitle+merge+is%3Aclosed

**Comment by emilevauge** [comment]
Thanks for proposing @mkumatag :) We usually cherry pick every 1.x commits into master few days after the initial merge. It should land there soon!

**Comment by mkumatag** [comment]
@ldez @emilevauge Thanks for the information.

**Pull request merged**
