### PR TITLE
Remove duplicated link to Kubernetes.io in README.md

### PR DESCRIPTION
**Pull request by oscerd**
Just removed a duplicated link into README. Nothing really important :-)

### CODE REVIEW

**Comment by emilevauge** [comment]
@oscerd thanks for noticing :)
There is an issue with the travis build. Could you rebase to solve this?

**Comment by oscerd** [comment]
I updated the commit date and pushed again

**Comment by oscerd** [comment]
It doesn't seems to need a rebase, but maybe I'm losing something :-)

**Comment by oscerd** [comment]
The problem seems to be with this 

[ERROR]	Failed to set version on github.com/mailgun/manners to fada45142db3f93097ca917da107aa3fad0ffcb5: Unable to update checked out version

**Comment by oscerd** [comment]
Let me know if it's my fault

**Comment by emilevauge** [comment]
OK, this issue is solved on branch 1.1, can you rebase on this branch? I just changed your PR to v1.1 branch. Thanks :)

**Comment by oscerd** [comment]
emilevague, sorry for this, I was looking at master branch. Sorry :-)

**Comment by oscerd** [comment]
My fault anyway :-D

**Comment by oscerd** [comment]
Rebased again.

**Comment by oscerd** [comment]
Thanks. It was a minor problem :-)

**Pull request merged**
