### PR TITLE
#216: sets passHostHeader to true by default

### LINKED ISSUE #216: Set new default values for docker-based frontends?
I ran into issues with redirects and ran into the `passPostHeader`-flag.

Is there any way to change the default for this? We don't actually put any labels on our containers and the default configuration seems to work fine. Except for one thing, the `passPostHeader` needs to be set to true.

Is there any way for me to change this globally, without having to add labels to all containers?

Another one just for my curiosity... ;) Why is `passPostHeader` false by default? What is the usecase for that?

### PR DESCRIPTION
**Pull request by stongo**
This PR sets passHostHeader to true by default.
Fixes #216

### CODE REVIEW

**Comment by samber** [comment]
I think you forgot the ConsulCatalog provider (template/consul_catalog.tmpl - line 32)

**Comment by stongo** [comment]
added

**Comment by stongo** [comment]
found a bug that I need to fix

**Comment by emilevauge** [comment]
@stongo: thanks a lot!
There is currently an issue with travis on go cross compilations. I need to investigate on it before reviewing your PR.

**Comment by emilevauge** [comment]
You can now rebase to master to get travis working again ;) The issue was in https://github.com/mitchellh/gox.

**Comment by stongo** [comment]
Rebased and passing! w00t

**Comment by emilevauge** [comment]
Well done @stongo !
Thanks a lot :)
LGTM
/cc @vdemeester

**Comment by vdemeester** [comment]
@stongo needs a rebase :sweat_smile: 
Otherwise, LGTM 🐸

**Comment by stongo** [comment]
Rebased

**Pull request merged**
