### PR TITLE
Replace underscores to dash in autogenerated urls (docker provider)

### LINKED ISSUE #1043: Normalize auto generated frontend-rule (docker)
### What version of Traefik are you using (`traefik version`)?
Version:      v1.1.2
Codename:     camembert
Go version:   go1.7.4
Built:        2016-12-15_10:21:15AM
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml...)?
/traefik --web --retry --retry.attempts=10 --docker --docker.watch --docker.swarmmode --docker.domain=my.domain.org --logLevel=DEBUG --entryPoints=Name:http Address::80 Redirect.EntryPoint:https --defaultEntryPoints=http,https --web.address=:8081 --entryPoints=Name:http2 Address::8080 --entryPoints=Name:https Address::443 TLS:traefik.crt,traefik.key

### What did you do?
I use docker 1.13 rc7, with a docker-compose file and the docker stack deploy command
This create a service (swarm mode) named
```
<stack>_<service>
```

### What did you expect to see?
I want traefik create a frontend rule like
```
<stack>-<service>.<default_domain>
``` 

### What did you see instead?
Traefik take the service name, so
```
<stack>_<service>.<default_domain>
```

### So what can we do?
Can traefik change the underscore to hyphen in the normalize process ?
Cause underscores are not valid URI character
See https://tools.ietf.org/html/rfc1035
```
<domain> ::= <subdomain> | " "

<subdomain> ::= <label> | <subdomain> "." <label>

<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]

<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>

<let-dig-hyp> ::= <let-dig> | "-"

<let-dig> ::= <letter> | <digit>

<letter> ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

<digit> ::= any one of the ten digits 0 through 9
```

Thanx for reading

### PR DESCRIPTION
**Pull request by WTFKr0**
Closes #1043

### CODE REVIEW

**Comment by SantoDE** [comment]
Hey @WTFKr0 ,

thank's for your contribution :) Can you rebase your branch please, so it fires off again with travis and stuff?

Thanks :-)

WDYT @vdemeester ?

**Comment by emilevauge** [comment]
@WTFKr0 some tests are failing, could you have a look ?

**Comment by WTFKr0** [comment]
Don't know what are these errors...
Don't think my code do that :D 
```
----------------------------------------------------------------------
PASS: docker_test.go:128: DockerSuite.TestDockerContainersWithLabels	1.689s
PASS: docker_test.go:164: DockerSuite.TestDockerContainersWithOneMissingLabels	1.717s
PASS: docker_test.go:78: DockerSuite.TestSimpleConfiguration	0.504s
PASS: consul_test.go:399: ConsulSuite.TestCommandStoreConfig	3.556s
ERRO[0026] Datastore sync error: Object lock value: expected 1420e2ba-072f-4e6f-a4e5-8e35963a4c6a, got 2842cf2a-43be-4c70-9a37-1cd4567f5c75, retrying in 253.203223ms 
ERRO[0028] Datastore sync error: Object lock value: expected 4e8bcb9e-08d1-4052-addb-7eeaae6ecf58, got 349e3145-e94a-4e41-8114-3221668c0fa4, retrying in 641.745199ms 
[...]
ERRO[0060] Datastore sync error: Object lock value: expected 1c774173-66b0-44e4-ac27-148cdf0f0666, got c94f37f4-ea07-4baf-919f-1060e2e66f53, retrying in 572.685001ms 
ERRO[0060] Datastore sync error: Object lock value: expected e377c3f7-222f-4e16-b465-e9b032bf79db, got 1c774173-66b0-44e4-ac27-148cdf0f0666, retrying in 356.18893ms 
PASS: consul_test.go:440: ConsulSuite.TestDatastore	39.698s
PASS: consul_test.go:249: ConsulSuite.TestGlobalConfiguration	3.473s
PASS: consul_test.go:126: ConsulSuite.TestNominalConfiguration	4.301s
PASS: consul_test.go:108: ConsulSuite.TestSimpleConfiguration	3.769s
```

**Comment by WTFKr0** [comment]
Ok I saw it : 
```
FAIL: docker_test.go:96: DockerSuite.TestDefaultDockerContainers
docker_test.go:117:
    c.Assert(resp.StatusCode, checker.Equals, 200)
... obtained int = 404
... expected int = 200
```

I look

**Pull request merged**
