### PR TITLE
Fix Marathon config load on connection error

### PR DESCRIPTION
**Pull request by diegooliveira**
### What does this PR do?

Add a logic to keeping trying to load the initial configuration if Marathon is inaccessible the first time.

### Motivation

There is an open issue, #3974, listing the problem.

### CODE REVIEW

**Comment by ldez** [comment]
Could you use the branch 1.7 instead of 1.5?

**Comment by diegooliveira** [comment]
@ldez yes, I'll make a pull request for that versions tonight. We are using the 1.5 version, so it would be nice to have the fix in all three versios, 1.5, 1.6 and 1.7.

**Comment by diegooliveira** [comment]
@ldez are you going to release a new version of the 1.5 branch? We are using this in production and this  is a current problem in this version.

**Comment by diegooliveira** [comment]
@ldez I just submited two PRs #4150 for v1.6 and #4151 for v1.7

**Comment by ldez** [comment]
We create release only for version 1.7 according to:

> Each version is supported until the next one is released (e.g. 1.1.x will be supported until 1.2.0 is out)

https://github.com/containous/traefik#release-cycle

**Pull request closed without merging**
