### PR TITLE
Add Traefik logo (First proposition)

### PR DESCRIPTION
**Pull request by pekha**
Here is a traefik logo propostion !

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks a lot @pekha :heart_eyes: 
@vdemeester @ldez your thoughts?
I have one question and one proposal:
* Why does the blue cloud cry ^^ ?
* What do you think of moving the subway stations a bit to the left? I think it would be more balanced ;)

**Comment by pekha** [comment]
:) 
- The cloud does not cry, it's more like if the cloud were painted using paint spray.
- I agree with you the 3 spots seems to be centered, il will chnage it

**Comment by thaJeztah** [comment]
Oh, nice! Could you also provide a vector version of the logo, in case different resolutions or versions are needed in the future?

**Comment by emilevauge** [comment]
+1 for a SVG version ;)
@pekha, OK for the NOT crying cloud ^^
I know I'm boring, but on your 2nd version, I found it too much on the left :scream:.
Or I don't know, maybe the NOT crying cloud is a bit too big?
Other than this detail, I think it's really cool!

**Comment by pekha** [comment]
For now it's hard tu reduce the "Not crying cloud" size only. i just try to move on the right the 3 spots. tell me if your prefer.

**Comment by emilevauge** [comment]
:+1:

**Comment by thaJeztah** [comment]
I think removing the ethernet cable/plug on the left may make the logo a bit more "abstract", and possibly "stronger". I don't think it's really needed (just my 0.02c) :smile:

**Comment by emilevauge** [comment]
Yeah maybe it would be better to be stay abstract :) We don't even touch cables anymore ^^

**Comment by pekha** [comment]
Is it right now ?

**Comment by emilevauge** [comment]
Definitely better for me :)

**Comment by vdemeester** [comment]
@pekha looks good :)

I was wondering about small size logo too. How this one would look on a smaller size scale (like 64x64 or ?). I think we might want to have simplified version for smaller size, wdyt ?

**Comment by thaJeztah** [comment]
Yup, looks better! Thanks!

**Comment by emilevauge** [comment]
I love the horizontal one!

**Comment by pekha** [comment]
I just push 2 64px logo, a vertical and an horizontal one. Maybe the 2 versions can be usefull depending the use case.

**Comment by ldez** [comment]
I see 2 problems :
- blue is not blue (Traefik blue #00B1FF)
- SVG files aren't standard, is an Inkskape SVG file

You can see that :
```
inkscape:export-filename="C:\Users\pkeersbulik\traefik\traefik\docs\img\Traefik_logo_64_vert.png"
```

Can you change the color and the file format please.

**Comment by emilevauge** [comment]
@ldez, by 
> blue is not blue (Traefik blue #00B1FF)

you mean the blue currently used in UI?

**Comment by ldez** [comment]
I mean blue in Traefik's typo : https://camo.githubusercontent.com/0d83f4ec95b28ecc0353078ca4364bf461b99c2d/687474703a2f2f7472616566696b2e6769746875622e696f2f7472616566696b2e6c6f676f2e737667

**Comment by emilevauge** [comment]
@ldez yep, but this new logo will replace it, so why not keeping the same blue but I'm not sure that it's critical.

**Comment by ldez** [comment]
Ok, no problem.

Otherwise :
- Cloud, it's already seen too much.
- I like the spot however

**Comment by vdemeester** [comment]
Thanks again for the work @pekha, but now that traefik has a logo, I'm gonna close this one :stuck_out_tongue:.

**Comment by emilevauge** [comment]
For the record, @pekha designed the new gopherized logo ;)

**Comment by vdemeester** [comment]
:heart_eyes_cat: @pekha

**Pull request closed without merging**
