### PR TITLE
Check X-Forwarded-For and X-Real-Ip headers for whitelisted IPs

### PR DESCRIPTION
**Pull request by joe-bowman**
Taking @joshdvir's contribution in https://github.com/containous/traefik/pull/1915 and make it configurable as per @emilevauge and @marco-jantke requests.

Docs and tests to follow!

### CODE REVIEW

**Comment by emilevauge** [comment]
@joe-bowman thanks a lot for this great contribution!
I'm still not sure about adding this complexity into Traefik on white listing though :thinking: 
What about using the [authentication forward mechanism](http://docs.traefik.io/configuration/entrypoints/#forward-authentication) we introduced recently ? You could use a delegate server that would manage all your white listing needs instead.
WDYT?
/cc @containous/traefik

**Comment by OverlyExcessive** [comment]
For our use cases using a forwarding auth server would mean more overhead than the source white listing. We have some services that we only want to expose internally but some publicly. 
Source white listing is great because we only need to add a service label to make it work. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Emile Vauge <notifications@github.com> Date: 26/10/2017  15:44  (GMT+01:00) To: containous/traefik <traefik@noreply.github.com> Cc: "Gabriel A.S" <gabriel.a.svensk@gmail.com>, Manual <manual@noreply.github.com> Subject: Re: [containous/traefik] Check X-Forwarded-For and X-Real-Ip headers for whitelisted IPs (#2235) 
@joe-bowman thanks a lot for this great contribution!

I'm still not sure about adding this complexity into Traefik on white listing though 🤔

What about using the authentication forward mechanism we introduced recently ? You could use a delegate server that would manage all your white listing needs instead.

WDYT?

/cc @containous/traefik

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/containous/traefik","title":"containous/traefik","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/containous/traefik"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilevauge in #2235: @joe-bowman thanks a lot for this great contribution!\r\nI'm still not sure about adding this complexity into Traefik on white listing though :thinking: \r\nWhat about using the [authentication forward mechanism](http://docs.traefik.io/configuration/entrypoints/#forward-authentication) we introduced recently ? You could use a delegate server that would manage all your white listing needs instead.\r\nWDYT?\r\n/cc @containous/traefik "}],"action":{"name":"View Pull Request","url":"https://github.com/containous/traefik/pull/2235#issuecomment-339670261"}}}

**Comment by emilevauge** [comment]
@OverlyExcessive for this use case, we recommend to use 2 Traefik instances (internal & public), and use [contraints](http://docs.traefik.io/configuration/commons/#constraints) to allocate internal & public services to the right Traefik instance.

**Comment by OverlyExcessive** [comment]
Hi,
That would require us to open up another port on the host machines which we in term must add extra routing logic for in our L4 load balancer.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Emile Vauge <notifications@github.com> Date: 26/10/2017  17:02  (GMT+01:00) To: containous/traefik <traefik@noreply.github.com> Cc: "Gabriel A.S" <gabriel.a.svensk@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [containous/traefik] Check X-Forwarded-For and X-Real-Ip headers for whitelisted IPs (#2235) 
@OverlyExcessive for this use case, we recommend to use 2 Traefik instances (internal & public), and use contraints to allocate internal & public services to the right Traefik instance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/containous/traefik","title":"containous/traefik","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/containous/traefik"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilevauge in #2235: @OverlyExcessive for this use case, we recommend to use 2 Traefik instances (internal \u0026 public), and use [contraints](http://docs.traefik.io/configuration/commons/#constraints) to allocate internal \u0026 public services to the right Traefik instance."}],"action":{"name":"View Pull Request","url":"https://github.com/containous/traefik/pull/2235#issuecomment-339695242"}}}

**Comment by emilevauge** [comment]
@joe-bowman Any news on my comment https://github.com/containous/traefik/pull/2235#issuecomment-339670261 ?

**Comment by Gabology** [comment]
Any updates on this? Forwarding auth is not really a good fit for us, as we would have to then forward all requests to the forwarding auth server and we have traefik deployed globally in a variety of regions.

**Comment by beenanner** [comment]
I just ran into this the other day. With docker swarm mode all request come from the swarms 10.255.x.x address making whitelisting impossible based on standard client ip.

**Comment by keiths-osc** [comment]
I use traefik in AWS in a Kubernetes cluster where the nodes are behind ELBs.   I really would prefer to not have to duplicate and maintain all the whitelist checking logic in a whole separate service of my own when traefik already has all the logic and could just do it directly, if only it knew the right IP to check.

**Comment by lheinlen** [comment]
I have the same use case as @keiths-osc and would also strongly prefer to avoid maintaining a separate service to perform these checks.

**Comment by nemosupremo** [comment]
I noticed this PR, and its similar to what I'd like to setup as well (also looking for #2260). Currently I'm looking up to setup an instance of traefik behind AWS ELB / GCP LB, while whitelisting some IPs to bypass Basic Http Authorization.

I don't think the Authorization Forward Mechanism is a good solution - it introduces a lot of complexity, a network hop, plus having to monitor another service (that could end up becoming a SPOF) for pretty simple functionality. 

I think what nginx does with the RealIP module works fine -

```
real_ip_header X-Forwarded-For;
set_real_ip_from 0.0.0.0/0;
```

This basically states that the last IP in the `X-Forwarded-For` should be considered the client IP, but its only allowed from remote addresses in `0.0.0.0/0` (everywhere). If a user requires more security then they can set `set_real_ip_from` to the correct ip or ip ranges they want to trust.   

```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  whiteListSourceRange = ["127.0.0.1/32", "192.168.1.7"]
  whiteListTrustForward = "192.168.0.0/16"
```

If security / hand-holding is required, you could warn or crash if `whiteListTrustForward` is set to `0.0.0.0/0`.

**Comment by beenanner** [comment]
Agree @nemosupremo I just tested this with my Google's LB and it appears that the X-Forwarded-For header isn't pulling the first IP off the list for my use-case as the first IP is my pubic address and the last 2 are Google LBs

```
Hostname: 8a592c4309f1
IP: 127.0.0.1
IP: 10.0.7.32
IP: 10.0.7.14
IP: 172.18.0.5
GET / HTTP/1.1
Host: whoami.test.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Upgrade-Insecure-Requests: 1
Via: 1.1 google
X-Cloud-Trace-Context: f11cc2e3cce29b0f364b64061b330383/13854514456674479385
X-Forwarded-For: 170.20.11.15, 35.190.20.125, 130.211.3.126
X-Forwarded-Host: whoami.test.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: fc451219e95c
X-Real-Ip: 130.211.3.126
```

@joe-bowman let me know if there is a tag available and I can test this change for my use-case. I'm using Docker Swarm mode.

**Comment by nemosupremo** [comment]
First, @beenanner, AWS ELB claims to insert the public IP at the end (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for), I'd have to double check the standard. In your case it's also strange that your public IP is the first in the list, while however the `X-Real-Ip` header is the last IP in the `X-Forwarded-For` list. I'll double check with AWS ELB, as a quick google search shows that they might be doing the same, and that their documentation might be wrong.

Next,  I actually started working on this in a branch, and because what I need was closer to #2260, I ended up implementing it under the `Auth` directive, my conf looks like this:

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth.basic]
  users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"]
  whiteListSourceRange = ["8.8.8.8/24"]
  whiteListTrustProxy = true
```

**Comment by beenanner** [comment]
@nemosupremo very strange indeed as far as I'm aware the standard for x-forwarded-for is to just append to the x-forwarded-for header as it hops from client to destination. It would be a shame if those docs are true. :( I guess for the time being for my use-case I'll need to have a whitelisting nginx proxy outside of traefik to handle the whitelisting before it hits traefik until the multiple IPs in x-forwarded-for stuff gets sorted out.

**Comment by nemosupremo** [comment]
I took a look at [Google's Docs](https://cloud.google.com/compute/docs/load-balancing/http/#components) for LB, and it looks like Google is doing the weird thing here.

If you manufactured a request like Amazon's and passed it through Google LB, you would actually get:
```
X-Forwarded-For:  ip-address-1, ip-address-2, client-ip-address, <global forwarding rule external IP>, <proxies running in GCP>
```

GCP is actually extra IP address onto the end, its also just adding other values on there as well - see this [post on someone hitting this same problem](https://groups.google.com/forum/#!topic/gce-discussion/ibltta2ZAqA).

**Comment by beenanner** [comment]
@nemosupremo hmm it still seems to act the same when I did a test setup in AWS. Maybe the ELBs act different but the ALB seems to act the same as google's HTTP(s) LBs.

```
Hostname: 04dcc71a7a62
IP: 127.0.0.1
IP: 10.0.0.4
IP: 10.0.0.5
IP: 172.18.0.4
GET / HTTP/1.1
Host: whoami.1.jml2yg0ur6xvzbtvyjf75elub.docker.localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
X-Amzn-Trace-Id: Root=1-5a20270b-58b443b640abbb6669ddead4
X-Forwarded-For: 170.20.11.22, 10.22.17.40
X-Forwarded-Host: whoami.1.jml2yg0ur6xvzbtvyjf75elub.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 64c535ec9dd1
X-Real-Ip: 10.22.17.40
```

So does traefik need to implement something like `set_real_ip_from`?

**Comment by beenanner** [comment]
And here is the one from the Google LB now.

```
Hostname: fba5d78c564b
IP: 127.0.0.1
IP: 10.255.0.31
IP: 10.255.0.30
IP: 172.18.0.5
IP: 10.0.7.24
IP: 10.0.7.14
GET / HTTP/1.1
Host: whoami.test.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: Keep-Alive
Upgrade-Insecure-Requests: 1
Via: 1.1 google
X-Cloud-Trace-Context: a2d6aa72c6ab9e10b283b8060d1e7ab6/11011894925047814559
X-Forwarded-For: 170.20.11.22, 35.190.20.120
X-Forwarded-Proto: http
```

**Comment by beenanner** [comment]
> Can you try running a request like
> 
> curl -H"X-Forwarded-For: 8.8.8.8" http://whoami.test.com
> Edit: Also here (https://cloud.google.com/appengine/docs/flexible/go/how-requests-are-handled) describes how X-Forwarded-For works in Google. The issue with using the first IP, is that I believe that first IP isn't the one you want (see my example, where the first ip might be 8.8.8.8, even though we are clearly not 8.8.8.8)'

You are correct if you add to the forwarded for it will show up but that known.

```
Hostname: 04dcc71a7a62
IP: 127.0.0.1
IP: 10.0.0.4
IP: 10.0.0.5
IP: 172.18.0.4
GET / HTTP/1.1
Host: whoami.1.jml2yg0ur6xvzbtvyjf75elub.docker.localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
X-Amzn-Trace-Id: Root=1-5a2029d6-06ef43ea3219eb4f416bf1ef
X-Forwarded-For: 8.8.8.8, 170.20.11.22, 10.22.17.40
X-Forwarded-Host: whoami.1.jml2yg0ur6xvzbtvyjf75elub.docker.localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 64c535ec9dd1
X-Real-Ip: 10.22.17.40
```

and for GCP
```
Hostname: fba5d78c564b
IP: 127.0.0.1
IP: 10.255.0.31
IP: 10.255.0.30
IP: 172.18.0.5
IP: 10.0.7.24
IP: 10.0.7.14
GET / HTTP/1.1
Host: whoami.cnet.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: Keep-Alive
Upgrade-Insecure-Requests: 1
Via: 1.1 google
X-Cloud-Trace-Context: 143a2e16b0c62a893d2b6b948776083a/12177613093041323368
X-Forwarded-For: 8.8.8.8, 170.20.11.22, 35.190.20.120
X-Forwarded-Proto: http
```

It seems like we would need something like nginx's `set_real_ip_from` were you can whitelist what IPs to trust for x-forwarded-for. In both cases of AWS and GCP we would just trust 35.190.x.x and  10.22.x.x for what x-forwarded-for should be used.

**Comment by nemosupremo** [comment]
@beenanner I've oped a new PR #2502, that takes your use case into account. If you know what the trusted IPs are of the Google Load Balancer, traefik will "skip" them until it gets to an untrusted IP.

**Comment by beenanner** [comment]
Thanks @nemosupremo! I'll take to conversation over there as I've been playing around with a nginx proxy to see what would be needed to grab the appropriate IP.

**Comment by emilevauge** [comment]
Hi @joe-bowman, thanks a lot for you contribution. We want to keep the authentication section as simple as possible and we think that your use case could be addressed differently. We advise you to either use a vpn, either use the [authentication forward mechanism](http://docs.traefik.io/configuration/entrypoints/#forward-authentication) we introduced recently.
Thanks @joe-bowman

**Pull request closed without merging**
