### PR TITLE
Native kubernetes ACME storage

### PR DESCRIPTION
**Pull request by Place1**
### What does this PR do?

This PR is an attempt to contribute towards the ideas in #2542 

Currently, this PR implements a very naive approach to storing the ACME information in native k8s objects, it simply takes the entire `acme.StoredData` struct and saves it in a secret called `traefik-acme-storage`.

Here are some discussion points that i'd love some input from others in the community (or even help to implement if anyone has time):
- concurrency/safety
    - we could implement a distributed lock using annotations on the secret to ensure safe concurrent access
    - we could break up the storage into many config-maps and secrets as mentioned in the original issue #2542 
        - probably still requires distributed locking
- automatic configuration reloading
    - i'm not very familiar with the codebase but i'm sure nodes will need to make use of k8s watch apis to reload ACME data when other nodes write
    - i'm not sure how this push based reloading works in the broader context of the codebase

I assume with safe concurrent access to the storage (be it 1 or many objects) using a lock + automatic configuration reloading we'll be able to have a fairly robust implementation where any node can participate in the acme challenge.

It'd be great for others to raise their own ideas on the implementation of this feature so we can get this moving! I think it will be a very useful feature for many use-cases of traefik.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Here's the configuration to use the Kubernetes storage implementation.

```toml
[acme]
# ...
[acme.kubernetes]
  namespace = "default"
```

### CODE REVIEW

**Comment by emilevauge** [comment]
Hey @Place1, thanks for your contribution.
As there is **no implementation** in this PR, I will close it as the discussions should remain in the initial issue.
Thanks for your understanding and comprehension.

**Comment by Place1** [comment]
@emilevauge sorry! i forgot to push the implementation (silly me, was late at night).

The current implementation stores acme data in a single k8s secret. It lacks the following:
1. ensuring instances of traefik in the cluster synchronise on the data
2. ensuring concurrent access to the data

I was hoping to get some eyes on the PR so others could voice their opinions on where the implementation should go. I'm happy to keep the discussion in the issue though if that's preferred :smiley: 

If others see this PR and want to try it locally then here's the `config.toml` i've used:
```toml
# general config process config
defaultEntryPoints = ["http", "https"]
debug = true
logLevel = "DEBUG"

# http(s) traffic entrypoints
[entryPoints]
  [entryPoints.http]
  address = ":8080"
  [entryPoints.https]
  address = ":8443"
    [entryPoints.https.tls]

# letsencrypt config
[acme]
email = "admin@<domain>"
onHostRule = true
acmeLogging = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" # ACME staging server
entryPoint = "https"
[acme.kubernetes]
  namespace = "default"
[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "<domain>"
```

Considering my implementation uses `client_go`'s `InClusterConfiguration` it's a little tricky to run traefik outside the cluster while still using k8s (i.e. minikube). Here's how I did it.
1. run `kubectl proxy` to proxy your minikube k8s API to `localhost:8001`
2. `export KUBERNETES_SERVICE_HOST=localhost`
3. `export KUBERNETES_SERVICE_PORT=8001`
4. `kubectl get secret default-token-w278w -o=jsonpath="{.data['ca\.crt']}" | base64 --decode > /var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
5. `kubectl get secret default-token-w278w -o=jsonpath="{.data.token}" | base64 --decode > /var/run/secrets/kubernetes.io/serviceaccount/token`
4. create your config.toml
5. `go build cmd/traefik/traefik.go`
6. `./traefik -c config.toml`

the environment variables, ca.crt and token files make your local machine look like a k8s pod in the context of client_go's `InClusterConfiguration()`. This makes it easy to run traefik in your dev environment while it connects to your minikube.

sorry for writing so much but I thought it might be helpful to others

**Comment by Place1** [comment]
@emilevauge i've pushed the implementation but I dont think the github PR is updating to show the commit

**Comment by githubcdr** [comment]
would it be possible to have cert-manager work besides traefik in this opted scenario?

**Comment by mmack** [comment]
> would it be possible to have cert-manager work besides traefik in this opted scenario?

same here. I would love to use certmanager / external-dns for certs and dns and traefik just for loadbalancing. Anyone did that already? For http it works, for https i have troubles...

**Comment by danramteke** [comment]
@Place1 This would be really cool functionality to have in traefik! Could you try updating the pull request with your file changes? Or maybe making a new pull request?

**Pull request closed without merging**
