### PR TITLE
Mapping ExternalNames to custom ports

### PR DESCRIPTION
**Pull request by gildas**
### What does this PR do?
This fixes issue #1816 

Basically, if the `servicePort.Port` is not 443 or 80, we add it to the `url` (not the `name`).
And if the `servicePort.name` is 'https' we also use 'https' as the protocol. That allows to proxy https traffic to any port.

### Motivation

In my deployment, I need træfik to proxy to external servers on custom ports. I do not control these servers.

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
@gildas could you remove merge commit.

**Comment by gildas** [comment]
@ldez, not sure how this happened.
Should I submit another PR? Not sure I know how to remove the merge commit safely.

**Comment by ldez** [comment]
@gildas I will fix that.

**Comment by gildas** [comment]
You sure? Because I have already re-forked and am rewriting the fix.
As it is very small, it is easy to write.

**Comment by ldez** [comment]
You have completely broke the PR :disappointed: 
You don't need to "re-fork" or create a new PR for update you PR.

Now, you must open a new PR.

**Comment by gildas** [comment]
Sorry, I thought it would be the fastest way. My bad. Shame on me :(

**Pull request closed without merging**
