### PR TITLE
Documentation improvement for minikube users crd acme user guide

### PR DESCRIPTION
**Pull request by woodcockjosh**
### What does this PR do?

Updates the documentation to help users following the kubernetes crd acme guide with minikube

### Motivation

I had to figure out how to configure minikube on my own which was painful. Users that are testing something out for the first time often don't want to do so in a shared environment because they don't have access to do so. Minikube is a popular choice for testing and the guide should cover configuration which is not obvious to a new k8s user. 

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

N/A

### CODE REVIEW

**Comment by mpl** [comment]
@woodcockjosh Hi. I'm not saying we're not interested in the contribution, but I don't understand your motivation. If what you were looking for is simplicity of testing on your own machine, why not just follow the guide as it is and use k3s to mimic k8s?

**Comment by woodcockjosh** [comment]
> @woodcockjosh Hi. I'm not saying we're not interested in the contribution, but I don't understand your motivation. If what you were looking for is simplicity of testing on your own machine, why not just follow the guide as it is and use k3s to mimic k8s?

I don't want to use k3s :-) I am a minikuber. If my preference was k3s then yes maybe its good enough. I'm not sure really because I don't use k3s.

**Comment by dduportal** [comment]
Hi @woodcockjosh , thanks for this contribution. However, it's not really a documentation addon, but more a tutorial for very very specific use case (not minikube but nginx ingress in front of traefik).
Why would the end-user want to add nginx in front of traefik? 

Some arguments against this setup:

- Too complex: VM Network <-> Ingress Nginx (Service + pod)  <-> Ingress Traefik (Service + pod) <-> Application (Service + Pod). Not only it's not a recommended setup, but also beginners will be terribly lost (they are already enough things to learn).
- Minikube supports the Service of kind "Load Balancer" as explained in the minikube official documentation: https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service. Please note that even a Service of type "NodPort" can be used instead. 
- The goal of this user guide is to demonstrate Traefik with Let's Encrypt focused on Kubernetes. It's not a "getting started with Traefik and Kubernetes": the focus is different.


A proposal for you to fulfill the "minikube" part of your contribution: write a user guide, strictly focused on getting started with Traefik in Minikube. This would imply installing Traefik with a Service of type LoadBalancer (in the same spirit as the official "hello minikube" documentation I linked earlier in this comment). Goal would be to cover beginner using minikube. The end of such a guide could link to the "Kubernetes + Let's Encrypt" example explaining it's the "next steps" (aka. "once you're at ease with the basic concepts of Kubernetes, and base of HTTP routing with Traefik CRD, then you might want to check... for HTTPS with let's encrypt". WDYT?

**Comment by dduportal** [comment]
Hi @woodcockjosh do you mind switching on the community forum for getting help, to avoid discussing on a closed issue/PR as this subject is related to usage/config  while we try to keep the github tracker for bugs and features requests? 
Don't hesitate to mention me on the topic so I'll jump in to give you more explanations.

In parallel, you should strongly read the tutorial https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service to learn how to reach minikube from the host. I'll help you if you need further help.

**Comment by woodcockjosh** [comment]
@dduportal I don't need help. I know what I am doing. Thanks for assuming that I don't. I was asking what you wanted to be in the content of the article.

**Comment by dduportal** [comment]
@woodcockjosh my goal was to work collaboratively on this topic and share the intents of such an article. I'm not assuming anything as we never had any interaction before :)

**Pull request closed without merging**
