### PR TITLE
If Marathon doesn't have healthcheck, assume it's ok

### PR DESCRIPTION
**Pull request by gomes**
Healthcheck are not mandatory, so if a result is not present, assume it
is ok to continue. Fixes the case when a new leader is elected and
don't have any healthcheck result's, returning 404 to all requests.
https://github.com/containous/traefik/issues/653

### CODE REVIEW

**Comment by vdemeester** [comment]
/cc @containous/traefik 
Seems fine to me 👼

**Comment by errm** [comment]
LGTM

**Comment by errm** [comment]
@gomes needs a rebase :)

**Comment by gomes** [comment]
Done

**Comment by emilevauge** [comment]
@gomes thanks for this, LGTM :)
I'm sorry but could you rebase again? I will merge it right away.

**Comment by gomes** [comment]
@emilevauge done, I had to execute 2 times because of a build failure.

**Pull request merged**
