### PR TITLE
Merge v1.3 branch into master [2017-05-11]

### PR DESCRIPTION
**Pull request by timoreimann**
Brings #1581 into mainline.

### CODE REVIEW

**Comment by timoreimann** [comment]
I believe we should have this be part of 1.3 as well, so I cherry-picked the fix.

See PR 1581.

**Comment by timoreimann** [comment]
@ldez:

>It's a good idea to add this modification in 1.3 branch and the master

This PR handles master, and #1581 has been merged into the 1.3 branch earlier today. Anything missing from your point?

**Comment by ldez** [comment]
@timoreimann sorry mispelling

It's **not** a good idea to add this modification in 1.3 branch and the master

**Comment by emilevauge** [comment]
@timoreimann We still use the same process:

1. Bug fix PR on the release branch (here v1.3)
2. Merge v1.3 into master later

As https://github.com/containous/traefik/pull/1581 has already been merged into v1.3, I propose to simply close this one. OK for you @timoreimann ?

**Comment by timoreimann** [comment]
@emilevauge @ldez I repurposed this PR for the merge. Please have a look again.

**Comment by ldez** [comment]
:trollface: In the @timoreimann head: if I change the PR title, they don't see nothing...
`timoreimann:kubernetes-ignore-missing-pass-host-header-annotation` is not the `v1.3` branch, or I have miss somethings?

**Comment by timoreimann** [comment]
@ldez Locally I merged `upstream/v1.3` into `upstream/master` and pushed the result to `timoreimann:kubernetes-ignore-missing-pass-host-header-annotation`. It's a shame Github won't let me change PR branches, thereby uncovering my rebranding operation. :-)

The commits look okay to me though. Or did I miss something?

**Comment by timoreimann** [comment]
@ldez okay for you?

**Comment by ldez** [comment]
oops so quick...

**Comment by timoreimann** [comment]
Thanks 👏

**Pull request merged**
