### PR TITLE
Add status code text to webui bar chart tooltip

### PR DESCRIPTION
**Pull request by wader**
### What does this PR do?

So you don't have to lookup status code numbers

### Motivation

I keept googling them

### More

- [ ] Added/updated tests

Not sure how to add test for this?

### CODE REVIEW

**Comment by wader** [comment]
This changes the tooltip design a bit, now it's just "200 OK" before it was "[color] 200 [count]" with more padding

**Comment by ldez** [comment]
@wader I think you can use https://www.npmjs.com/package/http-status-codes to simplify the code.

**Comment by wader** [comment]
@ldez Ok, have switched to using http-status-codes now

**Comment by wader** [comment]
Let me know if there something else to fix

**Pull request merged**
