### PR TITLE
Add Rancher provider again

### PR DESCRIPTION
**Pull request by SantoDE**
### What does this PR do?

Adds the rancher provider again

### Motivation

Have rancher following the new provider system

### More

- [X] Added/updated tests
- [X] Added/updated documentation

### Additional Notes
Have fun @ldez , @juliens and others :-D

### CODE REVIEW

**Comment by juliens** [comment]
Do you think you can add the TCP part? ( you can take a look at #4621 )

**Comment by SantoDE** [comment]
Sure, I just wanted to have in a seperate PR (and when I did this, TCP was not implemented elsewhere :P)

**Comment by SantoDE** [comment]
ping @ldez , @juliens :) tcp support added and squashed

**Comment by EugenMayer** [comment]
Sorry i do not want to hijack the PR - just maybe a short "where to go" notice - i am migrating the old syntax to the new one, found https://docs.traefik.io/v2.0/providers/rancher/ and worked through it.
Also checked the migration guide which yet does not include rancher

Checked the forum

 - https://community.containo.us/t/rancher-behind-traefik-2-0-0-alpha8/823/16
 - https://community.containo.us/t/traefik-docker-letsencrypt-migration-v1-7-v2-0-epic-fail/1396/2

But i cannot see any reference of `providers.rancher.api` or `providers.rancher.metadata` in the new API. Where would i start a question / discussion about that, forum i guess once again, or stick this to a github issue?

**Pull request merged**
