### PR TITLE
Update systemd service file with new cli flags

### PR DESCRIPTION
**Pull request by keis**
Oops. was sitting on this change for a bit

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks @keis :)
LGTM, once rebased ;)

**Comment by keis** [comment]
`update branch` button did not do what I wanted. I'll do a proper rebase in a bit

**Comment by keis** [comment]
@emilevauge rebased!

**Comment by vdemeester** [comment]
LGTM 🐷

**Pull request merged**
