### PR TITLE
Clean glide

### PR DESCRIPTION
**Pull request by ldez**
### Description

Update `glide.yml`, `glide.lock` and `vendor`.

----
fix: sirupsen/logrus version

State:
- Current version: `10f801ebc38b33738c9d17d50860f484a0988ff5`
- Glide suggest: `f7f79f729e0fbe2fcc061db48a9ba0263f588252`

refs:
- https://github.com/sirupsen/logrus/commits/master?after=85b1699d505667d13f8ac4478c1debbf85d6c5de+34
- https://github.com/sirupsen/logrus/commit/10f801ebc38b33738c9d17d50860f484a0988ff5 (17 Mar 2017)
- https://github.com/sirupsen/logrus/commit/f7f79f729e0fbe2fcc061db48a9ba0263f588252 (19 Jan 2016)

---
fix: golang/protobuf version

`github.com/golang/protobuf` is used by:
- `github.com/prometheus/client_golang` (no version)
- `github.com/gogo/protobuf` (no version)
- `google.golang.org/appengine` (no version)
- `github.com/matttproud/golang_protobuf_extensions` (no version)

State:
- Current version: `2bba0603135d7d7f5cb73b2125beeda19c09f4ef`
- Glide suggest: `8616e8ee5e20a1704615e6c8d7afcdac06087a67`

Force to keep the current version.

Refs
- https://github.com/golang/protobuf/commit/2bba0603135d7d7f5cb73b2125beeda19c09f4ef (Mar 31, 2017) next commit the Apr 27, 2017.
- https://github.com/golang/protobuf/commit/8616e8ee5e20a1704615e6c8d7afcdac06087a67 (8 Jun 2016)

----

fix: Prometheus dependency version: matttproud/golang_protobuf_extensions

`matttproud/golang_protobuf_extensions` is used by:
- `github.com/prometheus/client_golang`
- `github.com/prometheus/common`

Force to the latest version.

Refs:
- https://github.com/matttproud/golang_protobuf_extensions/commits/master (no dependencies manager)
- 24 Apr 2016, https://github.com/matttproud/golang_protobuf_extensions/commit/c12348ce28de40eed0136aa2b644d0ee0650e56c (master, HEAD)
- 6 Apr 2015, https://github.com/matttproud/golang_protobuf_extensions/commit/fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a

------

fix: Mesos/k8s dependency version: golang/glog

`golang/glog` is used by:
- `github.com/mesos/mesos-go` (no version)
- `k8s.io/client-go` (`44145f04b68cf362d9c4df2182967c2275eaefed`)

In #353 (add Mesos provider, 20 Jul 2016), the `golang/glog` hash is `fca8c8854093a154ff1eb580aae10276ad6b1b5f`.

The problem appear in #836 (use k8s client, 1 Dec 2016).

Refs:
- Traefik:
  - https://github.com/containous/traefik/pull/836
  - https://github.com/containous/traefik/commit/131f581f77f2cab53079a624585cd19a88fab0ac
- Glog
  - https://github.com/golang/glog/commits/master
  - https://github.com/golang/glog/pull/13
  - https://github.com/golang/glog/commit/44145f04b68cf362d9c4df2182967c2275eaefed  
  - https://github.com/golang/glog/commit/fca8c8854093a154ff1eb580aae10276ad6b1b5f
- k8s
  - https://github.com/kubernetes/client-go/blob/e121606b0d09b2e1c467183ee46217fa85a6b672/Godeps/Godeps.json
  - https://github.com/kubernetes/client-go/blob/master/Godeps/Godeps.json

----

fix: Vulcand dependency version: vulcand/predicate

`vulcand/predicate` is used by:
- `github.com/vulcand/oxy` (no dependencies manager)
- `github.com/vulcand/route` (used by `github.com/vulcand/vulcand`)

`github.com/vulcand/vulcand` (Godeps) required an old version `cb0bff91a7ab7cf7571e661ff883fc997bc554a3`.

`19b9dde14240d94c804ae5736ad0e1de10bf8fe6` is the only commit before `cb0bff91a7ab7cf7571e661ff883fc997bc554a3`.

refs:
- https://github.com/vulcand/vulcand/blob/42492a3a85e294bdbdd1bcabb8c12769a81ea284/Godeps/Godeps.json
- https://github.com/vulcand/predicate/commits/master
- https://github.com/vulcand/predicate/commit/19b9dde14240d94c804ae5736ad0e1de10bf8fe6

----

fix: k8s dependency version: emicklei/go-restful

`emicklei/go-restful` is used by:
- `k8s.io/client-go`  (Godeps)

Refs:
- https://github.com/kubernetes/client-go/blob/e121606b0d09b2e1c467183ee46217fa85a6b672/Godeps/Godeps.json

-----

fix: Prometheus dependencies

Prometheus is related to `go-kit/kit`.
`go-kit/kit` doesn't have dependency manager.

We use `go-kit/kit` v0.3.0 (15 Nov 2016).

We must explicitly declare the Prometheus dependencies.
Prometheus doesn't have dependency manager.
Use the commit date to fixed all hash.

refs:
- go-kit
  - https://github.com/go-kit/kit/tree/v0.3.0 (15 Nov 2016)
- Prometheus
  - https://github.com/prometheus/client_golang/commits/master
  - https://github.com/prometheus/client_golang/commit/08fd2e12372a66e68e30523c7642e0cbc3e4fbde (Apr 1, 2017)
  - https://github.com/prometheus/common/commits/master
  - https://github.com/prometheus/common/commit/49fee292b27bfff7f354ee0f64e1bc4850462edf (Feb 20, 2017)
  - https://github.com/prometheus/client_model/commits/master
  - https://github.com/prometheus/client_model/commit/6f3806018612930941127f2a7c6c453ba2c527d2 (Feb 16, 2017, master, HEAD)
  - https://github.com/prometheus/procfs/commits/master
  - https://github.com/prometheus/procfs/commit/a1dba9ce8baed984a2495b658c82687f8157b98f (Feb 16, 2017)

### CODE REVIEW

**Comment by ldez** [comment]
ETCD problem:

Seems we don't use this file:
```
 D vendor/github.com/coreos/etcd/pkg/fileutil/fileutil.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/lock_plan9.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/lock_solaris.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/lock_unix.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/lock_windows.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/perallocate_unsupported.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/preallocate.go
 D vendor/github.com/coreos/etcd/pkg/fileutil/purge.go
 D vendor/github.com/coreos/etcd/version/version.go
```

**Comment by ldez** [comment]
Glide warn state:

```
[WARN]	Conflict: github.com/Sirupsen/logrus rev is currently 10f801ebc38b33738c9d17d50860f484a0988ff5, but github.com/vulcand/vulcand wants f7f79f729e0fbe2fcc061db48a9ba0263f588252
[WARN]	Conflict: github.com/vulcand/oxy rev is currently f88530866c561d24a6b5aac49f76d6351b788b9f, but github.com/vulcand/vulcand wants 8d49f51577f79f0ffd7607ec9fab42b300002851
[WARN]	Conflict: golang.org/x/net rev is currently 242b6b35177ec3909636b6cf6a47e8c2c6324b5d, but github.com/vulcand/vulcand wants 6460565bec1e8891e29ff478184c71b9e443ac36
[WARN]	Conflict: golang.org/x/sys rev is currently 8d1157a435470616f975ff9bb013bea8d0962067, but github.com/vulcand/vulcand wants eb2c74142fd19a79b3f237334c7384d5167b1b46
[WARN]	Conflict: github.com/gogo/protobuf rev is currently v0.3, but k8s.io/client-go wants e18d7aa8f8c624c915db340349aad4c49b10d173
[WARN]	Conflict: github.com/miekg/dns rev is currently 8060d9f51305bbe024b99679454e62f552cd0b0b, but github.com/mesosphere/mesos-dns wants d4ee3f8757f79c17405846965b8a620de7ca9073
[WARN]	Conflict: golang.org/x/oauth2 rev is currently 7fdf09982454086d5570c7db3e11f360194830ca, but k8s.io/client-go wants 3c3a985cb79f52a3190fbc056984415ca6763d01
[WARN]	Conflict: github.com/golang/protobuf rev is currently 2bba0603135d7d7f5cb73b2125beeda19c09f4ef, but k8s.io/client-go wants 8616e8ee5e20a1704615e6c8d7afcdac06087a67
[WARN]	Conflict: github.com/matttproud/golang_protobuf_extensions rev is currently c12348ce28de40eed0136aa2b644d0ee0650e56c, but github.com/coreos/etcd wants fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a
[WARN]	Conflict: github.com/prometheus/client_model rev is currently 6f3806018612930941127f2a7c6c453ba2c527d2, but github.com/coreos/etcd wants fa8ad6fec33561be4280a8f0514318c79d7f6cb6
[WARN]	Conflict: github.com/prometheus/common rev is currently 49fee292b27bfff7f354ee0f64e1bc4850462edf, but github.com/coreos/etcd wants ffe929a3f4c4faeaa10f2b9535c2b1be3ad15650
[WARN]	Conflict: github.com/prometheus/procfs rev is currently a1dba9ce8baed984a2495b658c82687f8157b98f, but github.com/coreos/etcd wants 454a56f35412459b5e684fd5ec0f9211b94f002a
[WARN]	Conflict: github.com/docker/distribution rev is currently v2.6.0, but k8s.io/client-go wants cd27f179f2c10c5d300e6d09025b538c475b0d51
[WARN]	Conflict: github.com/aws/aws-sdk-go rev is currently v1.6.18, but github.com/docker/distribution wants 90dec2183a5f5458ee79cbaf4b8e9ab910bc81a6
[WARN]	Conflict: cloud.google.com/go rev is currently v0.7.0, but k8s.io/client-go wants 3b1ae45394a234c385be014e9a488f2bb6eef821
[WARN]	Conflict: github.com/vulcand/predicate rev is currently 19b9dde14240d94c804ae5736ad0e1de10bf8fe6, but github.com/vulcand/vulcand wants cb0bff91a7ab7cf7571e661ff883fc997bc554a3
[WARN]	Conflict: google.golang.org/grpc rev is currently v1.2.0, but github.com/coreos/etcd wants f5ebd86be717593ab029545492c93ddf8914832b
```

**Comment by ldez** [comment]
Comments are automatically removed when you are doing `glide get`...

**Comment by emilevauge** [comment]
Indeed, good point (that's too bad 😢)

**Pull request merged**
