### PR TITLE
Custom 404 mapping

### PR DESCRIPTION
**Pull request by jangie**
### Custom 404 mapping

Addresses #884 , which is a pain point for us in helping our developers troubleshoot where in the stack they are experiencing issues.

### CODE REVIEW

**Comment by emilevauge** [comment]
@jangie We just opened a proposal https://github.com/containous/traefik/issues/1634 on this. We want to avoid serving static files from Traefik. WDYT?

**Comment by ldez** [comment]
Relate to  #1576

**Comment by jangie** [comment]
@emilevauge Sorry! Didn't realize. After reading the proposal, I guess I'm curious about what cases the errors apply to. In this particular case, this is intended to show up if there is no matched frontend mapping rule. For the 500-level errors as listed in the proposal, would those be coming from the mapped backend?

I guess as a general piece: I'm somewhat in favor of static files being served by Traefik. There is, for example, no guarantee that the error backend is able to serve traffic, and fallback in case of that backend being down or missing a particular file is potentially more complicated to deal with. That said, I am not married to that or to this PR at all and am totally happy to close this out in favor of that eventual PR.

**Comment by timoreimann** [comment]
Without having looked closer at this PR, I also get the feeling it serves a different purposes than what the proposal is trying to cover.

That said, I am not 100% sure whether exposing routing details via 404 responses is the right approach. Couldn't that potentially leak internal information to outsiders? Would the (access) logs possibly be a better place to store debugging information?

**Comment by jangie** [comment]
@timoreimann We're aiming to write our custom messaging such that it doesn't specifically list that out, but at least to denote what it is that is giving back the 404. As it stands, the generic 404 message is not particularly clear at that point.

As it stands, there wouldn't be any explicit routing information given back in the envisioned usage of this as this is specifically going to be giving back a static set of content which does not have any of the request's context.

**Comment by timoreimann** [comment]
@jangie to better understand your use case, could you give an example of what kind of information you'd be passing back to your users along the custom 404 page?

**Comment by jangie** [comment]
A static "Welcome to Traefik, we couldn't find what you were looking for" would be akin to what we're trying to do.

**Comment by timoreimann** [comment]
@jangie thanks for the example. It clarifies things for me and now it does look like #1634 would be able to solve your case too (albeit in a less static way).

**Comment by jangie** [comment]
👍  closing this out then, thanks! will be watching #1634 .

**Pull request closed without merging**
