### PR TITLE
Added getIPAddress helper for docker template

### PR DESCRIPTION
**Pull request by download13**
The docker template currently results in the IP address for a container being seen as every IP the container has (on every network it is a part of) being concatenated together.

For example a container that is a part of two networks and has the IPs `172.10.1.1` and `172.10.2.1` on those networks will have it's IP in the template filled in as `172.10.1.1172.10.2.1`.

This patch ensures that the user can select the network whose IP will be used with the `traefik.docket.network` label. If there is no label and more than one network, the first network will be used.

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @download13, great job :)
Could you add this new label in the documentation https://github.com/containous/traefik/blob/master/docs/toml.md ?
Thanks

**Comment by download13** [comment]
Sorry, I rebased without realizing it would do that. The documentation is there at least.

**Comment by emilevauge** [comment]
Thanks!
Could you merge correctly and squash your commits?
I cannot merge this one as is sorry ;)

**Comment by download13** [comment]
Okay, I think everything is working now. Some basic documentation for the label is in there now.

**Comment by emilevauge** [comment]
Thanks a lot @download13 :)
Once rebased, LGTM :)
/cc @vdemeester 
Fixes #229

**Comment by vdemeester** [comment]
LGTM :+1:

**Comment by scher200** [comment]
hi @download13,
your commit is great. Do you think it could be possible for traefik to automatically add itself to this particular traefik.docker.network
the project uses the /var/run/docker.sock:rw
with something like:
docker network connect **traefik.docker.network** traefik

**Pull request merged**
