### PR TITLE
Fix k8s memory leak

### LINKED ISSUE #377: potential memory leak in kubernetes ingress backend
@emilevauge and i have talked about this in slack as well, but it appears that when using the kubernetes ingress backend there is a slow memory leak.

a container configured to use kubernetes but with no traffic directed to it and no other configuration steadily consumes more memory over time until it finally runs out and crashes, often with this error:

```
time="2016-05-16T02:20:21Z" level=error msg="Error watching kubernetes events: failed to create watch: failed to do watch request: GET \"https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?watch&resourceVersion=2467988\": Get https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=2467988&watch=: dial tcp 172.17.0.1:443: connect: cannot assign requested address"
time="2016-05-16T02:20:21Z" level=fatal msg="Cannot connect to Kubernetes server failed to create watch: failed to do watch request: GET \"https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?watch&resourceVersion=2467988\": Get https://172.17.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=2467988&watch=: dial tcp 172.17.0.1:443: connect: cannot assign requested address"
```

which seems to imply that sockets may be leaking as well.

### PR DESCRIPTION
**Pull request by emilevauge**
This PR fixes memory leaks in Kubernetes backend.
/cc @nlf
Fixes #377

### CODE REVIEW

**Comment by emilevauge** [comment]
Waiting feedback from @nlf before merging

**Comment by nlf** [comment]
LGTM very very significant improvement :+1:

**Comment by emilevauge** [comment]
Hum, I need more time on this...

**Comment by errm** [comment]
It seems much better, but it still looks like memory usage is growing unbounded, albeit at a much slower rate...

**Comment by emilevauge** [comment]
I just pushed a new version for testing purpose on docker hub: `containous/traefik:k8s`

**Comment by errm** [comment]
Ok just deployed `containous/traefik:k8s` will let you know what it looks like ...

**Comment by nlf** [comment]
i've got the latest k8s tag deployed too and am monitoring memory growth, i'll report back later today

**Comment by errm** [comment]
The leak is still there, but much slower. I am seeing the memory usage go from 20MiB to 256MiB in 5 hours, after 256MiB I am killing the process.

It seems that memory is leaking from somewhere in k8s.client#WatchAll as I have a branch where I am watching endpoints rather than pods and replication controllers, and the memory leak is much slower again... as watched events fire far less often.

**Comment by emilevauge** [comment]
Hi @errm, I can't reproduce your leak on my computer :'( 
@nlf do you have the same behavior ?

**Comment by nlf** [comment]
i can't say for sure, our hosting provider had some issues so we had a bunch of services restart from that. if everything stays up ok today i'll report back later

**Comment by errm** [comment]
@emilevauge I am still seeing the issue, but I these changes are a big improvement so I think it would be good to merge them in.  For me the issue is solved when I am running these changes, plus the stuff I am working on to build the backend with endpoints. 

I will be able to open a PR with as soon as this is merged...

**Comment by emilevauge** [comment]
@errm OK ;) Let's merge this one then :)
You could also try to modify the parameter `providersThrottleDuration` in traefik, as you have a high rate of kubernetes events. By default, it is set to `2s`, maybe you could try with `500ms`, it could help.

**Comment by nlf** [comment]
I tend to agree, it's so significantly better than it was it's worth merging as is to keep things moving forward. For what it's worth, of the 4 instances I'm running it looks like only one of them is leaking at all, and it appears that garbage collection is fighting to keep it under control so the growth is pretty minimal

**Comment by vdemeester** [comment]
Sounds good to me (based on the comments).
LGTM 🐯

**Pull request merged**
