### PR TITLE
Add a make help target

### PR DESCRIPTION
**Pull request by vdemeester**
2016-04-07-163019_684x288_scrot

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by emilevauge** [comment]
Great! I also wanted to do that ;)
http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html

**Comment by emilevauge** [comment]
Needs a rebase :)

**Comment by vdemeester** [comment]
@emilevauge done :wink:

**Comment by emilevauge** [comment]
LGTM

**Pull request merged**
