### PR TITLE
Using more sensible consul blocking query to detect health check changes (only passing ones)

### PR DESCRIPTION
**Pull request by vholovko**
This is a possible solution for #1107 

Basically only the health check blocking query is used for consul catalog change detection. The rest is the same.

### CODE REVIEW

**Comment by errm** [comment]
Need to run gofmt otherwise lgtm

**Comment by emilevauge** [comment]
@vholovko I'm not sure to really understand your code.
`_, meta, err := health.State("passing", opts)` calls this API https://www.consul.io/docs/agent/http/health.html#health_state, and will then returns the checks in the `passing` state. This call is not a blocking query and you don't use the result in the following part (appart from `meta`). To me, you just get all the `passing` checks (which could be empty) before listing the services, am I wrong?

**Comment by vholovko** [comment]
@emilevauge Actually we are going the long polling (a blocking query) by specifying wait time parameter in the query options `QueryOptions{WaitTime: DefaultWatchWaitTime}` which is resolved to 15 seconds.
The wait time is the time when connection is open until time is out or consul return us a new index (in case the amount of passing services changes) in the `meta` return value. 
Then we are comparing the indices between each other (the previous with the returned one) and will repeat the long polling (the last returned index will be send together with other query options) in case it's the same or we will generate the fresh traefik consul-catalog configuration if the index was changed.

**Comment by emilevauge** [comment]
@vholovko My main concern is that I don't get why you call `_, meta, err := health.State("passing", opts)` as you don't match the result (assigned in `_`) with services using `ServiceID`.
`health.State` just list all `passing` health checks right? You don't match `passing` health checks with services, right? Then I don't get it :thinking:

**Comment by vholovko** [comment]
Hi, @emilevauge

I'm not using the actual data because I'm only interested in the `meta` index change (since it is **capable to react on health change** and this is the story all about).
I'm using `health.State` only **as a trigger** not as a data provider.
Even if I started to use the health data it lacks the information like `Service.Tags` which is essencial for building the traefik config.
The `data` itself will be fetched when calling to `catalog.Services` and on a later stage to `health.Service`.

Why to specify `passing` in the query? We don't want to listen changes on following health changes:

warning -> critical
critical -> warning

We are only interested in the next changes:

critical -> passing
warning -> passing
passing -> warning
passing -> critical

So only for these events we should regenerate the traefik config (it was concluded from the code where `health.Service` is called with passingOnly set to `true`)

**Comment by emilevauge** [comment]
@vholovko thanks for your explanation, I finally get it!
I think you should add this as a comment in the code, as this is not obvious to understand ;)
Could you add some unit tests in `consul_catalog_test.go`, rebase against v1.2 branch, and squash your commits? If you can do this today, we would love to get this in rc2 :)

**Comment by rokka-n** [comment]
Its solves a legit problem, can we haz it merged please.

**Comment by vholovko** [comment]
Closed branch because of inaccurate squash.
Sorry for the mess, #1241 is more clean.

**Pull request closed without merging**
