### PR TITLE
Option to disable expose of all docker containers

### PR DESCRIPTION
**Pull request by s7anley**
In case someone wants to register containers manually.

### CODE REVIEW

**Comment by s7anley** [comment]
There is small problem with default value when using configuration file. I have one solution in mind e.g. create constructor function for `GlobalConfiguration` and set `ExposedByDefault` to true. I think there will be more and more options which default value has to be changed when instantiating. What you think?

**Comment by s7anley** [comment]
@emilevauge I'm strangling with default value when configuration file is used. I didn't find the way how to configure viper. I tried `viper.SetDefault`, but this value is ignore once configuration file is loaded.  Any ideas?

**Comment by emilevauge** [comment]
@s7anley thanks for your contribution!
We are in the process of replacing viper/cobra by our own lib, it should be a lot easier to manage these use cases. I suggest we wait this refactor before merging your PR :)
WDYT?

**Comment by s7anley** [comment]
Sure, not a problem.

**Comment by bbinet** [comment]
+1, it would be great if it could be merged before 1.0 release.

**Comment by s7anley** [comment]
@emilevauge any news regarding own configuration lib?

**Comment by emilevauge** [comment]
The PR is here #403, will be merged soon :)

**Comment by emilevauge** [comment]
Hi @s7anley, the PR https://github.com/containous/traefik/pull/403 is merged ;)

**Comment by s7anley** [comment]
@emilevauge thanks for update, I will take a look during weekend.

**Comment by emilevauge** [comment]
Ping ?

**Comment by emilevauge** [comment]
Hi @s7anley , I'm planning to get this PR in the 1.1 releases. Do you think it's possible ?

**Comment by vdemeester** [comment]
Carrying here https://github.com/containous/traefik/pull/514

**Comment by s7anley** [comment]
Oh, I'm really sorry guys. Hopefully, next time I will do better work.

2016-07-11 23:02 GMT+02:00 Vincent Demeester <notifications@github.com>:

**Comment by vdemeester** [comment]
@s7anley don't worry about it, I'm just carrying it (and fixing conflicts), but it's still your work and your commit :wink:. You did a good job :+1:

**Pull request closed without merging**
