### PR TITLE
Second option for entrypoint syntax in compose file results in error

### PR DESCRIPTION
**Pull request by chersicm**
### What does this PR do?

Remove a misleading section from the docs: second option for entrypoint syntax in compose file results in error.

### Motivation

Traefik fails with the following error:
```
time="2018-08-20T08:36:06Z" level=info msg="Traefik version v1.6.5 built on 2018-07-10_03:54:03PM"
time="2018-08-20T08:36:06Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-08-20T08:36:06Z" level=info msg="Preparing server  &{Address::443 TLS:0xc420359680 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42047bb80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-08-20T08:36:06Z" level=error msg="Unable to add a certificate to the entryPoint \"\" : unable to generate TLS certificate : tls: failed to find any PEM data in key input"
time="2018-08-20T08:36:06Z" level=error msg="Error creating TLS config: No certificates found for TLS entrypoint "
time="2018-08-20T08:36:06Z" level=fatal msg="Error preparing server: No certificates found for TLS entrypoint "
```
### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
could you edit the de description to respect the template, thanks.

**Comment by chersicm** [comment]
Updated with respect to the template.

**Comment by chersicm** [comment]
I've just noticed that the error occurs when trying to use the second syntax with the command expressed as a list (kind of a mix between the two), so perhaps that could be a useful note.

**Comment by ldez** [comment]
The syntax works for me, I think you have another issue. I recommend you to go to our [Slack Workspace](https://slack.traefik.io) to speak about that.

**Comment by chersicm** [comment]
It works for me too. It's just the mix of the two syntaxes that does not work:

command:
- --entryPoints='Name:powpow Address::42 Compress:true'

**Pull request closed without merging**
