### PR TITLE
Added an option to skip URL cleaning.

### PR DESCRIPTION
**Pull request by sybrandy**
See https://github.com/gorilla/mux/issues/94

This was done as we have Marathon behind Traefik and it adds additional "/" characters to the URLs.  Without this option, you, at a minimum, lose the ability to restart apps.

### CODE REVIEW

**Comment by errm** [comment]
Re gorilla/mux#94
> The risk there is that it's a sharp edge that—if you don't carefully write your own path-cleaning logic—you could break your application in other ways.

Should we be doing just this, or should we provide our own slightly less zellous path cleaning...

Am I correct in thinking that all we need to do for Marathon to work properly is to not clean paths with adjacent slashes?

**Comment by sybrandy** [comment]
First, that's why I made this configurable.  Most of what we do behaves nicely with the URL cleaning on.  So far we've only found the one case, Marathon, that's given us any trouble.

As for should we, I don't know.  I could argue both ways.  On one hand, it would be nice to have a single place that can clean URLs so that our webapps don't have to deal with it.  On the other hand, since the proxy does not have any real knowledge of the apps behind it, it should just pass the requests straight through since the apps may be expecting non-standard behaviour.  I don't know which is more common, so I'm not sure what the better default is.

As for Marathon, based on what we've seen, yes, I believe that's the case.  However, I'm not sure if that's something we can have turned on in the general case and have it work in all cases.

**Comment by emilevauge** [comment]
Hi @sybrandy, thanks for your contribution.
I agree that we should provide an option to disable path cleaning.
But I have few comments:

- could you `go fmt` your code?
- could you add this new option in the flag parser `func (ep *EntryPoints) Set(value string) error` ?
- could you complete the documentation in `traefik.sample.toml` and `docs/toml.md` ?

Thanks :)

**Comment by sybrandy** [comment]
Apologies for the delay.  The initial work was done for my project, but I haven't had much time to get back to this as I've had to work on other tasks.  As soon as I can I'll make the updates.

**Comment by emilevauge** [comment]
Closing in favor of #688.

**Pull request closed without merging**
