### PR TITLE
Setting the Cookie Path explicitly to root

### LINKED ISSUE #1744: Ingresses for a sticky services with a single ingress path can get multiple cookies
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* deploy a web app on k8s with multiple pods (3 app pods in our case)
   * app serves many endpoints on multiple paths (i.e. https://app.domain.com/path1, /path2, etc.)
* create an k8s service that selects the pods and requests stickiness through traefik.backend.loadbalancer.sticky: "true"
* deploy traefic ingress controller pods via a k8s deployment (3 traefik pods in our case)
    * configure traefik to watch a single namespace ("sets" in our case)
* create a k8s ingress resource with a single host
   * path: /
   * kubernetes.io/ingress.class: traefik
* start hitting endpoint from a single client via a web browser

### What did you expect to see?

Since stickiness is configured, and since a single, global path was specified, all requests from a given client browser session should be directed to the same app pod.

### What did you see instead?

For some web clients, all requests go to the same app pod.
   * these client have a single traefik backend cookie
snip20170612_9

For some other web clients, requests for path path1 always to to pod A, request for path2 got to pod B, etc.
   * clients affected always have multiple traefik backend cookies, one per path
screen shot 2017-06-12 at 4 18 20 pm
   * as many as 4 cookies, each with a different path have been observed

### Output of `traefik version`
1.3.0

### What is your environment & configuration

traefik config
```yml
apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    [kubernetes]
    namespaces = ["sets"]
kind: ConfigMap
metadata:
  creationTimestamp: 2017-06-06T23:08:37Z
  labels:
    app: private-ingress
  name: private-ingress
  namespace: sets
  resourceVersion: "105250320"
  selfLink: /api/v1/namespaces/sets/configmaps/private-ingress
  uid: 12642da1-4b0d-11e7-a9df-0259bfeee5dc
```

app ingress resource
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: 2017-06-12T22:49:12Z
  generation: 2
  labels:
    app: jira
    env: archive
  name: jira-private-archive
  namespace: sets
  resourceVersion: "107822544"
  selfLink: /apis/extensions/v1beta1/namespaces/sets/ingresses/jira-private-archive
  uid: 5a4f53bf-4fc1-11e7-9ac4-02ba24f06372
spec:
  rules:
  - host: jiraarchive.nordstrom.net
    http:
      paths:
      - backend:
          serviceName: jira-test
          servicePort: 8080
        path: /
status:
  loadBalancer: {}
```

app svc
```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.backend.loadbalancer.sticky: "true"
  creationTimestamp: 2017-06-12T16:35:53Z
  labels:
    app: jira
    component: jira
    env: test
  name: jira-test
  namespace: sets
  resourceVersion: "107822074"
  selfLink: /api/v1/namespaces/sets/services/jira-test
  uid: 33b4d522-4f8d-11e7-ad5f-02587911dfec
spec:
  clusterIP: 25.0.143.41
  ports:
  - name: jira
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jira
    component: jira
    env: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by marcopaga**
Created the PR to get the changes from oxy to set the sticky session cookie to "/".

Fixes #1744

### CODE REVIEW

**Comment by marcopaga** [comment]
Releated to containous/traefik#1744

**Comment by timoreimann** [comment]
You have seemingly forgotten to update the glide hash in the lock file. That's why the CI is red.

**Comment by marcopaga** [comment]
Too bad. I changed the hash in the glide.lock and glide.yml. Not sure what went wrong.
I'm on vacation without a dev environment. I can check it when I'm back.

**Comment by ldez** [comment]
@marcopaga I have fixed the problem.

**Comment by marcopaga** [comment]
@ldez Thank you very much!

**Pull request merged**
