### PR TITLE
Fix k8s panic

### LINKED ISSUE #869: digest auth example is incorrect
When I follow the example from the documentation:
```
[entryPoints]
   [entryPoints.http]
   address = ":80"
   [entryPoints.http.auth.basic]
   users = ["test2:traefik:518845800f9e2bfb1f1f740ec24f074e"]
```

I get the error:
Error starting server: Error parsing Authenticator user: test2:traefik:518845800f9e2bfb1f1f740ec24f074e" 

based on the code, I tried to replace entryPoints.http.auth.basic by entryPoints.http.auth.digest.
With this it seems to works

(I forgot to mention I am using the docker image traefik:v1.1.0)

### LINKED ISSUE #877: 1.1.0 kubernetes panic: send on closed channel
This has happened twice (2) in the last hour since i upgraded to 1.1.0 in our development cluster. 

The last log message before the panic was:
```
time="2016-11-22T14:43:00Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://127.0.0.1:9443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 639.617334ms" 
```

```
panic: send on closed channel

goroutine 4420 [running]:
panic(0xd292c0, 0xc4203f96a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1.1(0xc42050e900, 0xc420141260, 0xc420221080, 0x26, 0xc420141200)
	/go/src/github.com/containous/traefik/provider/k8s/client.go:280 +0x33f
created by github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1
	/go/src/github.com/containous/traefik/provider/k8s/client.go:286 +0xbf
```

I run traefik like this:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      containers:
      - image: traefik:v1.1.0
        name: traefik-ingress-lb
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8081
        args:
        - --retry.attempts=8
        - --retry
        - --web
        - --web.address=:8081
        - --kubernetes
        - --kubernetes.endpoint=https://127.0.0.1:9443
```

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #877 
Fixes #869 
**DO NOT merge before validation made in https://github.com/containous/traefik/issues/877**

### CODE REVIEW

**Comment by jonaz** [comment]
Should'nt this be enought? Whats the motives to use "third" party libs in stead of just channels and goroutines directly? 
```
@@ -270,9 +271,9 @@ func (c *clientImpl) watch(url string, labelSelector string, stopCh <-chan bool)
 
        go func() {
                defer close(watchCh)
-               defer close(errCh)
                go func() {
                        defer res.Body.Close()
+                       defer close(errCh)
                        for {
                                var eventList interface{}
                                if err := json.NewDecoder(res.Body).Decode(&eventList); err != nil {

```

**Comment by emilevauge** [comment]
@jonaz I don't know what you are calling "third party libs" here.
`safe.Go` is taken from Traefik directly. The goal is to avoid Traefik to panic and stop. So it is not useless ;)

**Comment by jonaz** [comment]
I mean some external package thats not part of go. Just thought the fix was a bit to complicated for what was needed. But i'll admit i did not thoroughly read the safe packge from traefik.

**Comment by jonaz** [comment]
Is'nt there a possible goroutine leak aswell?
```
	safe.Go(func() {
		EndCh := make(chan bool, 1)
		defer close(watchCh)
		defer close(errCh)
		defer close(EndCh)
		safe.Go(func() {
			defer res.Body.Close()
			defer func() {
				EndCh <- true
			}()
			for {
				var eventList interface{}
				if err := json.NewDecoder(res.Body).Decode(&eventList); err != nil {
					if !strings.Contains(err.Error(), "net/http: request canceled") {
						errCh <- fmt.Errorf("failed to decode watch event: GET %q : %v", url, err)
					}
					return
				}
				watchCh <- eventList
			}
		})
		<-stopCh **// Wont we listen here forever in case of error in Decode?** 
		safe.Go(func() {
			cancel() // cancel watch request
		})
		<-EndCh
	})
```

provider/kubernetes.go seems to check for error channel and send stop to it. But i dont think a client should be dependant on the usage not to leak goroutines. 

DISCLAMER: This maybe should belong in another issue on github.

**Comment by emilevauge** [comment]
@jonaz goroutine leak has been tested quite intensively during [the RC phase](https://github.com/containous/traefik/issues/844).
Besides, we are in the process of [moving to the official k8s client](https://github.com/containous/traefik/pull/836) in the next release.

**Comment by jonaz** [comment]
Good. Official client should sufficient! :D

**Pull request merged**
