### PR TITLE
Add shell script linting with shellcheck for better portability

### PR DESCRIPTION
**Pull request by dduportal**
### What does this PR do?

This PR introduce a new step for the targets `make validate` and `make validate-file`,
to perform a shellcheck lint on the shell scripts.

If the binary shellcheck is not found on the machine performing the `make validate`, then nothing is done, and no error is thrown to avoid forcing end user to install tons of tools.

Please note that `shellcheck` cannot be easily integrated into the Docker container `go:1.xx-alpine` as there is no Alpine package (yet.. https://bugs.alpinelinux.org/issues/7105). There are 2 Docker images (https://hub.docker.com/r/koalaman/shellcheck-alpine/ and https://hub.docker.com/r/koalaman/shellcheck) but it would be too complex to integrate in the workflow.

### Motivation

The project is using a lot of shell scripts. These scripts are expected to be as lean and portable as possible. But shell being a not-so-easy language, `shellcheck` provides sane linting and gives a lot of example about how to correct code.

Initial motivation comes from #4844 .

### More

- ~[ ] Added/updated tests~
- ~[ ] Added/updated documentation~

### Additional Notes

Here is a fun GIF about shell because why not?

shell

### CODE REVIEW

**Comment by dduportal** [comment]
It looks like that there is an integration test error, which I can reproduce on the `v2.0` branch (but weirdly, it worked on the CI):

```shell
*************-
INFO[0088] DockerSuite.TestDockerContainersWithTCPLabels: Traefik logs:  
INFO[0088] time="2019-05-08T15:05:08Z" level=info msg="Using TOML configuration file /go/src/github.com/containous/traefik/integration/fixtures/docker/simple.toml239658419"
time="2019-05-08T15:05:08Z" level=info msg="Traefik version 681892148e54589a8aceece54e83ff7590be004e built on 2019-05-08_03:02:09PM"
time="2019-05-08T15:05:08Z" level=debug msg="Static configuration loaded {\"Global\":{\"Debug\":false,\"CheckNewVersion\":false,\"SendAnonymousUsage\":false},\"ServersTransport\":{\"InsecureSkipVerify\":false,\"RootCAs\":null,\"MaxIdleConnsPerHost\":200,\"ForwardingTimeouts\":null},\"EntryPoints\":{\"traefik\":{\"Address\":\":8080\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}},\"web\":{\"Address\":\":8000\",\"Transport\":{\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"RespondingTimeouts\":{\"ReadTimeout\":0,\"WriteTimeout\":0,\"IdleTimeout\":180000000000}},\"ProxyProtocol\":null,\"ForwardedHeaders\":{\"Insecure\":false,\"TrustedIPs\":null}}},\"Providers\":{\"ProvidersThrottleDuration\":0,\"Docker\":{\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}.docker.localhost`)\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15},\"File\":null,\"Marathon\":null,\"Kubernetes\":null,\"KubernetesCRD\":null,\"Rest\":null,\"Rancher\":null},\"API\":{\"EntryPoint\":\"traefik\",\"Dashboard\":true,\"Statistics\":null,\"Middlewares\":null},\"Metrics\":null,\"Ping\":null,\"Log\":{\"Level\":\"DEBUG\",\"format\":\"common\"},\"AccessLog\":null,\"Tracing\":null,\"HostResolver\":null,\"ACME\":null}"
time="2019-05-08T15:05:08Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-05-08T15:05:08Z" level=debug msg="No default certificate, generate one"
time="2019-05-08T15:05:08Z" level=debug msg="Start TCP Server" entryPointName=web
time="2019-05-08T15:05:08Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2019-05-08T15:05:08Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-05-08T15:05:08Z" level=info msg="Starting provider *docker.Provider {\"Constraints\":null,\"Watch\":true,\"Endpoint\":\"unix:///var/run/docker.sock\",\"DefaultRule\":\"Host(`{{ normalize .Name }}.docker.localhost`)\",\"TLS\":null,\"ExposedByDefault\":true,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
time="2019-05-08T15:05:08Z" level=debug msg="Provider connection established with docker 19.03.0-beta3 (API 1.40)" providerName=docker
time="2019-05-08T15:05:08Z" level=error msg="port is missing" providerName=docker container=/recursing_wing-d72cfadef2ea5a18be8764ad14a800ccf6d1a0508da1f81dcbe00026fd0f10e9
time="2019-05-08T15:05:08Z" level=debug msg="Configuration received from provider docker: {\"HTTP\":{},\"TCP\":{\"routers\":{\"Super\":{\"entryPoints\":null,\"service\":\"Super\",\"rule\":\"HostSNI(`my.super.host`)\",\"tls\":{\"passthrough\":false}}},\"services\":{\"Super\":{\"loadbalancer\":{\"servers\":[{\"address\":\"172.17.0.3:8080\",\"weight\":1}],\"method\":\"wrr\"}}}},\"TLSOptions\":null,\"TLSStores\":null}" providerName=docker
time="2019-05-08T15:05:08Z" level=debug msg="No default certificate, generate one" 

----------------------------------------------------------------------
FAIL: docker_test.go:147: DockerSuite.TestDockerContainersWithTCPLabels

docker_test.go:176:
    c.Assert(err, checker.IsNil)
... value *errors.errorString = &errors.errorString{s:"try operation failed: could not find 'HostSNI(`my.super.host`)' in body '{}'"} ("try operation failed: could not find 'HostSNI(`my.super.host`)' in body '{}'")


----------------------------------------------------------------------
```

**Comment by ldez** [comment]
the real issue:
```
Testing from host…
fake_dns_server.go:9:2: cannot find package "github.com/miekg/dns" in any of:
	/usr/local/golang/1.12/go/src/github.com/miekg/dns (from $GOROOT)
	/home/runner/workspace/src/github.com/miekg/dns (from $GOPATH)
make: *** [test-integration] Error 1
```

It's a regression due to this PR.

**Comment by dduportal** [comment]
@ldez I need help on this topic. When I work on the branch `v2.0`, from an cleaned `dist` dir, I also got the Integration test error (ref. https://gist.github.com/dduportal/1d38356de853b2af276cde317af87792).

However I don't have the issue you are mentioning about the `fake_dns`: this is introduced by my PR (has I don't have it on the `v2.0` branch, I'm focusing on this part.

**Comment by ldez** [comment]
Your computer is slow, then you need to use the timeout multiplier (set the env var `CI` to `true`)

**Comment by dduportal** [comment]
@ldez thanks, Did not know about this one. Now I'm having the same error as the (most recent) CI for the integration test. (My Docker VM having 16 Gb and 8 CPUs, with 128 Gb SSD, I dont really understand what we is considered as "slow", but heh, it did the trick. What could be the culprit here?).

Still I can't reproduce the `fake_dns` error, which appears on the CI, but not on my local `CI=10 make test-integration`. So I d'ont really understand what did I break?

My current understanding is that this library is on the imports of `integration/fake_dns.go`, but the library in itself is found on the `vendor`. I guess the integration tests are run on a place which is missing the `vendors` directory somehow?

**Comment by ldez** [comment]
`CI` is not a number it's a boolean.

**Comment by dduportal** [comment]
Mmmh looks like it should still work: https://github.com/containous/traefik/blob/v2.0/integration/try/try.go#L168 right?

However as I can't reproduce the issue, I tried (and is trying) the following hypothesis:

- Removed any changes done to the `.semaphoreci/*` scripts: error still there
- Debugging the `test-integration` script to see what has changed on the command line executed

If you have any clue or idea?

**Comment by ldez** [comment]
`.semaphoreci/*` scripts are not used.

The issue is:
```bash
cd "${SCRIPT_DIR}"/../integration
```

**Comment by dduportal** [comment]
Ok, after our 1:1 exchange, I understand now.
The issue is related to the `SCRIPT_DIR` variable, which is using the full resolved path. But in Semaphore, the workspace is using symlinks.
So using the full resolved path results to an absolute path outside the GOPATH, even if the relative path embed the vendor.

Rollbacked the changes, and removed the `SCRIPT_DIR` variable did the trick.

**Pull request merged**
