### PR TITLE
feat(consul-catalog-provider): + setting unique backend name + backendd redirecting to internal container ip

### PR DESCRIPTION
**Pull request by samber**
see https://github.com/containous/traefik/issues/275

**Caution**: Breaking (see issue)

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks @samber !
Could you rebase to the master?
Other than that, LGTM :)

**Comment by samber** [comment]
Done ;-)

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by keis** [comment]
Trying this out after fixing the service address I'm registering but I'm getting issues from some of the static configured services we have in consul. Configured by json files in the consul directory where we don't set the ip because it's optional and would be discovered at runtime. The health route returns the service address as empty string but querying these through the consul dns returns the node ip.

I think the node address should be used as a fallback to match what consul itself does. Oh, and now it even fails to do anything because a name collision in backend names when the service address is empty.

**Comment by samber** [comment]
There is no unique id in Consul, maybe shall we set a random id or put an index at the end of the service name ? (ex: web-80-1, api-443-2, nginx-80-3...)

IMO, Traefik shouldn't retrieve these services without valid ip. In your json file, can you declare the service as unhealthy ?

**Comment by keis** [comment]
I'm not sure it's really invalid though because according to documentation the field is optional https://www.consul.io/docs/agent/services.html

> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided. The port field can be used as well to make a service-oriented architecture simpler to configure; this way, the address and port of a service can be discovered.

**Comment by emilevauge** [comment]
There is an issue with backend names: #309

**Comment by samber** [comment]
Mmmh, ok let's do that.

I don't know your needs, but i think the best practice in that case would be to register your service in consul with a Status to warning or critical: https://www.consul.io/docs/agent/http/catalog.html#catalog_register

**Comment by keis** [comment]
Sorry. Let me try to explain my scenario a bit better. It's not the case of unhealthy service at all.

We have some services that are deployed as plain old rpm and runs directly on the host without any container or network isolation. We register these into consul with static json configurations we don't specify the service address because we are perfectly fine using the same as the agent running on the same host.

e.g 

/etc/consul/services.json
```
{
  "services": [
    {
      "name": "marathon",
      "tags": [
        "marathon",
        "scheduler"
      ],
      "port": 8080,
      "checks": [
        {
          "script": "curl http://localhost:8080/ui/#/apps >/dev/null 2>&1",
          "interval": "15s"
        }
      ]
    }
  ]
}
```

**Comment by samber** [comment]
Ok, thanks @keis 
I see the use case ;-)

**Pull request merged**
