### PR TITLE
Conditionally use IPs in X-Forwarded-For for whitelisting; Bypass Authentication for whitelisted IPs.

### LINKED ISSUE #2260: Make the IP "whitelisting" more flexible
### Feature: Increase the flexibility of the whitelisting

The current whitelisting acts as a strict gate to incoming traffic. The authentication is also used as a strict gate. To gain access you have to meet *both* criteria and there is no mechanism to support meeting *either*.

Whilst it may be too late to change this naming now it would appear to the current functionality is more of a `greylist` than a `whitelist` since the requests get challenged again.

The feature behaviour would be have two groups of access lists, one that does indeed whitelist the traffic and hence allow it straight through, and a second which allows the traffic through to the next level of checking.

For the simple case of no auth the two lists would be essentially the same. And if no lists are set the auth would continue to be the decider.

There is no obvious need for the `blacklist` variant since this can be better achieved using a normal firewall.

### What did you do?

Using the docker image `traefik:1.4` enable both authentication and whitelisting for entrypoints:

```toml
[entryPoints]
    [entryPoints.http]
    address = ":80"
    whiteListSourceRange = [ "x.x.x.x" ]

    [entryPoints.http.auth.basic]
    usersFile = "/etc/htpasswd"
```

### What did you expect to see?

Requests that failed the IP address check would trigger the basic authentication instead.

### What did you see instead?

* Requests that failed the IP address check where blocked immediately.
* Requests that met the IP address check had to meet the basic authentication criteria

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0-rc5
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-10_02:04:46PM
OS/Arch:      linux/amd64
```

### Additional notes

There is a secondary part to this which is that when you are using the docker container the incoming IP address may be that of the docker host, not the original requesting host. This is certainly the case if you are working with a swarm because then the traefik container must be on an internal network. Ideally the checks would be against the originating IP address.

### PR DESCRIPTION
**Pull request by nemosupremo**
### What does this PR do?

This PR provides the functionality for Traefik to whitelist based on the `X-Forwarded-For` header optionally. This mirrors functionality in other reverse proxies, like [nginx](http://nginx.org/en/docs/http/ngx_http_realip_module.html) with the `set_real_ip` directive. It adds a new configuration option `whitelistTrustProxy` that accepts a list of CIDRs or IPs. If a request comes in that matches the IP of `whitelistTrustProxy`, traefik will whitelist based on the values in `X-Forwarded-For`. If there are multiple IPs in `X-Forwarded-For` (comma separated), it will use the last IP, as that is the only IP that can considered trustworthy by the [defacto standard](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html). If the remote IP is the second to last (or greater) IP, you can enter those IPs in `whitelistTrustProxy`, and Traefik will skip those IPs. For example with a configuration:

```toml
whitelistTrustProxy = ["trusted-ip1", "trusted-ip2"]
```

A request like so:

```
X-Forwarded-For: malicious-ip, client-ip, trusted-ip3, trusted-ip2, trusted-ip1
```

will return `trusted-ip3`. You can add the CIDR for the trusted-ips to get the `client-ip`. This functionality is needed for instances behind Google LB or CloudFlare.

This PR also fixes #2260, by extending this functionality to the `Auth` component. With the following config, a request from 172.17.0.1 will go through unchallenged, while any other request from any other IP will be challenged.
```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth]
    whitelistSourceRange = ["172.17.0.1"]
    whitelistTrustProxy = ["127.0.0.1/8"]
    [entryPoints.http.auth.basic]
    users = ["test:traefik:a2688e031edb4be6a3797f3882655c05 ", "test2:traefik:518845800f9e2bfb1f1f740ec24f074e"]
    usersFile = "/path/to/.htdigest"
```

This syntax is backwards compatible with Traefik deployments today (users won't suddenly see their authenticated endpoints bypassed by whitelisted IPs).

This PR provides a similar solution to the one outlined in #2235, but is stricter on the `X-Forwarded-For` policy.

### Motivation

We are using Traefik, behind Amazon ELB, to route requests from the outside world and inside our cluster to various microservices, for example a docker registry.  From inside our network, we wanted to be able use commands like `docker pull example.com/web` without a `docker login`, but also have tools like CircleCI also push images to our registry from the outside with authentication. This use case created the two problems we needed solved:

1. For an IP based authentication whitelist (so instances on our cluster could communicate unchallenged, but 3rd party services would be challenged).
2. A  trust `X-Forwarded-For` proxy so that requests that came into ELB would have their "real" ip exposed to Traefik.

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

PR #2235 also did some work on forwarding this information to the Kubernetes frontend. Unfortunately I haven't used Kubernetes and I'm unsure if this option needs to be forwarded to the Kubernetes backend. If that is something that needs to be included, if someone can explain to me how that works I'd be glad to include it (or it can be included in another PR).

### CODE REVIEW

**Comment by beenanner** [comment]
@nemosupremo I was able to get a whitelist working today with nginx in front of traefik by using the following configs. I also tested injecting a x-forwarded-for of 8.8.8.8 to verify the setup worked with malicious ips.

Nginx configs used

```
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 130.211.0.0/22;
set_real_ip_from 35.227.230.198/32;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

server {
    listen 80;
    listen 8080;
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;

    include /var/www-allow/whitelist.conf;

    proxy_set_header Host            $host;
    proxy_set_header X-Forwarded-For '$http_x_forwarded_for, $realip_remote_addr';
    proxy_set_header X-Real-IP $remote_addr;

    location / {
        if ($scheme = http) {
            proxy_pass http://traefik;
        }
        if ($scheme = https) {
            proxy_pass https://traefik;
        }
    }
    location ~ ^/(dashboard|api).*/ {
            proxy_pass http://traefik:8080;
    }
}
```

results in the following 

```
Hostname: f3a624b14a6d
IP: 127.0.0.1
IP: 10.0.0.2
IP: 10.0.0.3
IP: 172.18.0.3
GET / HTTP/1.1
Host: whoami.test.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Pragma: no-cache
Upgrade-Insecure-Requests: 1
Via: 1.1 google
X-Cloud-Trace-Context: fcfaabeb8736495d6b0de68b3d394405/17312253612327182169
X-Forwarded-For: 8.8.8.8, 64.30.233.86, 35.227.230.198, 130.211.2.75, 10.0.0.9
X-Forwarded-Host: whoami.test.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 4191ca3f8689
X-Real-Ip: 64.30.233.86
```


Here are the things that matter for the GCP LB
**
set_real_ip_from 130.211.0.0/22; <-- proxy LB IPs
set_real_ip_from 35.227.230.198/32; <-- real LB IP
real_ip_header X-Forwarded-For;
real_ip_recursive on;**

**proxy_set_header X-Forwarded-For '$http_x_forwarded_for, $realip_remote_addr';
proxy_set_header X-Real-IP $remote_addr;**

**Comment by nemosupremo** [comment]
Ok, I've built my feature branch and pushed it as a docker image to [nemothekid/traefik](https://hub.docker.com/r/nemothekid/traefik/).

According to your nginx config, the following traefik config should work:
```toml
[entryPoints]
  [entryPoints.http]
  address = ":80"
  whitelistSourceRange = ["127.0.0.1"]
  whitelistTrustProxy = ["35.227.230.198", "130.211.0.0/22",  "10.0.0.0/8"]
```

I'm also pretty sure in GCP, `10.0.0.0/8` is your Google private network range (or the IPs of your hosts) so for anyone reading this, you would likely need that as well even if you weren't using docker. I was also confused about the 3rd IP (which is the real LB IP), thanks for clearing that up.

**Comment by beenanner** [comment]
@nemosupremo is correct you will need the 10.0.0.0/8 or whatever your private CIDR block is regardless of running docker or standalone.

@nemosupremo sweet thanks for throwing this together! I'll give your image a go and report back.

**Comment by beenanner** [comment]
Looks like this is working! The only issue I see now is the X-Real-IP is still the last in the list.

```
Hostname: e3c37638a4e1
IP: 127.0.0.1
IP: 10.0.0.2
IP: 10.0.0.3
IP: 172.18.0.3
GET / HTTP/1.1
Host: whoami.acme.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Via: 1.1 google
X-Cloud-Trace-Context: 6a3b51bb7bf9e86f0127fb318c3df4fc/7369758590415622740
X-Forwarded-For: 170.20.11.31, 35.227.230.198, 130.211.2.173
X-Forwarded-Host: whoami.acme.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: d50554d3e2ed
X-Real-Ip: 130.211.2.173
```

I see this in traefik with debug on so it seems the source-IP it's checking against is correct. Just not sure where X-Real-IP is set.

```
time="2017-12-01T15:28:02Z" level=debug msg="source-IP 170.20.11.31 matched whitelist &{[%!s(*net.IP=&[0 0 0 0 0 0 0 0 0 0 255 255 35 227 230 198])] [%!s(*net.IPNet=&{[10 0 0 0] [255 0 0 0]}) %!s(*net.IPNet=&{[170 20 11 0] [255 255 255 128]}) %!s(*net.IPNet=&{[130 211 0 0] [255 255 252 0]})] %!s(bool=false)} - passing"
```

**Comment by nemosupremo** [comment]
I think the `X-Real-Ip` is coming from somewhere else (the LB?, I'm not sure). There's nothing in traefik's codebase I could fine about `X-Real-Ip`.

**Comment by beenanner** [comment]
Back tracking through to https://github.com/containous/traefik/issues/2311 looks like it may be part of the vendors that were added to 1.4.1.

https://github.com/containous/traefik/blob/44b82e62311232bff6887e5a78c73312c0236712/vendor/github.com/vulcand/oxy/forward/rewrite.go#L30

**Comment by beenanner** [comment]
Made @ldez could shed some light on this issue for us?

**Comment by nemosupremo** [comment]
Looks like its being set by the underlying http library [oxy](http://github.com/vulcand/oxy). Fixing the `X-Real-IP` header would mean submitting a PR to that repo, and then integrating an option in traefik to passdown all the way to oxy. 

That would be a separate issue - I'm really only concerned about whitelisting.

**Comment by beenanner** [comment]
@nemosupremo totally agreed as this indeeds solves the original issue of the whitelisting. The [oxy](https://github.com/vulcand/oxy) fix would be another correction that could be integrated later in a separate ticket in the event that downstream apps need to use X-Real-IP for logging or other things.

**Comment by emilevauge** [comment]
Hi @nemosupremo, thanks a lot for you contribution. We want to keep the authentication section as simple as possible and we think that your use case could be addressed differently. We advise you to either use a vpn, either use the [authentication forward mechanism](http://docs.traefik.io/configuration/entrypoints/#forward-authentication) we introduced recently.
Thanks @nemosupremo

**Comment by nemosupremo** [comment]
@emilevauge 

I'm revisiting this as I've currently deployed a fork of traefik with the features I needed and I want to figure out how I can get back to mainline. I'm going to contribute back the mesos changes (#2617) so they fit the new model, but this feature I'm a but puzzled as to how I would get it with authentication forwarding. Authentication forwarding seems to only work at the entrypoint level, whereas I need authentication/ip checks at the frontend level. 

Maybe it would help to explain my setup. We use Traefik as a frontend reverse proxy for all our http traffic. Some of our frontends are public (reachable by the internet), private (only reachable from a specific IP range) and authenticated (reachable by the internet with credentials OR reachable from a specific IP range). For example, we deploy Apache Spark on our cluster and we use Traefik to route to the Spark API, so we have machines in our infrastructure that will communicate with Traefik over the private secured network without authentication, but we need to also expose it publicly so that CircleCI can also push updates to the Spark frameworks working in our cluster. See how we don't want the public to run code on our machines via Spark, we use http authentication to secure that endpoint between CircleCI and Spark.

Using a VPN here is a non-starter - CircleCI and some of the other third party integrations we work with don't allow us to install VPNs on their machines. 

I looked at authentication forwarding, but it since we use Traefik for all our traffic, the authentication forwarding service build would also have to build a parallel configuration of Traefik's entire backend to make decisions on whether to allow authorization or not. Since we use container tags to register with traefik, the authentication forwarding mechanism would also have to contain logic for communicating with our cluster and parsing the traefik rules to make decisions on authentication. Authentication forwarding doesn't seem very practical. If authentication forwarding works on a frontend level, it would reduce the amount of code we would have to deploy, but still doesn't seem very attractive as it increases our security complexity.

Maybe you have a better solution for my use case that's more idiomatic? Essentially I want stricter access to a frontend based on source IP address.

**Pull request closed without merging**
