### PR TITLE
Replace PathPrefixStrip by PathPrefix in k8s

### LINKED ISSUE #337: Kubernetes PathPrefixStrip
The kubernetes provider create the path rules with PathPrefixStrip so the service fail 

example : 
``` 
Route	               Rule
/                      PathPrefixStrip:/
grafana.domain.tdl	   Host:grafana.domain.tdl
```

browser http://grafana.domain.tdl/public/css/grafana.dark.min.a95b3754.css -> to the service http://grafana.domain.tdlpublic/css/grafana.dark.min.a95b3754.css

I think we need to put Path for this usage

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #337 

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :D

**Comment by AlmogBaku** [comment]
@vdemeester Why?? this broke my whole app!
When introducing breaking code, i expect some compatibility behaviour 😠

**Comment by AlmogBaku** [comment]
btw, it can be solved by annotation imo

**Comment by emilevauge** [comment]
Sorry, there was a discussion on that point, we went to stay compliant with other ingress implementations.

**Pull request merged**
