### PR TITLE
Updates for jaeger tracing client.

### PR DESCRIPTION
**Pull request by tcolgate**
This adds some extra options:

- Allow generating 128-bit spans
- Allow propagating via b3 headers (in future, w3c will be an option here)

Also the new client library has no direct dependency on thrift (still needed for
zipkin).

These changes make it easier to interoperate with OpenCensus and OpenZipkin.

### CODE REVIEW

**Comment by tcolgate** [comment]
@mmatur added docs.

**Comment by tcolgate** [comment]
@mmatur It's not obvious to me which tests are failing :/ Lots of stuff about docker daemons and some uuids having changed.

**Comment by tcolgate** [comment]
Sorry, clicked a wrong button, repushing the release branch based version

**Comment by tcolgate** [comment]
Actually, sorry, do you want this based off of 1.7, or master? I meant to PR to the release branch.

**Comment by mmatur** [comment]
Np @tcolgate, on master branch it's perfect!

**Comment by tcolgate** [comment]
@mmatur rebased on master. Thanks.

**Comment by juanpabloaj** [comment]
Hi, this feature is available? and how could I configure it?

```
propagation = "jaeger"
```

https://github.com/containous/traefik/commit/6f6ebb80252dca3eed301d90dc3ee7fde86bd967#diff-75790e13e08a6df020d2ae463a4973f5R65

Because I don't find it in the documentation

https://docs.traefik.io/configuration/tracing/

thanks

**Pull request merged**
