### PR TITLE
forwardAuth.addHeadersToResponse

### LINKED ISSUE #3660: Forward authentication response headers
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be useful to allow headers returned from the forward authentication HTTP endpoint to be added to the final HTTP response. This would allow scenarios where the forward authentication endpoint can refresh authentication credentials and add the new credentials as a header/cookie.

This can be accomplished with a new configuration for http forward auth of "addHeadersToResponse" or similar.

Example:
```
addHeadersToResponse = ["Set-Cookie"]
```
This would result in any cookies added from HTTP forward auth response to be returned with the final response to the requesting client.

End-to-End example.
1. Traefik receives request to entrypoint with forward auth.
2. Traefik forward request to auth HTTP URI
3. JWT is used as a cookie for authentication. Forward auth server validates JWT, but expiration of JWT is soon.
4. Forward auth server requests new JWT for user and uses "Set-Cookie" header to overwrite previous JWT. Returns 20* response telling Traefik to continue routing.
5. Request is routed to correct frontend/backend and response obtained.
6. Forward auth middleware adds "Set-Cookie" header to outgoing response with new JWT.
7. New JWT cookie is used for subsequent requests.

### PR DESCRIPTION
**Pull request by iamolegga**
### What does this PR do?

closes #3660 

### Motivation

described in #3660 

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

Before reviewing this please read [this comment in related issue](https://github.com/containous/traefik/issues/3660#issuecomment-636144753) for understanding desired behaviour.

This PR **CAN** be merged, it does pass headers from `forwardAuth` service to response, but if *backend* has the same header, it overwrites values of the first one (`Set-Cookies` headers will be set from both services if have different `name`s, if both responses have same `Set-Cookie`'s `name` value from **backend** will be set).

Desired behaviour from my point of view is when values of headers from both services will be concatenated (through `Add`). So my question is to someone from the core team: what is the best way to deal with it? Or we can merge it now as it is, but implementing desired behaviour in next iteration will be breaking change

Thanks 🙂

### CODE REVIEW

**Comment by iamolegga** [comment]
Looks like tests not related to current changes have failed

**Comment by SantoDE** [comment]
Hey hey,

thanks for your work on that!

We're currently trying to figure out an answer for your question and I think, adding the `Add` functionality would be great  as its a non destructive approach and would probably help us to avoid strange behavior.

Do you have the time to contribute that as well?

**Comment by iamolegga** [comment]
Hi @SantoDE thanks for your response!

> Do you have the time to contribute that as well?

Sure, I would like to! Just need a bit of instructions on best way to implement it 🙂

**Comment by iamolegga** [comment]
Any updates @SantoDE @jbdoumenjou ? 🙂

**Comment by jbdoumenjou** [comment]
Hi @iamolegga,

Thanks for your contribution and sorry for the delay :)  

After analysis, as the RFC says :
    
```Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name.  (See Section 5.2 for how user agents handle this case.)```

To be compliant, the Set-Cookie header received from the authentication server response should only be applied after checking the Set-Cookie header value sent by the backend. The right way to do that would be to use the ModifyResponse mechanism from go. However, there is currently no way to keep track of the headers from the authentication server until the handling of the backend response.
 
 This is why, to accept this Pull Request, a technical way to apply the header a posteriori must be found.

Unless you have a better technical proposal, we will unfortunately close this PR.
What do you think ?

**Comment by iamolegga** [comment]
Hi @jbdoumenjou 

> Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name. (See Section 5.2 for how user agents handle this case.)

good catch, I didn't see that before, thanks 👍 

> To be compliant, the Set-Cookie header received from the authentication server response should only be applied after checking the Set-Cookie header value sent by the backend.

I think that passing set-cookie header from auth service is expected behaviour, if we set it, right?
But in case of same `name` that came from both auth and backend, it would be useful if backend could overwrite _default_ value from auth. Imagine some business logic on backend that could extend default business logic on auth service. Wdyt? 🙂

**Comment by jbdoumenjou** [comment]
As I said before, without a technical proposal compatible with the RFC, we are obliged to close this PR.
Feel free to discuss it on the corresponding issue.
Thanks anyway.

**Comment by iamolegga** [comment]
Why closing this PR? My proposition is totally compliant with RFC @jbdoumenjou

**Comment by iamolegga** [comment]
@jbdoumenjou why are you closing pr that is still in progress, what's the reason? Please read again my previous messages, I just wanted to know if described behaviour could be merged, then I could change this pr to _technical proposal compatible with the RFC_

**Comment by notsureifkevin** [comment]
Hi @iamolegga,

The team has discussed your proposal to determine if it is compliant with RFC and it appears that it is not. For example, if you copy the header `Set-Cookie: name=value` from the auth server response and the backend response also includes the header `Set-Cookie: name=value2`, both will set in the Traefik response which is not compliant as explained [here](https://tools.ietf.org/html/rfc6265#section-4.1.1).

> Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name.

As mentioned by @jbdoumenjou, to implement said functionality would require logic to handle the auth header being copied only if the backend response does not contain a `Set-Cookie` header with the same name. One approach would be to use the `ModifyResponse` mechanism from Go and there is currently no way to keep track of the headers from the auth server before the handling of the backend response.

As there is no technical proposal compatible with the RFC we were forced to close this PR. If you have ideas on how to implement this without breaking the RFC, we would welcome the discussion in the aforementioned issue that relates to this PR.

It is also possible to implement this functionality in custom middleware plugin where it isn't necessarily required to be compliant with the RFC specifications. If you'd like to learn more about how to build such a plugin, please reference the [plugindemo repository](https://github.com/containous/plugindemo).

If you have any additional questions or comments, feel free to respond here or in the aforementioned issue.

**Comment by iamolegga** [comment]
Hello @notsureifkevin 

Sorry, but I didn't get it, are we discussing now only `set-cookie` header behaviour, right? Because according to current tests, `set-cookie` set by _backend_ overwrite `set-cookie` with the same `name` set by _auth_. And if there is `set-cookie` with unique `name` from _auth_ or _backend_ it's set too. It is desired behaviour, isn't it?

My original question was about concatinating header values from both _auth_ and _backend_ (of course we must exclude `set-cookie` with same `name` here), but that could be extra feature, and simple overwriting that is implementing for now could be enough from my point of view.

**Comment by iamolegga** [comment]
@notsureifkevin please check [this lines](https://github.com/containous/traefik/pull/6893/files#diff-8e174f48100a7ee05608997d1e3a0bb0R47-R53)

**Comment by notsureifkevin** [comment]
@iamolegga according to the team, the response would include multiple `set-cookie` headers, both of which could include duplicate `name`'s.

**Comment by iamolegga** [comment]
@notsureifkevin um, but tests pass 😐

**Comment by ldez** [comment]
Hello,

If you swap the lines [L81 and L82](https://github.com/containous/traefik/pull/6893/files#diff-8e174f48100a7ee05608997d1e3a0bb0R81) in your integration test, you will see that it is not working:

```
forwardauth_test.go:62:
    c.Assert(err, checker.IsNil)
... value *fmt.wrapError = &fmt.wrapError{msg:"try operation failed: for header Set-Cookie got values [Bar=Auth Bar=Backend], wanted [Foo=Auth Bar=Backend]", err:(*errors.errorString)(0xc000359ca0)} ("try operation failed: for header Set-Cookie got values [Bar=Auth Bar=Backend], wanted [Foo=Auth Bar=Backend]")
```

This is related to the fact that in your [implementation](https://github.com/containous/traefik/pull/6893/files#diff-5b170f890426c7bcf124e6c2dd6570c9R159-R161), only the first value of `Set-Cookie` header is copying to the Traefik response.

If you replace your implementation by the following code, you will see that your test (without any modification) will not work:

```go
for _, headerName := range fa.addHeadersToResponse {
	for _, v := range forwardResponse.Header.Values(headerName) {
		rw.Header().Add(headerName, v)
	}
}
```

```
forwardauth_test.go:62:
    c.Assert(err, checker.IsNil)
... value *fmt.wrapError = &fmt.wrapError{msg:"try operation failed: for header Set-Cookie got values [Foo=Auth Bar=Auth Bar=Backend], wanted [Foo=Auth Bar=Backend]", err:(*errors.errorString)(0xc00052e910)} ("try operation failed: for header Set-Cookie got values [Foo=Auth Bar=Auth Bar=Backend], wanted [Foo=Auth Bar=Backend]")
```

So in case, it cannot be compliant with the RFC.

Thanks anyway.

**Pull request closed without merging**
