### PR TITLE
Add ratelimit headers.

### LINKED ISSUE #6113: Support RateLimit headers Internet Draft
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Return the ratelimit headers described in https://tools.ietf.org/html/draft-polli-ratelimit-headers-01

Eg.  for 10 requests per second, use

```
RateLimit-Limit: 10
RateLimit-Remaining: 5
RateLimit-Reset: 1
```

- The extended version can be returned too, which may better fit the ratelimit model from traefik

```
RateLimit-Limit: 10, 10;w=1
RateLimit-Remaining: 5
RateLimit-Reset: 1
```

### Notes

See PR: #6111 suggestions on how to improve/rewrite this PR are welcome

### PR DESCRIPTION
**Pull request by ioggstream**
### What does this PR do?

Stub implementation of https://tools.ietf.org/html/draft-polli-ratelimit-headers-03

### Motivation

Avoid clients receiving 429 abruptly

Fixes #6113

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Other implementors: [Kong](https://github.com/Kong/kong/pull/5335), [3scale](https://github.com/3scale/APIcast/pull/1166) , 
[Envoy](https://github.com/envoyproxy/envoy/pull/12410), Express Gateway [PR](https://github.com/nfriedly/express-rate-limit/pull/169).

### CODE REVIEW

**Comment by dtomcej** [comment]
Of note: The draft was updated and renewed in March 2020: https://tools.ietf.org/html/draft-polli-ratelimit-headers-02

**Comment by ioggstream** [comment]
> Of note: The draft was updated and renewed in March 2020: https://tools.ietf.org/html/draft-polli-ratelimit-headers-02

Yep! Linked 3scale and kong merge commits too. 

I need some help to finish this implementation @dtomcej  can you provide some guidance?

**Comment by ioggstream** [comment]
Hi @dtomcej , the ratelimit draft recently landed on Envoy too https://github.com/envoyproxy/envoy/pull/12410 Do you have any feedback for implementing it into traefik and reorganize this PR?

**Comment by notsureifkevin** [comment]
@ioggstream Thank you for your interest in Traefik and for the draft PR.

Given the RFC you've mentioned is still in draft state, the team here would prefer to wait until either the RFC is accepted, altenatively if there is a large consensus of Traefik users who would like this feature implemented before the acceptance of the RFC draft we would revisit the topic.

In the meantime, it is possible to create custom plugins using Traefik Pilot in the 2.3RC - you can [read more](https://github.com/containous/plugindemo) about how to build your own.

**Comment by notsureifkevin** [comment]
@ioggstream The team has decided to close this PR, in the future we'll consider the PR once the specification has been recommended or enough users have requested this functionality exist on the official rate limit middleware. Feel free to keep the issue open in the meantime and let us know when the RFC has come out of the draft state.

Thank you again for the contribution, and we're looking forward to the custom plugin demonstrating this capability.

**Comment by ioggstream** [comment]
@notsureifkevin thanks for your time :) I will take a look at the custom plugin features, but it will take some time.

In case you were going to add ratelimit headers Ratelimit middleware, I just suggest reading the I-D https://tools.ietf.org/html/draft-polli-ratelimit-headers-02 first :D 

Have a nice day, R.

**Pull request closed without merging**
