### PR TITLE
Support for multiple services per container in Rancher

### PR DESCRIPTION
**Pull request by jasl8r**
Add support for multiple services using Rancher labels in the form traefik.<service_name>.frontend.rule (and others).  This implements all the service level configuration supported in the Docker backend.

Resolves: #2052 

- [x] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
@jasl8r could you fix the CI (replace spaces by tab)?

And could add documentation ?

**Comment by ldez** [comment]
@jasl8r could you fix the CI (replace spaces by tab)?

**Comment by jasl8r** [comment]
Ugh, sorry, bad combination of editor detection and hiding whitespace changes...
Should be all set now, I squashed it all due to the whitespace stuff.

**Comment by jasl8r** [comment]
@ldez Not sure what to do about unit tests failing, they're in other components.  I've been running `TESTDIRS=./provider/rancher make test-unit`

**Comment by mmatur** [comment]
@jasl8r Unit tests are failing due to a flaky test @ldez is fixing this flaky test. When #2386 will be merge you can rebase and unit tests will be ok

**Comment by charandas** [comment]
@jasl8r the PR seems to be working well for me since last week. Could you please rebase so this could be merged and we could all benefit from the Github releases channel instead of having to fork / build?

**Comment by jasl8r** [comment]
This is going to be more than a simple rebase with the config overhaul.  I'll try to take a look in the next couple days.

**Comment by charandas** [comment]
@ldez I realize you have assigned this to yourself. I just wanted to express my appreciation for this feature, and re-request it be moved forward. I can take a look as well, I sort of get `go` :)

**Comment by ldez** [comment]
Due to some refactor I made this PR will be very hard to rebase but I'm working on a new approach on "services" methods, a PR coming soon 😃

**Comment by jjscarafia** [comment]
@jasl8r @ldez :+1: for this functionality. Can I help in any way? Thanks!

**Comment by ldez** [comment]
Closed in favor of #3073

**Pull request closed without merging**
