### PR TITLE
Added support for Vault

### PR DESCRIPTION
**Pull request by tbe**
### What does this PR do?

This PR adds support for Vault PKI

### Motivation

Vault PKI can be an excellent replacement for LE inside a private network infrastructure.

See also #2855

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

This PR is currently WIP

### CODE REVIEW

**Comment by tbe** [comment]
I used the ACME provider as a template for the vault provider. But right now, i didn't find the point, where a KV is used as storage backend in cluster mode. Any hints? ;)

**Comment by tbe** [comment]
As the current master branch and 2.0 don't have support for KV's, i will suspend to working on this PR until it is back. I have rebased the PR on the current master branch. @ldez is there information how one could help (re)implementing KV's?

**Comment by ldez** [comment]
Thank you :+1: 

Sorry for the late answer, we think that the KV support is out of the scope of this PR.

Then could rebase on the `v2.0` branch and add some tests?

**Comment by ldez** [comment]
@tbe any news ?

**Comment by ldez** [comment]
@tbe any news ?

**Comment by tbe** [comment]
Sorry for the long silence. I have two other high priority projects ongoing right now. I will not be able to continue the work in the next 3 weeks. After that i will finish the PR.

**Comment by ldez** [comment]
@tbe any news ?

**Comment by hongkongkiwi** [comment]
I'm really keen on this too! Can we merge this in?

**Comment by ndobbs** [comment]
This would be a great feature to have!

**Comment by ldez** [comment]
@tbe last call, any news ?

**Comment by ldez** [comment]
The PR was opened since one year now.

Despite several reminders, there has been no progress.
The code of Traefik has now changed a lot.

We will close this PR, but the subject is not abandoned, we leave open the issue attached to this PR.

Thank you for your understanding.

**Pull request closed without merging**
