### PR TITLE
Update TLS Ciphers for Go 1.8

### PR DESCRIPTION
**Pull request by kekoav**
See #1268 . This is an update to include all supported TLS ciphers in Go 1.8.

There are no cipher removals, only additions.

### CODE REVIEW

**Comment by kostyrev** [comment]
when will this be released?

**Comment by timoreimann** [comment]
The upcoming 1.3 release will have it.

**Comment by kostyrev** [comment]
That is the release cadence?

**Comment by timoreimann** [comment]
I think it's scheduled for some time at the end of this month. We're still in the process to finding a good cadence, hence we haven't published release schedules yet (but will do so eventually).

**Comment by kostyrev** [comment]
thanks for letting me know!

**Comment by jmagnusson** [comment]
I'm a bit worried that the list of ciphers fall behind what's actually available. Perhaps a more dynamic way of extracting what Go supports would be in place?

**Comment by timoreimann** [comment]
@jmagnusson we might be able to use reflection to achieve that. Alternatively, we put a big red sign right before the Go version specifier in the Go builder Docker image we use that says something like "do not update without updating the TLS ciphers too".

Regardless of what the best approach is, you are raising a valid point. Would you mind filing an issue?

**Pull request merged**
