### PR TITLE
feat: document how to use intermediate certificates

### PR DESCRIPTION
**Pull request by Trois-Six**
### What does this PR do?

Just add a sentence on how we support intermediate certificates in Traefik

### Motivation

Looking at the documentation, I asked myself if Traefik supports intermediate certificates, and it wasn't obvious. I am not the only one to ask the question: https://github.com/containous/traefik/issues/2957.

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

I am not sure about the location of that new paragraph ?

### CODE REVIEW

**Comment by mpl** [comment]
I'm not convinced this belongs to the traefik doc itself, so I'll let someone else approve it for now.

**Comment by PCM2** [comment]
Can anyone confirm that the proposed solution works? I don't presently have a development environment that would allow me to do this.

**Comment by notsureifkevin** [comment]
> 
> 
> I'm not convinced this belongs to the traefik doc itself, so I'll let someone else approve it for now.

I second this, this is more of a client / consumer concern, and we're sort of just a messenger.

**Comment by SantoDE** [comment]
Hello @Trois-Six,

after checking, we will turn down this PR for now and see, if it will have a place later on.

Thanks!

**Pull request closed without merging**
