### PR TITLE
Don't run go test on .glide cache folder

### PR DESCRIPTION
**Pull request by vdemeester**
Because… you know… 🐻

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by trecloux** [comment]
LGTM 👍

**Comment by guilhem** [comment]
:+1: I had to do it in my PR https://github.com/containous/traefik/pull/843/commits/c9ba1569f042b68dd3160d0a6656577355848ec1 :angel:

**Comment by vdemeester** [comment]
@guilhem yep I saw 👼 🙇 
Once you're PR is green and merged, I'll close this one 😝

**Comment by guilhem** [comment]
@vdemeester you can merge this one, I will rebase :)

**Pull request merged**
