### PR TITLE
Support multiple endpoints for KV stores:

### LINKED ISSUE #222: Support high availability / multiple endpoints for KV stores
Currently, Traefik doesn't support providing multiple endpoints for KV stores. See: https://github.com/containous/traefik/blob/1881d5eeed4a25164ab9d3fb8e391ac8359b15f8/provider/kv.go?ts=2#L28

We just need to change:
```golang
[]string{provider.Endpoint}
```
to
```golang
strings.Split(provider.Endpoint, ",")
```

We're planning on running Traefik in a high-availability environment. Depending on a single KV node is not an option.

Happy to send a PR over! :)

### PR DESCRIPTION
**Pull request by advait**
- Fixes #222

### CODE REVIEW

**Comment by vdemeester** [comment]
@advait could we have a small integration test for it (with `etcd` for example) :wink:

**Comment by emilevauge** [comment]
@advait 
Thanks for your contribution!
+1 for an integration test ;)

**Comment by advait** [comment]
@emilevauge @vdemeester I've taken the liberty to add a new etcd integration test which was missing! This test spins up a quorum of three etcd nodes and configures traefik to use them!

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by emilevauge** [comment]
Thank you @advait  :)
LGTM

**Pull request merged**
