### PR TITLE
Adding support for `HostSNIRegex` for TCP routers

### PR DESCRIPTION
**Pull request by sponte**
### What does this PR do?

Adds support to use regex matching in TCP routers.

### Motivation

Currently there is no way of doing a wildcard match against the host for TCP routers e.g. `*.mydomain.com`. This is supported under HTTP routers. Since we can read the hostname
from ClientHello, we can allow regex matching against the host.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

This requires a lot more thinking. I don't know traefik inside-out and am sure there are other considerations to be made with regards to this functionality. E.g. how and when do ACME certificates get mapped. For my needs, I only need to use wildcard matching with `tls.passthrough`.

### CODE REVIEW

**Comment by kdankert** [comment]
I would really like to be able to use this in production, I would just need it using tls passthrough as well. Is there anybody working on this or eager to implement this?

**Comment by FuNK3Y** [comment]
I would have the exact same use case. Any way I could help here?

**Comment by FuNK3Y** [comment]
@sponte can you grant permission to your branch? This way I could help and maybe start with doc

Can can take full credit - I am only interested in having the feature implemented

**Comment by ldez** [comment]
Just to be clear @FuNK3Y is not a member of the Traefik team.

@FuNK3Y you don't need rights on @sponte repo, you just have to create a pull request on his fork.

**Comment by itapai** [comment]
any estimate on this?

**Comment by FuNK3Y** [comment]
> Just to be clear: @FuNK3Y is not a member of the Traefik team.
> 
> @FuNK3Y you don't need rights on @sponte repo, you just have to create a pull request on his fork.
> 
> FYI, this pull request is still in the `design-review` status.

Ha! I was not aware of that feature - neat! I did the the PR as suggested: https://github.com/eu-evops/traefik/pull/1

**Comment by sponte** [comment]
Hello @juliens - have you created proposal yourself or are suggesting we do it? Happy to do it, just don't want to duplicate effort if its already in place

**Comment by juliens** [comment]
Hello @sponte I haven't created a proposal, it would be great if you take the time to create one. Thank you

**Pull request closed without merging**
