### PR TITLE
Add dark theme for Web UI

### LINKED ISSUE #5975: Dark theme for UI
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Light/dark switch in toolbar of web UI to switch color scheme.
This can be useful for night work or just for those who love dark theming.
Maybe I'll start this myself, but first I need some feedback about this feature.

### PR DESCRIPTION
**Pull request by sh7dm**
### What does this PR do?
Add dark theme variant for Traefik Web UI

### Motivation
Fixes #5975

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by sh7dm** [comment]
this needs an update too 
image

**Comment by matthieuh** [comment]
@sh7dm the dark icon looks good to me even if think it could be possible playing with opacity to avoid an image for both themes.

**Comment by sh7dm** [comment]
If we use opacity the middle layer will be visible through top one. Maybe you have an idea how to do that?

**Comment by matthieuh** [comment]
@sh7dm Yes good catch the way you did seems actually the best :)

**Comment by sh7dm** [comment]
@matthieuh I did almost all of things you said to do, but some of them were just not in Traefik code but Quasar one, so can't be fixed.

**Comment by matthieuh** [comment]
@sh7dm Good job man all seems much better now 👌However I will have a latest comment on the subnav when mode is dark:

expecting:
Screen Shot 2020-02-27 at 14 53 33

getting:
Screen Shot 2020-02-27 at 14 53 48

**Pull request merged**
