### PR TITLE
Display priority in web UI

### PR DESCRIPTION
**Pull request by sh7dm**
### What does this PR do?
Add priority to main routing table

### Motivation
Adresses #5667, but only partially.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
@sh7dm could you "rebase" this PR on v2.1? thank you

**Comment by ldez** [comment]
there is a problem during the rebase you have some extra commits.

**Comment by sh7dm** [comment]
There's! Sorry for taking time, I'm rebasing now.

**Comment by sh7dm** [comment]
@ldez done. As I see, v2.1 uses q-table, so this PR can also (probably) adress the other part of issue (sorting).

**Comment by ldez** [comment]
I prefer to keep PR with one topic at time.

The priority can be seen as a bug (branch v2.1) but the sorting is a enhancement (branch master)

**Comment by sh7dm** [comment]
Okay, let's keep this clear. Is there any other things I should do for this to be merged?

**Comment by ldez** [comment]
We will review the PR now. Thanks.

**Comment by ldez** [comment]
I am embarrassed, I misread the PR and I was wrong, it is not a bug fix but an enhancement.

I'm really sorry, I have to ask you to rebase your PR on the master branch.

Sorry again, it's my fault.

**Comment by sh7dm** [comment]
@ldez should be fine now.

**Comment by sh7dm** [comment]
Was the commit you asked to squash in https://github.com/containous/traefik/commit/77cb27593dcdd908d297f8d30bb1e92862b11936 ?

**Comment by ldez** [comment]
Yes it's this commit (column order)

**Comment by sh7dm** [comment]
I can't cherry-pick it :man_shrugging:

**Comment by sh7dm** [comment]
May I just copy the code and commit myself?

**Comment by ldez** [comment]
yes don't care about my code, you can redo it

**Comment by ldez** [comment]
The priority can be large (9223372036854775807) so the render is not really good is this case.
The max value is used by default for internal routers so it's not a edge case.

**Comment by sh7dm** [comment]
@ldez fixed!
image
Does this (fixed) look good?

**Comment by ldez** [comment]
Not really, for me the priority column take too many space in the table.

**Comment by sh7dm** [comment]
on a narrower resolution:
image

**Comment by sh7dm** [comment]
What should we do with it? just sorting?

**Comment by notsureifkevin** [comment]
@sh7dm Thank you for your contribution, the back-end API currently does not support sorting. Since the front-end UI does lazy loading this makes sorting, in effect, impossible considering those constraints.

With the amount of horizontal space in the table limited, making this addition doesn't make sense at this time given the constraints of being unable to sort.

There are a couple of feature additions that I would recommended proposing in order to support adding this column to the table:

-  Adding the ability to customize the table columns by toggling certain fields on/off - with sane defaults
- Adding the ability to sort in the API (defaults to no sort, as sorting creates additional overhead - which should always be optionally)

It's also worth noting that adding any/all of these features is non-trivial and would require additional considerations, and making these suggestions doesn't necessarily mean these feature requests would be accepted.

For the time being, I propose we close this PR and continue the discussion here: https://github.com/containous/traefik/issues/5667

**Pull request closed without merging**
