### PR TITLE
K8s: add an option to configure "PathPrefixStrip" for the ingress-resource using annotation

### PR DESCRIPTION
**Pull request by AlmogBaku**
solves https://github.com/containous/traefik/issues/372

### CODE REVIEW

**Comment by AlmogBaku** [comment]
Wooho! Tests passed =]

@emilevauge What do you think?

**Comment by emilevauge** [comment]
@AlmogBaku thanks a lot for your contribution!
I have 2 comments.
I think it would be better to stay compliant with traefik labels (from Docker/Marathon backend): we should store this in a `traefik.frontend.rule` key in annotation:
```
Annotations:
  traefik.frontend.rule:          PathPrefixStrip
```
Also, it would be great to add some docs here http://docs.traefik.io/toml/#kubernetes-ingress-backend :)
WDYT?
/cc @mgoodness, @ekozan

**Comment by AlmogBaku** [comment]
@emilevauge Make sense, I'm on it.

**Comment by AlmogBaku** [comment]
@emilevauge @mgoodness @ekozan
Following up to the Slack convo, I've update the PR to include controlling over the rule type by:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-my-svc
  annotations:
    traefik.frontend.rule.type: "PathPrefixStrip"
spec:
  rules:
    - host: api.example.net
      http:
        paths:
          - path: /mySvc
            backend:
              serviceName: mysvc
              servicePort: 80
```

The PR now includes:
- enhanced k8s capability with the annotation
- tests
- updated example
- updated documentation that include the information about the feature specified above

**Comment by emilevauge** [comment]
Thanks @AlmogBaku :)
LGTM
/cc @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐼

**Pull request merged**
