### PR TITLE
Remove traefik.frontend.value support in docker…

### PR DESCRIPTION
**Pull request by vdemeester**
… provider 👼. Was deprecated in 1.0, removing it for 1.1.

/cc @samber @emilevauge @errm @cocap10 @Russell-IO 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks @vdemeester, but https://github.com/containous/traefik/search?l=go&q=DEPRECATED&utf8=%E2%9C%93 ;)

**Comment by vdemeester** [comment]
@emilevauge damn you :joy: I'll update :wink:

**Comment by errm** [comment]
LGTM

**Comment by samber** [comment]
LGTM

**Comment by emilevauge** [comment]
LGTM

**Pull request merged**
