### PR TITLE
Update go-acme/lego to 3.2.0

### LINKED ISSUE #5317: ACME fails when using same domains in multiple routers
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?

While testing v2.0.0-rc2 I tried to reproduce my current setup and came up with the provided config below (only the relevant bits are given for briefness). On the initial run, I got the provided errors. I checked my DNS setup, but I was unable to see any ACME TXT records.

I then tried to remove the `tls` settings from one of the routers, and certificate was generated. Upon returning the settings, and restarting, no errors were reported and all routers had the same certificate.

So it seems that this only manifests when you try to request the same certificate for multiple routers.

### What did you expect to see?

LE certificates being generated on first run.

### What did you see instead?

Errors in the log (pasted like code to preserve wildcard characters):

```
time="2019-09-06T22:50:02Z" level=error msg="Unable to obtain ACME certificate for domains \"*.domain.com,domain.com\" : unable to generate a certificate for the domains [*.domain.com domain.com]: acme: Error -> One or more domains had a problem:\n[*.domain.com] [*.domain.com] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":81057,\\\"message\\\":\\\"The record already exists.\\\"}],\\\"messages\\\":[],\\\"result\\\":null}\"\n[domain.com] [domain.com] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":81057,\\\"message\\\":\\\"The record already exists.\\\"}],\\\"messages\\\":[],\\\"result\\\":null}\"\n" providerName=domain.acme


time="2019-09-06T22:50:10Z" level=error msg="Unable to obtain ACME certificate for domains \"*.domain.com,domain.com\" : unable to generate a certificate for the domains [*.domain.com domain.com]: acme: Error -> One or more domains had a problem:\n[*.domain.com] acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/finalize/65298024/1037519921 :: urn:ietf:params:acme:error:orderNotReady :: Order's status (\"deactivated\") is not acceptable for finalization, url: \n[domain.com] acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/finalize/65298024/1037519921 :: urn:ietf:params:acme:error:orderNotReady :: Order's status (\"deactivated\") is not acceptable for finalization, url: \n" providerName=domain.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.0.0-rc2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`traefic.toml`
```
...
[providers.file]
  filename = "config.toml"

[certificatesResolvers.domain.acme]
  email = "email@address.com"
  storage = "acme.json"
  keyType = "EC256"
  acmeLogging = true
  [certificatesResolvers.domain.acme.dnsChallenge]
    provider = "cloudflare"
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
...
```
`config.toml`
```
...
[http.routers.traefik]
  rule = "host(`traefik.domain.com`)"
  middlewares = ["default","auth"]
  service = "traefik"
  [http.routers.traefik.tls]
    options = "default"
    certResolver = "domain"
    [[http.routers.traefik.tls.domains]]
      main = "*.domain.com"
      sans = ["domain.com"]
[http.routers.site]
  rule = "host(`site.domain.com`)"
  middlewares = ["default"]
  service = "site"
  [http.routers.site.tls]
    options = "default"
    certResolver = "domain"
    [[http.routers.site.tls.domains]]
      main = "*.domain.com"
      sans = ["domain.com"]
...
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by kolaente**
### What does this PR do?

Updates go-acme/lego to 3.2.0: https://github.com/go-acme/lego/releases/tag/v3.2.0

### Motivation

Fixes bug with:
- Aurora DNS
- Cloudflare
- Digital Ocean
- OVH

Fixes #5317

Additional:
- add autodns support.

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

I only ran `go get -u github.com/go-acme/lego/v3`, verified tests are still passing and updated the docs, do I need to do anything else?

### CODE REVIEW

**Comment by ldez** [comment]
@kolaente could you:

- rebase the PR on the branch `v2.0`
```
git rebase --onto upstream/v2.0 f30a52c2
```
- run 
```
go mod tidy
```

**Comment by kolaente** [comment]
@ldez Rebased, but `go mod tidy` fails with 
```
github.com/containous/traefik/v2/cmd/traefik imports
	github.com/containous/traefik/v2/autogen/genstatic: module github.com/containous/traefik@latest (v1.7.19) found, but does not contain package github.com/containous/traefik/v2/autogen/genstatic
```

**Comment by kolaente** [comment]
Also, I guess I should target Branch `v2.0`?

**Comment by ldez** [comment]
@kolaente could you:

```
rm -rf autogen
go generate
go mod tidy
```

**Comment by ldez** [comment]
Because of the undocumented and breaking changes made by GitHub, the PR content from a fork by a GitHub organization can no longer be changed by us or by our bot and it's a pain.
Sorry.

**Comment by kolaente** [comment]
> Because of the undocumented and breaking changes made by GitHub, the PR content from a fork by a GitHub organization can no longer be changed by us or by our bot and it's a pain.
> Sorry.

Sure no problem. I've run your commands, it worked without issues.

**Comment by LeslieRan** [comment]
> @kolaente could you:
> 
> ```
> rm -rf autogen
> go generate
> go mod tidy
> ```

I have run those commands and the issue is still exsiting. Is there any other solutions?

**Comment by LeslieRan** [comment]
And there is a also another compiling problem:
```
github.com/traefik/traefik/v2/pkg/plugins imports
	github.com/traefik/yaegi/stdlib imports
	hash/maphash: malformed module path "hash/maphash": missing dot in first path element
```

**Comment by kolaente** [comment]
@LeslieRan What are you trying to do here? What issue? This PR has been merged since over a year now, maybe it'd be better to open a new issue?

**Pull request merged**
