### PR TITLE
Re-organize documentation

### PR DESCRIPTION
**Pull request by jmaitrehenry**
### Description
- Create a Backend section for the documentation and split toml page into different backends pages
- Create a configuration section, put traefik.toml and acme pages here.
- Update some list into table (API, Consul)
- sync traefik.sample.toml and documentation.

It could be interesting to move user-guide in each associated backend, the HA/cluster into Configuration.

### CODE REVIEW

**Comment by ldez** [comment]
Awesome job ❤️ 
Could you rebase on master?

**Comment by jmaitrehenry** [comment]
@ldez Done

**Comment by ldez** [comment]
@jmaitrehenry Due to the size of the PR, if necessary, do you allow us to change your PR instead of making a painful/long review?

**Comment by jmaitrehenry** [comment]
Sure, no problem.

Envoyé de mon iPhone

**Comment by jmaitrehenry** [comment]
Awesome work @ldez ! 😍 🎉

**Comment by jmaitrehenry** [comment]
One little thing, the table first column is not really readable: https://deploy-preview-2012--traefik-docs.netlify.com/configuration/backends/docker/

**Comment by SerialVelocity** [comment]
Hey @jmaitrehenry and @ldez,

The documentation/example about "forward auth" seems to have disappeared due to this PR. Was that intentional?

Best,
Ben

**Comment by ldez** [comment]
@SerialVelocity it's already fixed https://github.com/containous/traefik/pull/2110

**Comment by SerialVelocity** [comment]
Nice, thank you! ❤️

**Pull request merged**
