### PR TITLE
fix: header middleware response writer.

### LINKED ISSUE #7250: Regression in v2.2.10 - Some element in page are not displayed
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
No error

### What did you see instead?
Some element of the pages behind traefik does not show. Error in the log that were not present in 2.2.8

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.10
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-04T15:53:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_FOLDER}/traefik:/data
    ports:
      - 9080:80
      - 9443:443
    extra_hosts:
      - host.docker.internal:x.x.x.x
    restart: always
    command:
      - --accesslog=true
      - --api
      - --providers.file.directory=/data
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultrule=Host(`{{ normalize .Name | replace "-${COMPOSE_PROJECT_NAME}" ".${DOMAIN}"}}`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.default.acme.httpchallenge=true
      - --certificatesresolvers.default.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.default.acme.storage=/data/acme.json
      - --entrypoints.websecure.http.tls.certresolver=default
      - --entrypoints.websecure.http.middlewares=sts@docker
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --serverstransport.insecureskipverify=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      # Global settings
      - traefik.http.middlewares.sts.headers.stspreload=true
      - traefik.http.middlewares.sts.headers.stsseconds=31536000
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-09-04T20:58:02Z" level=error msg="Stack: goroutine 49043 [running]:\ngithub.com/containous/traefik/v2/pkg/middlewares/recovery.recoverFunc(0x2ec3a60, 0xc001460b40, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b500)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/recovery/recovery.go:47 +0x1db\npanic(0x24c0be0, 0xc0012cc900)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/containous/traefik/v2/pkg/middlewares/pipelining.(*writerWithoutCloseNotify).Hijack(0xc000aa2870, 0x7f65d7d47e08, 0xc0009d3320, 0x2eb97a0, 0xc0009d3320, 0x1)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/pipelining/pipelining.go:69 +0x47\nnet/http/httputil.(*ReverseProxy).handleUpgradeResponse(0xc001255720, 0x2ea76a0, 0xc000aa2870, 0xc00065a600, 0xc000bd8360)\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:530 +0x309\nnet/http/httputil.(*ReverseProxy).ServeHTTP(0xc001255720, 0x2ea76a0, 0xc000aa2870, 0xc00065a500)\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:268 +0xf07\ngithub.com/containous/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0xc000a10f40, 0x2ea7660, 0xc0014224b0, 0xc00065a500)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/pipelining/pipelining.go:36 +0xe7\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.AddServiceFields(0x2ea7660, 0xc0014224b0, 0xc00065a500, 0x2e5a300, 0xc000a10f40, 0xc0015bdfc0)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:47 +0x134\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0015bcc00, 0x2ea7660, 0xc0014224b0, 0xc00065a500)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0x10b\ngithub.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0xc000560bd0, 0x2ea7660, 0xc0014224b0, 0xc00082b800)\n\t/go/pkg/mod/github.com/vulcand/oxy@v1.1.0/roundrobin/rr.go:147 +0x13d\ngithub.com/containous/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0xc000a10f90, 0x2ea7660, 0xc0014224b0, 0xc00082b800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:31 +0x168\ngithub.com/containous/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0xc000cabf20, 0x2ea7660, 0xc0014224b0, 0xc00082b800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x609\ngithub.com/containous/traefik/v2/pkg/middlewares/auth.(*forwardAuth).ServeHTTP(0xc00139e100, 0x2ea7660, 0xc0014224b0, 0xc00082b800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/auth/forward.go:158 +0x83d\ngithub.com/containous/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc0017b4120, 0x2ea7660, 0xc0014224b0, 0xc00082b800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x16a\ngithub.com/containous/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP.func1(0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/headers/secure.go:52 +0xea\ngithub.com/unrolled/secure.(*Secure).HandlerFuncWithNextForRequestOnly(0xc0000df180, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b700, 0xc000cdaca8)\n\t/go/pkg/mod/github.com/unrolled/secure@v1.0.7/secure.go:228 +0x201\ngithub.com/containous/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP(0x2e5a420, 0xc0017b4120, 0xc0000df180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/headers/secure.go:51 +0x7a\ngithub.com/containous/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0xc000d89580, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b700)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/headers/headers.go:75 +0x52\ngithub.com/containous/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc0017b4300, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b700)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x16a\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0015bcc40, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b700)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:38 +0x144\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000580ba0, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b500)\n\t/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x112\ngithub.com/containous/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc000d89700, 0x7f65d7d47b18, 0xc0003a03f0, 0xc00082b500)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/recovery/recovery.go:33 +0x104\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.AddOriginFields(0x7f65d7d47b18, 0xc0003a03e8, 0xc00082b500, 0x2e5a340, 0xc000d89700, 0xc0015bdfc0)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:55 +0x198\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0015bcd40, 0x7f65d7d47b18, 0xc0003a03e8, 0xc00082b500)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0x10b\ngithub.com/containous/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc0000a9290, 0x7f65d7d47b18, 0xc0003a03e8, 0xc00082b400, 0xc000cdb4f8)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x37d\ngithub.com/containous/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1(0x7f65d7d47b18, 0xc0003a03e8, 0xc00082b400)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x83\nnet/http.HandlerFunc.ServeHTTP(0xc000d89800, 0x7f65d7d47b18, 0xc0003a03e8, 0xc00082b400)\n\t/usr/local/go/src/net/http/server.go:2041 +0x44\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0xc00007fce0, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300, 0x2e60a40, 0xc000d89800)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/logger.go:222 +0xace\ngithub.com/containous/traefik/v2/pkg/middlewares/accesslog.WrapHandler.func1.1(0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/accesslog/logger.go:68 +0x5a\nnet/http.HandlerFunc.ServeHTTP(0xc000d89820, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/usr/local/go/src/net/http/server.go:2041 +0x44\ngithub.com/containous/traefik/v2/pkg/server/router/tcp.(*Manager).buildEntryPointHandler.func1(0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/go/src/github.com/containous/traefik/pkg/server/router/tcp/router.go:194 +0x16f\nnet/http.HandlerFunc.ServeHTTP(0xc000d89ba0, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/usr/local/go/src/net/http/server.go:2041 +0x44\ngithub.com/containous/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0xc0000a9288, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/handler_switcher.go:23 +0x70\ngithub.com/containous/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc00004eeb0, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/go/src/github.com/containous/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:173 +0x10b\nnet/http.serverHandler.ServeHTTP(0xc0000f8700, 0x2eb97e0, 0xc0000f87e0, 0xc00082b300)\n\t/usr/local/go/src/net/http/server.go:2836 +0xa3\nnet/http.(*conn).serve(0xc0001a26e0, 0x2ec39a0, 0xc0015bdec0)\n\t/usr/local/go/src/net/http/server.go:1924 +0x86c\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2962 +0x35c\n" middlewareName=traefik-internal-recovery middlewareType=Recovery

```

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Adds `Hijack` and `Flush` methods on the response writer of the headers middleware.

### Motivation

Fixes  #7250

### More

- ~~[ ] Added/updated tests~~
-  ~~[ ] Added/updated documentation~~

### CODE REVIEW

**Review by j3458 — DISMISSED** [review]
Hacked address

**Review by SantoDE — APPROVED** [review]
Lgtm

**Review by juliens — APPROVED** [review]
LGTM

**Review by rtribotte — APPROVED** [review]
LGTM

**Pull request merged**
