### PR TITLE
fix concurrent provider config reloads

### PR DESCRIPTION
**Pull request by marco-jantke**
This PR fixes problems with concurrent provider reloads in relation with the throttling functionality of the provider reloads. 

The failure scenario before looked the following way:

- given we have a ProvidersThrottleDuration of 2 seconds and two providers
configured: Provider A and B.
- a configuration update comes in of provider A at second 0. This config
gets applied.
- a configuration update comes in of provider B at second 1. The config
  reload gets delayed.
- a configuration update comes in of provier A at second 1.5. This
  config reload gets delayed.
- it is second 2.0 and the last config update of provider A gets
  applied, whereas the config update of provider B is lost.

This PR fixes this problem by applying the config reload throttling individually for each provider.

Note: As I removed the last usage of concurrent-map with this PR, I also removed the dependency in glide and the vendor directory.

### CODE REVIEW

**Comment by marco-jantke** [comment]
Anyone else wants to have a look 👼 

I would go and rebase after the final approve if this is OK.

**Comment by ldez** [comment]
@marco-jantke could you resolve conflicts before?

**Comment by marco-jantke** [comment]
Yes, sure thing. Rebased.

**Comment by ldez** [comment]
@marco-jantke could you rebase again?

**Comment by ldez** [comment]
@marco-jantke Are you here? 😄

**Comment by marco-jantke** [comment]
Yes I am, at least kind of.. :D 

I already tried to rebase, but there are some real merge conflicts now that I have to take care of. Sorry, I am very busy these weeks/months and try to come back to it soonish.

**Comment by marco-jantke** [comment]
@ldez rebase is done. 

Thanks @nmengin for the help :)

**Pull request merged**
