### PR TITLE
Add addHeadersToResponse option in forward auth middleware

### PR DESCRIPTION
**Pull request by ashutoshgngwr**
### What does this PR do?

Adds a config option in forward auth middleware to allow adding headers from auth server to request's response.

### Motivation

Traefik allows copying response headers from auth server to upstream request in forward authentication. This makes it difficult to perform tasks such as updating authentication headers in response.

#### Inspiration
_I was fooling around and all unit tests passed_, and also #3660 

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by jwheeler-gs** [comment]
Can there be an option added to this to allow appending to headers instead of just overwriting like Envoy proxy supports? If the motivation is to be able to update authentication headers, this could cause problems if a lower layer is also trying to update headers (ie. via set-cookie) on the same response.

**Comment by ashutoshgngwr** [comment]
@dduportal I was wondering about a few things myself as @jwheeler-gs pointed out. In my additions, I am directly setting header values (overwriting any previously set values, I am not sure if there are?). Should this be desired behaviour or should I consider appending header values. Also, once auth middleware sets a value for a header, will it be overwritten if any other (next-in-queue) middleware or the upstream request to backend tries to set it?

**Comment by iamolegga** [comment]
@ashutoshgngwr hey!

> Edit: I just ran unit tests to check if response headers are overwritten by upstream request. They do and I need help because I think this is unacceptable behaviour (for headers such as Set-Cookie)!

Did you push this test to github, because I don't see any checks related to this problem. I would like to continue your work if you don't mind 🙂

**Comment by ashutoshgngwr** [comment]
@iamolegga It was a long time ago and I was merely familiar with Golang syntax at the time. If you really want to work on this feature, I'd suggest a start from scratch. At the time, the issue was that in this implementation, the response headers from the actual request's response would get overwritten by those from the response of the forward auth. This only happened for headers that were present in both the responses. And no, I didn't push the unit tests.

PS, I haven't read through it in-depth but #3660 seems to propose this very feature.

**Comment by iamolegga** [comment]
Ok, thanks!

**Comment by iamolegga** [comment]
I've just dived to the problem with overwriting headers. So, what I think is we have 3 cases:

- `Set-Cookie` header is allowed to be set multiple times for different cookie names. [rfc6265](https://tools.ietf.org/html/rfc6265#page-7). So there should not be problem with that.
- `Set-Cookie` sent from `forwardAuth` service should be overwritten by target service in case they have same cookie names.
- For all the other headers values must be concatenated

Is this this the right behaviour?

**Comment by ashutoshgngwr** [comment]
@iamolegga I am not sure about the correct behaviour but nothing should be overwritten with anything by default. We can leave the behavior to the user if we use `Header().Add` instead and move the adding-response-headers bit to after the next middleware is called.

https://github.com/ashutoshgngwr/traefik/blob/b9363180ac162c975e8a7f606e926e6421680274/pkg/middlewares/auth/forward.go#L155-L160

Try moving lines 155-157 to after 160. And using `Add` in-place of `Set` in 156.

**Comment by iamolegga** [comment]
@ashutoshgngwr I thought the same, but in that case if both send `Set-Cookie` with same cookie name, value from auth header will rewrite value from target header, and I think this is wrong behaviour. I think that target service headers should be prioritised over auth service headers

**Comment by ashutoshgngwr** [comment]
@iamolegga here are my thoughts on this.

Since user is specifying exactly which headers to copy, we should try to copy them after next middlewares have responded. We should also check if we will be overwriting anything. If we are in such a situation, we can print a warning/error to the user saying that we will not copy such header from auth response since it is already present in request's response.

**Pull request closed without merging**
