### PR TITLE
Unix socket support for services

### PR DESCRIPTION
**Pull request by sloonz**
### What does this PR do?

This adds Unix domain socket support for services, both on HTTP/1 and HTTP/2.

### Motivation

Copy-paste from https://github.com/containous/traefik/issues/4881 requesting the feature : 

Listening on Unix sockets is extremely useful in non-containerized environments (like the file provider), since it doesn’t require port allocation management, they honor filesystem ACLs, and they don’t risk raw port exposure on the internet in case of firewall/listening interface misconfiguration (in architectures when access control is the responsibility of the reverse proxy).

### More

- [x] Added/updated tests
- [X] Added/updated documentation

### Additional Notes

What is missing is TLS (for HTTP 1 and HTTP 2) over Unix sockets. Given that unix sockets are necessarily on the same machine, I don’t see any possible use-case for it.

### CODE REVIEW

**Comment by hostmit** [comment]
Have this been tested already? Merge soon?

**Comment by PackElend** [comment]
hi,
will it be merged into main?

use case is here
https://meta.discourse.org/t/difference-between-socket-and-port-based-connection-to-outer-nginx/60071
UNIX socket is preferred over TCP socket

**Comment by juliens** [comment]
Sorry for the delay.

Thank you for your interest in the project and the time you took to complete this PR!

I have talked with other maintainers about this feature, and to be honest, we are not really "fans" of it because we think it doesn't fit well in a cluster environment.

Although we understand that sometimes "the UNIX socket is preferred to the TCP socket", we believe that Traefik should not have direct access to this socket.

I will decline this PR for now, but if other use cases appear in the linked issue, we will be happy to consider reopening it.

**Comment by Razikus** [comment]
Use case:
1. Container needs access to host network, and exposes api
2. api can't be grabbed by traefik, cause it's bridged
3. can't make it working without workarounds, REALLY easy to make with unix sockets

**Comment by maxried** [comment]
TCP sockets are extremely slow compared with UNIX sockets as the add unnecessary overhead.

**Comment by rytsh** [comment]
There is another way to do that, write custom plugin and call unix socket with http.

**Pull request closed without merging**
