### PR TITLE
Use debug for log about skipping addition of cert

### PR DESCRIPTION
**Pull request by sylr**
### What does this PR do?

This entry can flood the logs if a cert is duplicated like wildcard certs can be.

### Motivation

Backport https://github.com/containous/traefik/pull/5641 in v1.7 tree.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by sylr** [comment]
FYI, this is what happened when we deployed the v2.0 patched version:

Search___Splunk_7_0_11_1

**Comment by ldez** [comment]
Hello,

I recommend to use the level `WARN` instead of `INFO`.

**Comment by sylr** [comment]
Hi

> I recommend to use the level WARN (the default level) instead of INFO in your configuration.

But if I do this I would lose access logs which use the INFO level, wouldn't I ?

**Comment by ldez** [comment]
The log level is for [Traefik log](https://docs.traefik.io/v1.7/configuration/logs/#traefik-logs).

The [access logs](https://docs.traefik.io/v1.7/configuration/logs/#access-logs) don't have a level.

**Comment by ldez** [comment]
As much as this change made sense in the v2 because of the management of the TLS on the routers, as much on the v1 that does not seem to me relevant.

So we will declined.

Thanks anyway.

**Pull request closed without merging**
