### PR TITLE
Add IP Blacklisting

### PR DESCRIPTION
**Pull request by mattdavis90**
### What does this PR do?

Added IP Blacklist support, in line with the current IP Whitelisting. Influenced by https://github.com/containous/traefik/issues/4026

### Motivation

Issue https://github.com/containous/traefik/issues/4026

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by nmengin** [comment]
Hello, @mattdavis90 

Thanks for you contribution :+1: 

We accept only bug fixes on 1.7 https://github.com/containous/traefik#release-cycle

Your PR seems interesting, could you rebase on master?
Thanks.

**Comment by ldez** [comment]
Thanks for your contribution :+1: 

We want to keep the IP filtering section as simple as possible and we think that your use case could be addressed differently.

We think that a blacklisting task can be better achieved using a firewall.

So, for now, and I insist on the "for now", we will decline your pull request.

**Comment by anantsaraswat** [comment]
@ldez I agree it's easy to use firewall for the same, But my ony issue is how we get client IP address? 

Let's say I am running tomcat behind traefik and a hacker run DDOS attack against the same, how will I get the client IP address from traefik? So that I can block that.

**Comment by helmut72** [comment]
> We think that a blacklisting task can be better achieved using a firewall.

A firewall rule, pushed from Fail2ban, will block all services behind Traefik, if someone try too many wrong logins to a specific service.

> We want to keep the IP filtering section as simple as possible

Feels to simple ;)

**Pull request closed without merging**
