### PR TITLE
Update available TLS ciphers to include all available ciphers in Go.

### PR DESCRIPTION
**Pull request by kekoav**
I had a need to use specific TLS ciphers but found many ciphers were missing support in Traefik. This PR is simply intended to add all available TLS ciphers defined in Go 1.7.

### CODE REVIEW

**Comment by kekoav** [comment]
@timoreimann Absolutely. The documentation for this can be found for latest Go version at https://golang.org/pkg/crypto/tls/#pkg-constants (displays 1.8 values) . This changes as Go is updated so for a more "permalink" reference it may be better to reference the source code in GitHub:

* Go 1.7 TLS Ciphers https://github.com/golang/go/blob/release-branch.go1.7/src/crypto/tls/cipher_suites.go#L269-L285
* Go 1.8 TLS Ciphers https://github.com/golang/go/blob/release-branch.go1.8/src/crypto/tls/cipher_suites.go#L369-L390 

I would be happy to update this for 1.8 as well, which has some nice additions.

**Comment by kekoav** [comment]
@timoreimann I also added the ciphers for 1.8. See #1276.

**Comment by timoreimann** [comment]
@kekoav could you rebase and resolve the merge conflicts?

**Comment by timoreimann** [comment]
@kekoav any chance for an update?

**Comment by timoreimann** [comment]
I tried to fix this myself but ended up making things worse. :-(

Reverted back to the previous state. @kekoav, we need your help.

**Comment by ldez** [comment]
Seems be a duplicate of #1276

**Comment by ldez** [comment]
Closing this PR in favor of #1276.

**Pull request closed without merging**
