### PR TITLE
Adding support for Traefik to respect the K8s ingress class annotation

### LINKED ISSUE #1163: traefik doesn't respect kubernetes.io/ingress.class
traefik: 1.1.2
kubernetes: 1.5.2
OS: ubuntu 14.04

Test kubernetes deployment, service, ingress:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path:
        backend:
          serviceName: nginx
          servicePort: 80
```

Important:
There is `metadata.annotations: kubernetes.io/ingress.class: "nginx"` in ingress.

Instead of skip this ingress (`kubernetes.io/ingress.class: "nginx"`) traefik is processing it and adding frontend and backend:
```
# curl -s 127.0.01:8080/api | jq '.kubernetes.frontends["example"]'
{
  "priority": 0,
  "passHostHeader": true,
  "routes": {
    "example.com": {
      "rule": "Host:example.com"
    }
  },
  "backend": "example.com",
  "entryPoints": [
    "http"
  ]
}
```
```
# curl -s 127.0.0.1:8080/api | jq '.kubernetes.backends["example.com"]'
{
  "loadBalancer": {
    "method": "wrr"
  },
  "servers": {
    "nginx-1691775941-kpx47": {
      "weight": 0,
      "url": "http://10.200.70.23:80"
    }
  }
}
```

Traefik should ship this ingress because of `kubernetes.io/ingress.class: "nginx"`.

### PR DESCRIPTION
**Pull request by Regner**
This is a first pass of making Traefik understand and respect the kubernetes.io/ingress.class annotation in Kubernetes.

There is a discussion in #1163 about how this should be handled. The objective of this PR is to have Traefik respond to the annotation in the same way other ingress controllers such as NGINX handle it. That being:
* Use ingress that have an annotation matching "traefik"
* Use ingress that have an annotation matching "" (a blank string)
* Use ingress that do not have the annotation at all
* Ignore all ingress that have an annotation of anything else

There is also discussion in the above mentioned issue about support for configuring what the annotation matches, for example being able to say "accept annotations that match traefik-internal" instead of matching on traefik. There doesn't seem to be clear consensus on how that should be handled. I think that should be spun out as a separate issue and done in isolation of this PR.

Fixes #1163 

Pinging @emilevauge @SantoDE @errm @dtomcej @vdemeester

### CODE REVIEW

**Comment by Regner** [comment]
Test failures seem unrelated. Something to do with timing out while pulling the golang container. Is there an easy way to retrigger that?

**Comment by dtomcej** [comment]
Weird. Restarted.

**Comment by Regner** [comment]
Thanks! Much appreciated.

**Comment by Regner** [comment]
Well, apparently my tests are not properly formatted. Taking a look now.

**Comment by Regner** [comment]
Moved the test for if an ingress should be processed into a separate function and made it a switch case. The code is a bit more verbose but i think a lot more clear as to its intentions. With that I think this is ready. :D

**Comment by Regner** [comment]
I believe this is ready for review. Sorry if I am spamming with the pings :)

Pinging @emilevauge @SantoDE @errm @dtomcej @vdemeester

**Comment by Regner** [comment]
Thanks once again for the comments @timoreimann, I was unaware of the comma usage in the switch statements.

Made the requested changes. :)

**Comment by timoreimann** [comment]
@Regner let's sync and merge. Looking forward to using this. :-)

**Pull request merged**
