### PR TITLE
Minor updates to dumpcerts.sh

### LINKED ISSUE #3115: contrib: dumpcerts.sh needs updating
### Do you want to request a *feature* or report a *bug*?

I wish to report a bug.

### What did you do?

I ran the `dumpcerts.sh` script against a legit ACME JSON file.

### What did you expect to see?

A directory populated with certificates and keys.

### What did you see instead?

An error prevented the script from actually executing -- this same error was mentioned here: https://github.com/containous/traefik/pull/1484#issuecomment-376046953 -- but when I addressed that issue, a number of other minor issues arose.  Apparently the JSON file's architecture has changed!

I have a working version and can submit a pull request, I just wanted to report the issue first.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I wasn't running Traefik per se, but `dumpcerts.sh` was last modified about 27 days ago in commit `8380de1bd9c5fdd751361fc3b40a81076a8a498b`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I ran this on an Ubuntu Linux system with `jq` and other tools installed as needed.

### PR DESCRIPTION
**Pull request by mathuin**
Closes #3115.

There was an extraneous $1 on line 69 which threw an error.  The locations of keys and certificates in the JSON file have changed.

### What does this PR do?

This pull request modifies `dumpcerts.sh` to run without errors and to access keys and certs in the JSON file correctly.

### Motivation

I now use Traefik to manage my LetsEncrypt certs for my mail server, so I needed to learn how to extract the certs and keys as files.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

I'm very new to Traefik.  All I can say about this script is "it works for me".  If it does not work for the general case, I would love to get some feedback to make a proper solution that works for both me and everyone else.  Thank you in advance for your patience!

### CODE REVIEW

**Comment by mathuin** [comment]
I have checked the `v1.6` branch and it does still have the `$1` issue.  As I am not running 1.6 locally, I will be unable to test the script's functionality, but I am happy to rebase my branch on the `v1.6` branch and remove all changes save the `$1` change.

**Comment by nmengin** [comment]
Hello @mathuin ,

It should be great if you can do it :smiley:

**Comment by mathuin** [comment]
I pulled the most recent changes for `master` and `v1.6`, then applied the single change to `v1.6` and force-pushed to `mathuin/fix-issue-3115`.  I *think* that worked.  Let me know if it didn't.

**Comment by mathuin** [comment]
Yeah, that did *not* go as I expected.  I'm sorry -- if it doesn't work, perhaps it's better to wait for your fix.

**Pull request merged**
