### PR TITLE
feat(webui): add doc and version in navbar

### PR DESCRIPTION
**Pull request by Slashgear**
### What does this PR do?

- ✨ Add Version in Navbar
- ✨ Add Documentation (based on version) link in Navbar

**Question** How can I map *version api* to *doc api* ?

### Motivation

- Helping User find Documentation directly in the Navbar is a sweet feature

### CODE REVIEW

**Comment by Slashgear** [comment]
Oops @ldez will fix that soon 🤕

**Comment by ldez** [comment]
@Slashgear friendly ping :wink:

**Comment by Slashgear** [comment]
In your case, what is the version JSON object from the version API ? :)

**Comment by ldez** [comment]
```json
{
  "Version": "v2.0.0-beta1",
  "Codename": "faisselle"
}
```

**Comment by Slashgear** [comment]
Is this ok for you now ?

**Pull request merged**
