### PR TITLE
extend and refactor prometheus metrics

### LINKED ISSUE #1759: Prometheus request metrics tracked twice
### Do you want to request a *feature* or report a *bug*?

*Bug*

### What did you do?

Setup a Traefik instance that provides Prometheus metrics.

### What did you expect to see?

Correct recording of http requests / http request durations metrics with the `service` label set to `backend1`.

### What did you see instead?

Doubled recording of http requests / http request durations metrics. One time with the `service` label `http` (entrypoint) + `backend1`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      dev
Codename:     cheddar
Go version:   go1.8.3
Built:        I don't remember exactly
OS/Arch:      darwin/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8080"

[file]

# rules
[backends]
  [backends.backend1]
     [backends.backend1.servers.server1]
     url = "http://localhost:8081"
     [backends.backend1.servers.server2]
     url = "http://localhost:8082"
     [backends.backend1.servers.server3]
     url = "http://localhost:8083"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Path:/ok"

[retry]
attempts = 3

[web]
address = ":8000"
  [web.metrics.prometheus]
    Buckets=[0.1,0.3,1.2,5.0]
```

### Problem Description

At the moment the Traefik metrics middleware is included twice in the middleware chain. One time the metrics are included in the `startHTTPServers` [here](https://github.com/containous/traefik/blob/2a578748fdb349bf92fb223c24397005b04cdc99/server/server.go#L195) and a second time when loading the config [here](https://github.com/containous/traefik/blob/2a578748fdb349bf92fb223c24397005b04cdc99/server/server.go#L786).

This leads to the following generated metrics when requesting the `/metrics` endpoint.

```
# HELP traefik_backend_retries_total How many request retries happened in total.
# TYPE traefik_backend_retries_total counter
traefik_backend_retries_total{service="backend1"} 14

# HELP traefik_request_duration_seconds How long it took to process the request.
# TYPE traefik_request_duration_seconds histogram
traefik_request_duration_seconds_bucket{service="backend1",le="0.1"} 7
traefik_request_duration_seconds_bucket{service="backend1",le="0.3"} 7
traefik_request_duration_seconds_bucket{service="backend1",le="1.2"} 7
traefik_request_duration_seconds_bucket{service="backend1",le="5"} 7
traefik_request_duration_seconds_bucket{service="backend1",le="+Inf"} 7
traefik_request_duration_seconds_sum{service="backend1"} 0.036858719
traefik_request_duration_seconds_count{service="backend1"} 7
traefik_request_duration_seconds_bucket{service="http",le="0.1"} 7
traefik_request_duration_seconds_bucket{service="http",le="0.3"} 7
traefik_request_duration_seconds_bucket{service="http",le="1.2"} 7
traefik_request_duration_seconds_bucket{service="http",le="5"} 7
traefik_request_duration_seconds_bucket{service="http",le="+Inf"} 7
traefik_request_duration_seconds_sum{service="http"} 0.037084179
traefik_request_duration_seconds_count{service="http"} 7

# HELP traefik_requests_total How many HTTP requests processed, partitioned by status code and method.
# TYPE traefik_requests_total counter
traefik_requests_total{code="200",method="GET",service="backend1"} 7
traefik_requests_total{code="200",method="GET",service="http"} 7
```

This is problematic, because effectively this means that when you aggregate the metrics in your Prometheus queries, without considering the labels, you will end up with twice as many requests as actually happen. Therefore the proper fix should be to remove the integration when starting the http servers. As one point to consider, this would mean that redirects are actually not tracked anymore. When tracking of the redirects is desired, I guess we should create a new metrics, to handle this cleanly.

Can you confirm that this is a bug for you and maybe give a recommendation on how to go for the fix?

### PR DESCRIPTION
**Pull request by marco-jantke**
For our internal Traefik setup I was working on improving the Prometheus metrics and wanted to upstream my work, as I guess this is potentially useful for a lot of Traefik users. It is planned to integrate more metrics in the future, but this PR already restructures the metrics implementation and provides significant benefits when monitoring Traefik with Prometheus. For more metrics  follow-up PRs will be smaller and more focused. It is important to note that in this rework, the metric naming was adapted in order to fix #1759 and to be more consistent. As the metrics implementation is in a rather young state, I had the feeling this is the right time to go for removing inconsistencies.

In general the following metrics are now available. Please check the code for details including the metric labels.
```
// server meta information
traefik_config_reloads_total
traefik_config_reload_failures_total
traefik_config_last_reload_success

// entrypoint
traefik_entrypoint_requests_total
traefik_entrypoint_request_duration_seconds

// backend level
traefik_backend_requests_total
traefik_backend_request_duration_seconds
traefik_backend_retries_total
```

In the course of extending the metrics I did some design reworks:

- I moved the implementation to an own package. This is necessary because some metrics get also collected in the server package and it makes the design more clear.
- I switched the prometheus test to a real integration test. On the one hand this made things easier on the other its a more "real world test".
- I changed the `Metrics` interface to one big interface. Even though this might not be the most idiomatic way in go, it makes it sufficiently easier for other potential future implementations to provide a "full" metrics implementation. Also the `VoidMetrics` and the general handling in the `server.go` is much easier through this.
- I integrated a `VoidMetrics` implementation to remove the necessity to check for nil on the consumer side.

### CODE REVIEW

**Comment by ldez** [comment]
The best practices when you do a refactor is to split each step in commits to facilitate the review and do mix refactor and improvements (or split into separate commit).

In the current state, this PR will be very hard to review.

**Comment by ldez** [comment]
Moreover this modification breaks the work done in the #1701

**Comment by marco-jantke** [comment]
In regards to splitting up the commits, when it helps you significantly I can split the commits and rebase accordingly. Let me know please when you want me to do it, because it will be also effort on my time.

In regards to breaking #1701. This is unfortunate, I wasn't aware of the PR. Though to be honest it is also "dangerous" to rely or consider it when moving forward, given it is open for longer than a month and no activity since 13 days. Anyway I think it will be not too much effort to adapt one of the two PRs after the merge of the other one. To be honest this PR will make integration of other providers in general easier and clearer and its design already accomplishes what @emilevauge requested in [one of his open PR comments](https://github.com/containous/traefik/pull/1701#discussion_r124837299).

What in general should be done and improved in this PR still are documentation. But I think it only makes sense for me to start with them when there is a clear chance that it gets merged.

**Comment by marco-jantke** [comment]
I am closing this PR for now, as I don't have the time right now to update my PR and the other provider implementations. I plan to do this though in middle term so stay tuned.

**Pull request closed without merging**
