### PR TITLE
Don't allow routers higher than internal ones

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Use a dynamic approach to get the maxInt.

on 64 bits: MaxInt64
on 32 bits: MaxInt32

### Motivation

Don't allow routers higher than internal ones.

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Review by mmatur — APPROVED** [review]
LGTM

**Review by rtribotte — APPROVED** [review]
LGTM

**Comment by hhromic** [comment]
This comment is not a review, but I'm wondering why not using `math.MaxInt` ?
I like to learn from experienced engineers and this one got me thinking.

Ref: <https://pkg.go.dev/math#pkg-constants>

**Comment by hhromic** [comment]
Thanks for the context and explanation, makes sense!

**Review by kevinpollet — APPROVED** [review]
LGTM

**Pull request merged**
