### PR TITLE
Extract some code in packages

### PR DESCRIPTION
**Pull request by vdemeester**
Reviving #1006 👼

- This will help split stuff in smaller, better tested packages
- This moves some stuff like the traefik command to package `cmd`

It's build on top of #1444, so only the 2nd commit should be reviewed 👼 

🦁

### CODE REVIEW

**Comment by timoreimann** [comment]
I think you'll need to adjust the Makefile targets and `script/` helpers since the build target changed from root to `cmd`.

Docs in `.github/CONTRIBUTING.md` likely need a small update too.

**Comment by timoreimann** [comment]
Hmm, given that the build ran for quite a while (even though erroneously), my comment might be false. Maybe you can double check.

**Comment by vdemeester** [comment]
@timoreimann yep, I need to update docs, just want to make sure these changes are ok for @emilevauge and everybody before doing it 👼

**Comment by emilevauge** [comment]
@vdemeester Looks very good to me ( love the new `server` package :heart_eyes: )

**Comment by vdemeester** [comment]
Updated with the docs 👼

**Pull request merged**
