### PR TITLE
Add Replace Query Regex Middlewares

### PR DESCRIPTION
**Pull request by dtomcej**
### What does this PR do?

Adds 2 new middlewares:
- ReplaceQueryRegex: To modify query strings
- ReplacePathQueryRegex: To modify paths and query strings

### Motivation

This PR carries on the work started with #4000

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional notes

Co-authored by @holygeek / @cention-nazri

### CODE REVIEW

**Comment by ldez** [comment]
I am troubled with `ReplacePathQueryRegex` because we also have `ReplacePathRegex`.

I wonder if we could merge it with `ReplacePathRegex` :thinking:

**Comment by jbdoumenjou** [comment]
I agree with @ldez, a merge between these middlewares seems to be more appropriate.

**Comment by dtomcej** [comment]
>I wonder if we could merge it with ReplacePathRegex 🤔

Yes. I will make this happen. It makes sense to me too.

Will aim for:
- `ReplacePathRegex` => Path and query modifier
and
- `ReplaceQueryRegex` => Query only modifier

**Comment by dtomcej** [comment]
@ldez @jbdoumenjou I looked into updating this PR, but I ran into the design reason for the difference between `ReplacePathRegex` and `ReplacePathQueryRegex`:

`ReplacePathRegex` modifies the path of the request, but `ReplacePathQueryRegex` only allows for the regex to match and use parts of the path to modify queries. `ReplacePathQueryRegex` does not allow for the path to be modified in this manner.

`ReplacePathRegex` operates on `*http.Request.URL.Path`, and `ReplacePathQueryRegex` operates on `http.Request.RequestURI`, and I'm not sure there is a good way to merge the two without incorporating breaking/design changes.

Thoughts?

**Comment by jbdoumenjou** [comment]
Sorry for the delay @dtomcej .
So, as we don't use the same data to apply those middlewares, I agree that it may be confusing to merge them.  Perhaps we need to define two better names to avoid any confusion. WDYT ?

**Comment by dtomcej** [comment]
>Perhaps we need to define two better names to avoid any confusion

Yessir. I think this would help out immensely.

**Comment by jbdoumenjou** [comment]
We can have only one middleware with an option like "src/target/criterion/..." to define the request part used. But it seems to be no compliant with the "spirit" of the middleware responsibility.
So, we can factorize the code between this two middlewares and try to find a better name (but I didn't managed to do it). It is just some non blocking comment, so I will accept the PR.

**Comment by freddydk** [comment]
Was the ability of changing the Query part of the URL as part of the modifiers ever implemented?
Thanks

**Comment by ldez** [comment]
Some notes:
- `ReplacePathQueryRegex`: use the path and the query to modify **the query string only**, there is no modification of the path.
- I continue to think that `replacePathRegex`, `replaceQueryRegex`, `replacePathQueryRegex` can be a single middleware.

I will continue to rewrite the PR, maybe I will open an another PR.

**Comment by ldez** [comment]
After discussion with the team, we think that the approach is too naive which will produce a high complexity of use.

So we will decline this PR but we keep the idea and for that I created an issue on this subject (#6276).

If you want to participate in the reflection on the subject or explain your use cases, I invite you to express yourself in this issue (#6276).

Thank you for your understanding.

**Pull request closed without merging**
