### PR TITLE
Fix Rancher healthcheck doesn't work as expected

### LINKED ISSUE #2279: Rancher healthcheck doesn't work as expected
### Do you want to request a *feature* or report a *bug*?
bug

### What did you do?
Start traefik with racnher metadata. With enabling AND disabling healtcheack.

### What did you expect to see?

1) If healtcheck is disabled and service is updating/updated, i see service rule on the traefik web admin. And servise opend in browser.

2) if healtcheck is enabled. I want to see the same behavior at this point.

### What did you see instead?

1) If healtcheck is disabled and when service is updating i see 2 servers on service backend by 1-2 seconds. But one of this servers is no longer works. (stoped by updateding when i use "start before stoping" at racnher). At browser i see Gateway Timeout.
Perhaps this is the correct behavior?

2) if heathcheck is enabled and service updating/updated with "start before stoping" i did not see any rules of this service on traefik admin. When i confirm update in rancher, traefik show new rules 

At rancher api i see:
```
"state": "upgraded",
"healthState": "healthy",
```
But if restart traefik. I will see service rules in web admin.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.4.0
Codename:     roquefort
Go version:   go1.9.1
Built:        2017-10-16_04:52:07PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[rancher]
domain = "dev.rz"
Watch = true
RefreshSeconds = 15
ExposedByDefault = false
EnableServiceHealthFilter = false/true (!!!)

[rancher.metadata]
IntervalPoll = false
Prefix = "/latest"
```

### PR DESCRIPTION
**Pull request by jmirc**
Fixes #2279 

Here is the small change I did to fix the issue. I tested locally and it works.
It is my first go changes so I am sure this could be better

### CODE REVIEW

**Comment by geraldcroes** [comment]
We would love to merge your Pull Request to fix the problem but unfortunately, we cannot find information on this "upgrading" state in the [official documentation](http://rancher.com/docs/rancher/v1.6/en/api/v1/api-resources/instance/).

Excerpt : 

> The current state of the instance. The options are creating, error, erroring, migrating, purged, purging, removed, removing, requested, restarting, restoring, running, starting, stopped, stopping, updating-running, updating-stopped.


Could you provide us with more information on the matter?

**Comment by jmirc** [comment]
We are using Rancher and Traefik in prod and I developed an app that is integrated with our CICD to deploy automatically our application on Rancher.
Here are examples of different states I am getting from Rancher when an update is executed.

```
2018-03-02 12:42:13.400  INFO 1 [ XNIO-2 task-48] c.e.w.c.r.d.service.ApplicationService    serviceName=cs-ch-trover-adapter; health state=initializing and service's state=upgrading
2018-03-02 12:42:13.423  INFO 1 [ XNIO-2 task-23] c.e.w.c.r.d.service.ApplicationService    serviceName=cs-ch-trover-adapter; health state=healthy and service's state=upgraded
2018-03-02 12:42:08.398  INFO 1 [ XNIO-2 task-23] c.e.w.c.r.d.service.ApplicationService    serviceName=cs-ch-trover-adapter; health state=healthy and service's state=upgrading
2018-03-02 12:42:03.373  INFO 1 [ XNIO-2 task-23] c.e.w.c.r.d.service.ApplicationService    serviceName=cs-ch-trover-adapter; health state=degraded and service's state=upgrading
```

Best
Jerome

**Comment by ldez** [comment]
@jmirc could you rebase on the v1.5 branch.

**Comment by jmirc** [comment]
close this issue based on master in favor of #2962 which is based on v1.5

**Comment by ldez** [comment]
@jmirc for the next time, I recommend to you to use a dedicated branch when you do a PR (e.g. not `master` or `v1.5`).

**Comment by jmirc** [comment]
@ldez Sorry about that. I will do it.

**Comment by ldez** [comment]
@jmirc don't change anything for now :wink: 

And also next time, please try to respect PR description template.

**Pull request closed without merging**
