### PR TITLE
Upgrade webui to FountainJS

### PR DESCRIPTION
**Pull request by micaelmbagira**

### CODE REVIEW

**Comment by emilevauge** [comment]
This is great, thanks a lot @micaelmbagira :tada: 
Ping @ldez ;)
Fixes #550

**Comment by ldez** [comment]
Sorry but this PR doesn't fix #550

**Comment by micaelmbagira** [comment]
Mmh, didn't get the problem. I will make another one with Webpack instead of Bower/wiredep.

**Comment by micaelmbagira** [comment]
@ldez @emilevauge Closed in favor of https://github.com/containous/traefik/pull/558

**Pull request closed without merging**
