### PR TITLE
fix DelayBeforeCheck

### LINKED ISSUE #2997: DelayBeforeCheck option does not work
### Do you want to request a *feature* or report a *bug*?
`DelayBeforeCheck` option does not work

### What did you expect to see?
Delay 300 seconds before checking TXT recording

### What did you see instead?

Testing revealed that TXT recording is created for 3-4 seconds

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
k8s, consul kv
```
curl -XPUT --data "300" https://consul.local/kv/traefik/acme/dnschallenge/delaybeforecheck 
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by BaronMsk**
### Motivation

Fixes #2997

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by BaronMsk** [comment]
#2997

**Comment by BaronMsk** [comment]
problem with the CI system, please try to run the tests when there will be no problems

**Comment by ldez** [comment]
```
---> Making bundle: validate-gofmt (in .)
These files are not properly gofmt'd:
 - acme/acme.go
 - provider/acme/challenge.go
```

**Comment by nmengin** [comment]
Hello @BaronMsk.

Many thanks for this Pull Request.
However, as the `acme.dnsChallenge.delayBeforeCheck` option type is `Duration`, it is stored in **nano seconds** in the KV store by the `storeconfig`  command.

Your PR seems to not be compatible with the standard command used to populate a KV store from a configuration file (`storeconfig` command) and may cause regressions.

That's why I have to close it but feel free to join our [Slack workspace](https://traefik.herokuapp.com/) to discuss [more about your need](https://traefik.slack.com/messages/C0CDT22PJ/).

**Pull request closed without merging**
