### PR TITLE
Add Nvd3 Dependency to fix UI / Dashboard

### LINKED ISSUE #796: cannot access webui/dashboard
I'm using latest experimental on Kubernetes, I'm getting this on port 8080 : 
screenshot from 2016-11-03 11-22-51

### PR DESCRIPTION
**Pull request by SantoDE**
This PR fixes #796 :)

/cc: @containous/traefik

### CODE REVIEW

**Comment by jippi** [comment]
any eta on this? :)

**Comment by emilevauge** [comment]
What do you mean by eta? This PR was submitted yesterday...

**Comment by jippi** [comment]
more on merging it in :)

**Comment by SantoDE** [comment]
It will be merged for the 1.1 release :)

**Comment by emilevauge** [comment]
LGTM! Thanks @santode

**Pull request merged**
