### PR TITLE
Use healthcheck for systemd watchdog

### PR DESCRIPTION
**Pull request by guilhem**
Mutualise code for `traefik healthcheck` command and watchdog.

Link to first version of watchdog implementation #818

### CODE REVIEW

**Comment by emilevauge** [comment]
Hey @guilhem, thanks for your contribution :)
Can I ask you what is the real need to check the healthcheck in the systemd watchdog ?

**Comment by guilhem** [comment]
@emilevauge of course you can :)

Currently, systemd watchdog only tests if a goroutine is working... that's not really a true healthcheck.
The server can be blocked, but watchdog ok.

With this kind of healthcheck, any problem on TCP stack (too many file open) and HTTP server is triggered

**Comment by emilevauge** [comment]
Yeah, I understand.
But the healthcheck is not on the same http server than the reverse proxy, so I'm wondering if it's worth it.
WDYT ?

**Comment by guilhem** [comment]
yes of course, but it's acting like any other healthcheck will do by requesting `/ping`.

In fact, I only use your work on command line `healthcheck` and generalize it to be used by systemd watchdog.

Any improvement in healthcheck function can be done :)

**Pull request merged**
