### PR TITLE
Revert "Ensure that we don't add balancees with no health check runs …

### PR DESCRIPTION
**Pull request by jangie**
…if there is a health check defined on it"

This reverts commit ad12a7264e4b8aecf8d90a96a747101b5fa4871a.

### CODE REVIEW

**Comment by jangie** [comment]
See: Discussion in #1185 .

**Comment by timoreimann** [comment]
Ping @emile @santode @errm @russ @dtomcej @vdemeester.

**Comment by emilevauge** [comment]
@jangie @timoreimann shouldn't we rebase this PR on `v1.2` instead ?

**Comment by timoreimann** [comment]
@emilevauge not too familiar with the release process yet. I suppose the `1.2` branch will be used for the next release? Do we then cherry-pick the commit into `master` later?

**Comment by emilevauge** [comment]
@timoreimann the `v1.2` release is based on the `v1.2` branch. We will merge the `v1.2` into master in the future. Does this PR needs to be in `v1.2` ?

**Comment by timoreimann** [comment]
I think it should be in 1.2 in order to avoid breaking existing clients.

@jangie can you rebase your PR? (The Github UI should allow that.)

**Comment by jangie** [comment]
that looks to have caused history i don't want to have, i'm going to close this out and start from v1.2.

**Comment by timoreimann** [comment]
@jangie oh I forgot that Github's rebase feature can be a bit iffy at times. FYI, what usually helps then is to first rebase onto the new base branch with git on the CLI and re-push to Github afterwards.

New branch works too though, thanks. :-)

**Comment by timoreimann** [comment]
New branch is #1198 .

**Pull request closed without merging**
