### PR TITLE
Fix docker issues with global and dead tasks

### LINKED ISSUE #1138: Docker Swarm provider not reliable in v1.2.0-rc1 (Docker 1.13.0, traefik v1.2.0-rc1)
### What version of Traefik are you using (`traefik version`)?
v1.2.0-rc1

### What is your environment & configuration (arguments, toml...)?
Docker Swarm Mode with Docker 1.13.0

### What did you do?
I started traefik (dockerized verison) without changes. I used to use v1.1.2 and switched to  v1.2.0-rc1. 1.1.2 works fine and discovers the services based on docker swarm labels.  v1.2.0-rc1 does not do this when all services are deployed. the docker provider tab and its services are sometimes looaded correctly and sometimes not. 

### What did you expect to see?
the docker provider tab and a deployment of the docker swarm services

### What did you see instead?
Looking at the Traefik log file, I can see:
time="2017-02-08T16:13:50Z" level=info msg="Starting provider *provider.Docker {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"docker.localhost\",\"TLS\":null\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":true}"

However, some lines below this I see:
...
time="2017-02-08T16:17:20Z" level=error msg="Near line 29 (last key parsed 'backends.backend-box.servers'): Key 'backends.backend-box.servers.server-box-1' has already been defined."
time="2017-02-08T16:17:35Z" level=error msg="Near line 127 (last key parsed 'backends.backend-rtdapp.servers'): Key 'backends.backend-rtdapp.servers.server-rtdapp-1' has already been defined."
...
This does not appear when restarting Traefik v1.1.2

### PR DESCRIPTION
**Pull request by christopherobin**
A couple small issues with Docker fixed in this PR:

* Global tasks (`docker service create --mode global`) do not have a `Slot` ID in the task list, so each entry will end up having the same name in the backend configuration making the docker provider crash. This fallbacks to using the `TaskID` instead if the service is global.
* Dead tasks would be also listed in traefik, added the `desired-state: running` filter to the task list query so that we only use alive tasks as backends.

Fixes #1138

### CODE REVIEW

**Comment by emilevauge** [comment]
@vdemeester we could get this one in v1.2 right ?

**Comment by vdemeester** [comment]
@emilevauge I think so

**Comment by emilevauge** [comment]
Rebased on branch v1.2.
@christopherobin Do you think you could add a unit test on this ?

**Comment by christopherobin** [comment]
@emilevauge I'll look into doing that asap.

I've also been using this branch on a local swarm cluster for about a week now and didn't run into any issue yet with both replicated and global services.

**Pull request merged**
