### PR TITLE
Do not compress when content type text/event-stream

### LINKED ISSUE #2576: Problem with text/event-stream when compress=true
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We use [concourse](https://concourse.ci/) (it's a CI/CD tool) under traefik. Concourse UI uses `text/stream` to get information about builds from its backend. In traefik 1.3.8 everything works fine, but after updating to traefik 1.4.0 - 1.4.5 concourse can't get any event from its backend (infinite waiting...).

### What did you expect to see?

Concourse gets events from the backend.

### What did you see instead?

Infinite waiting.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik 1.4.0 - 1.4.5

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

The route to concourse was configured statically.
```toml
################################################################
# Global configuration
################################################################

logLevel = "DEBUG"

# Traefik logs file
traefikLogsFile = "/var/log/traefik-debug.log"

# Access logs file
accessLogsFile = "/var/log/accessTraefik.log"

# Entrypoints
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
	[entryPoints.http.redirect]
	entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = ""
      keyFile = ""

# ...

[file]

[backends]
  [backends.concourse]
    [backends.concourse.servers.server1]
    url = "http://some-ip:8080"
# ...

[frontends]
  [frontends.concourse]
  backend = "concourse"
  passHostHeader = true
    [frontends.concourse.routes.host]
    rule = "Host:some-host"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

Only these lines are related to concourse in traefik logs.

```shell
time="2017-12-15T22:13:12Z" level=debug msg="Round trip: http://some-ip:port, code: 200, duration: 6.000457ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:some-host"
time="2017-12-15T22:13:14Z" level=debug msg="Round trip: http://some-ip:port, code: 200, duration: 2.51749ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:some-host"
time="2017-12-15T22:13:14Z" level=debug msg="Round trip: http://some-ip:port, code: 200, duration: 3.597858ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:some-host"
```

### PR DESCRIPTION
**Pull request by sylr**
Attempt to fix #2576

Co-authored-by: Joan Rieu <joan@joanrieu.com>

### CODE REVIEW

**Comment by joanrieu** [comment]
To give some context, right now SSE (Server-Sent Events) streams are not working properly: after the HTTP connection is established, the response is not transmitted because Traefik waits for the full body of the response (which never comes because it's a stream).

A workaround for Traefik users facing this issue is to disable compression altogether, but it's not a real solution.

There is already in the code a check to avoid compressing gRPC streams, this PR adds the same check for SSE streams.

**Comment by janober** [comment]
Any reason why that is not merged yet? Did also run into that issue and a proper fix (except deactivate compress all together) would be very appreciated. Thanks!

**Comment by dduportal** [comment]
Hi @janober, thanks for your interest.

The workflow for contributions is briefly explained here: <https://docs.traefik.io/v2.0/contributing/maintainers/#status-workflow>.

So actually, this PR is waiting for one of the core maintainers to do a design review.

- If the design is "LGTM-ed", then the PR's label will be updated to "status-2", and the maintainers will be expected to do the code review. 
- If not, the PR will be commented or refused based on the feedback.

You have to know that we are working hard on Traefik v2.0 (<https://github.com/containous/traefik/projects/3>), so the time required to review external PRs is short. Here, the priority is "P2" for the associated issue, so we might have to wait a bit.

**Comment by sylr** [comment]
Can we merge this please ?

**Comment by dcharbonnier** [comment]
The review for a if on the same way we're checking for application/grpc with a test more over.
The fact that you work on the v2.0 means also that this should be faster, there is no plan to do a big change on this version, just to fix a bug.
2 month ago someone made a contribution and you don't find 5 minutes to thanks this person and make his contribution count.

**Comment by LiranBri** [comment]
is there any workaround until this is merged?
if I got it correct, right now our only option is to disable completely compressing for supporting SSE

**Pull request closed without merging**
