### PR TITLE
Check that we serve HTTP/2

### PR DESCRIPTION
**Pull request by trecloux**
To be sure that bug #790 fixed in #814 does not come back

### CODE REVIEW

**Comment by errm** [comment]
this test seems to be failing on CI

```
----------------------------------------------------------------------
FAIL: https_test.go:22: HTTPSSuite.TestWithSNIConfigHandshake
https_test.go:47:
    c.Assert(proto, checker.Equals, "h2")
... obtained string = ""
... expected string = "h2"
---------------------------------------------------------------------
```

was it working for you locally @trecloux?

**Comment by trecloux** [comment]
@errm The tests were running based on master branch and the test is failing because master branch does not include the fix to server HTTP/2 (#814).
I modified the pull request to be based on v1.1.

**Comment by errm** [comment]
ping @containous/traefik

**Comment by SantoDE** [comment]
LGTM 👼

**Comment by vdemeester** [comment]
@trecloux needs a rebase :sweat:

**Comment by trecloux** [comment]
@vdemeester  Rebase done

**Pull request merged**
