### PR TITLE
Fix integration tests on MacOS

### PR DESCRIPTION
**Pull request by sylr**
### What does this PR do?

This PR improves the ability to run integration tests on MacOS.

To do so, we make the defaults traefik entryPoints listen on `localhost:<port>` instead of `:<port>` so that macos does not complain an unsigned application is trying to receive incoming connection.

Also fix all test fixture configs to use `localhost:<port>`.

### Motivation

I'm trying to run integrations test on my dev machine to validate my work.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by dtomcej** [comment]
Hey @sylr, it was my understanding that the container based integration tests worked fine, while the host based tests did not.

Is this something that can be explored to decrease the scope of the tests that are affected by this PR?

**Comment by sylr** [comment]
Hi @dtomcej,

You are right, the fixtures/ changes might be useless. I'll rollback them.

Thanks.

**Comment by dtomcej** [comment]
Instead of https://github.com/containous/traefik/pull/6061/files#diff-8449e3d93a890b1153a65283a93cf08bR22 Where tests are disabled because the IP isn't routable,

How about modifying the tests so that the request doesn't come from the host, but from another container.

It would require creating a tools container, and then docker exec or such to run the commands from that container. That would allow the tests to run, but without running from the host.

**Comment by sylr** [comment]
Are you suggesting we move the `ProxyProtocolSuite` from `host` to `container` ?

**Comment by ldez** [comment]
The root cause, of the majority of the problem with our integration tests on MacOS, is the docker-compose version that we use. We know that since a long time.

This require to change the tooling we use to run those kind of tests. https://github.com/containous/traefik/issues/4678

Changing Traefik code only to run integration tests on MacOS is not a good approach and having conditional tests only for MacOS does not seem a good approach either.

**Comment by sylr** [comment]
Skipping the ProxyProtocolSuite allowed me to run the whole test integrations suite successfully on my machine (with the changes made to the Makefile that are in https://github.com/containous/traefik/pull/6064).

**Comment by ldez** [comment]
Related to my previous post, we will decline this PR.

Thanks anyway.

**Pull request closed without merging**
