### PR TITLE
Fix empty IP for backend when dnsrr in Docker swarm mode

### LINKED ISSUE #1494: No hostname(s) and/or IP address(es) is registered on backend's URL when the Docker service is created as --endpoint-mode dnsrr in Docker swarm mode
### Do you want to request a *feature* or report a *bug*?

I think this is a bug.

### What did you do?

I created the Docker service in `--endpoint-mode dnsrr` with 3 replicas as the backend service. The frontend's rule is `PathPrefix`. If I remove the `--endpoint-mode dnsrr` which means that the endpoint mode will be in VIP, it will automatically register the VIP in the backend's URL.

### What did you expect to see?

The service name or the IP addresses of all the tasks (containers) created should be registered on the backend's URL.

### What did you see instead?

There is no address in the URL. It just show as http://:$port_number

### Output of `traefik version`: (_What version of Traefik are you using?_)

[Traefik Linux AMD64 v1.2.3](https://github.com/containous/traefik/releases/download/v1.2.3/traefik_linux-amd64)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = true
usebindportip = true
swarmmode = true
```

### PR DESCRIPTION
**Pull request by mmatur**
### What does this PR do?

Fixes #1494 

Currently we don't manage `DNSRR` resolution mode in Docker swarm mode. This PR only excludes services with `DNSRR` resolution mode. 

We will try to implement `DNSRR` resolution mode in Docker swarm mode ASAP

### More

- [x] Added/updated tests

### CODE REVIEW

**Comment by kcrawley** [comment]
> We will try to implement DNSRR resolution mode in Docker swarm mode ASAP

is there an issue being tracked for this work?

**Comment by caseycs** [comment]
Looks like the problem still exists - 1.5.2 and Docker Swarm:

```
deploy@www3:~$ sudo sudo ./traefik  -c traefik.sample.toml
INFO[2018-02-16T03:14:50+01:00] Using TOML configuration file /home/deploy/traefik.sample.toml
WARN[2018-02-16T03:14:50+01:00] web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics
WARN[2018-02-16T03:14:50+01:00] web option is ignored if you use it with one of these options : api, rest provider, ping or metrics
INFO[2018-02-16T03:14:50+01:00] Traefik version v1.5.2 built on 2018-02-12_10:55:08AM
...
DEBU[2018-02-16T03:14:50+01:00] Validation of load balancer method for backend backend-nginx failed: invalid load-balancing method ''. Using default method wrr.
DEBU[2018-02-16T03:14:50+01:00] Configuration received from provider docker: {"backends":{"backend-nginx":{"servers":{"server-nginx-1":{"url":"http://:80","weight":0},"server-nginx-2":{"url":"http://:80","weight":0},"server-nginx-3":{"url":"http://:80","weight":0},"server-nginx-4":{"url":"http://:80","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-test-test-nl-0":{"entryPoints":["http"],"backend":"backend-nginx","routes":{"route-frontend-Host-test-test-nl-0":{"rule":"Host:test.test.nl"}},"passHostHeader":true,"priority":0,"basicAuth":[]}}}
DEBU[2018-02-16T03:14:50+01:00] Creating frontend frontend-Host-test-test-nl-0
DEBU[2018-02-16T03:14:50+01:00] Wiring frontend frontend-Host-test-test-nl-0 to entryPoint http
DEBU[2018-02-16T03:14:50+01:00] Creating route route-frontend-Host-test-test-nl-0 Host:test.test.nl
DEBU[2018-02-16T03:14:50+01:00] Creating backend backend-nginx
DEBU[2018-02-16T03:14:50+01:00] Creating load-balancer wrr
DEBU[2018-02-16T03:14:50+01:00] Creating server server-nginx-4 at http://:80 with weight 0
DEBU[2018-02-16T03:14:50+01:00] Creating server server-nginx-2 at http://:80 with weight 0
DEBU[2018-02-16T03:14:50+01:00] Creating server server-nginx-3 at http://:80 with weight 0
DEBU[2018-02-16T03:14:50+01:00] Creating server server-nginx-1 at http://:80 with weight 0
```

And on the docker side:

```
deploy@www3:~$ sudo docker service inspect nginx
[
    {
...
            "EndpointSpec": {
                "Mode": "dnsrr"
            }
        },
...
    }
]
```

**Comment by mmatur** [comment]
Hi @caseycs, 

Could you open a new issue with a detailed configuration please ?

- Træfik configuration
- Compose file with your stack

**Comment by caseycs** [comment]
@mmatur thanks, I tried to make it as clear as I can: https://github.com/containous/traefik/issues/2869

**Pull request merged**
