### PR TITLE
add PING handler to dashboard API

### PR DESCRIPTION
**Pull request by jangie**
Discussion in the slack room indicated that this might be worthwhile.

### CODE REVIEW

**Comment by errm** [comment]
LGTM

**Comment by emilevauge** [comment]
LGTM

**Comment by emilevauge** [comment]
Hum, I forgot to ask you to add this in the documentation ;)

**Comment by jangie** [comment]
Ack, sorry! I'll add that in sometime tonight. Apologies for the oversight.

**Comment by jangie** [comment]
Have added

**Pull request merged**
