### PR TITLE
Update Oxy, fix for #1199

### PR DESCRIPTION
**Pull request by akanto**

### CODE REVIEW

**Comment by timoreimann** [comment]
@akanto With glide, you must not change `glide.lock` manually.

Please set the new version in `glide.yaml` and run `script/glide.sh update` afterwards.

**Comment by emilevauge** [comment]
I suggest to put this fix in v1.2 branch instead. @akanto could you also rebase your PR on v1.2 branch ?

**Comment by akanto** [comment]
Maybe I am doing something wrong, but a lot of dependencies has been changed after I have executed the ./script/glide.sh update. What I did:

* Updated the vulcand oxy hash in glide.yml
* Executed `./script/glide.sh update`

I have executed the `./script/glide.sh update` command from a container built from build.Dockerfile (https://raw.githubusercontent.com/containous/traefik/master/build.Dockerfile).

**Comment by timoreimann** [comment]
@akanto I think you did everything correct. The problem with glide is that it does not support updating individual packages only. It needs to update all unpinned dependencies, including transitive ones. The latter is what was updated mostly by your last push.

The build currently fails because glide pulled in an update of go-github, which has changed its API apparently. We'll have to adjust, which I can help you with.

What you should do first though in order to reduce merge conflict effort is to rebase your feature branch onto the v1.2 branch [as suggested](https://github.com/containous/traefik/pull/1278#issuecomment-286190058) by @emilevauge. Please also make sure that you commit all changes to the `vendor/` folder (i.e., what changes after you run `script/glide.sh update`) in a separate commit in order to keep the git history manageable and Github's review UI usable. (Unfortunately, Github does a fairly bad job at dealing with vendor changes reasonably, even medium-sized ones.)

Sorry for the inconvenience!

**Comment by timoreimann** [comment]
I have pushed a commit that should help adjust to go-github's API change and fix the build problem.

**Comment by timoreimann** [comment]
[Next one](https://travis-ci.org/containous/traefik/jobs/210780788#L3985-L3990):

```
---> Making bundle: binary (in .)
vendor/golang.org/x/oauth2/google/default.go:20:2: cannot find package "google.golang.org/cloud/compute/metadata" in any of:
	/go/src/github.com/containous/traefik/vendor/google.golang.org/cloud/compute/metadata (vendor tree)
	/usr/local/go/src/google.golang.org/cloud/compute/metadata (from $GOROOT)
	/go/src/google.golang.org/cloud/compute/metadata (from $GOPATH)
make: *** [binary] Error 1
```

Grrrrr...

**Comment by akanto** [comment]
Right, meantime I have rebased to 1.2 as requested, but there I run  into several issues, since some deps are not pinned and not only the compile but even "glide up" failed.

What I am doing now:
- updating the glide.yaml with new oxy hash
- pinning deps to glide.yaml that causing problems

**Comment by akanto** [comment]
@timoreimann it seems that somehow the build is stuck or not triggered on travis and the last build is still this: https://travis-ci.org/containous/traefik/builds/210780787 , could you trigger the build on travis, please?

**Comment by emilevauge** [comment]
@akanto 
>could you trigger the build on travis, please?

We can't, could you push force again?

**Comment by emilevauge** [comment]
Tests are failing, @akanto @timoreimann any idea why ?

**Comment by timoreimann** [comment]
@emilevauge I'm not sure but I guess it's caused by an undesirable package update. :/

Let me try something...

**Comment by timoreimann** [comment]
I managed to update the oxy package only and leave everything else untouched. Tests and validation look good on my machine locally, let's see what Travis says.

Here's what I did:

1. Revert the glide manifest and lock files to the revisions from the v1.2 branch.
1. Use the github.com/multiplay/glide-pin plugin to pin all versions in the manifest file to the ones given in the lock file.
1. Bump the commit hash of github.com/containous/oxy in the manifest file to the new version.
1. Run `glide update -v` to update the lock file.
1. Use glide-hash to get the manifest file hash and put it in the lock file to please `validate-glide`.

Pro: This might actually work.
Con: This is all _very_, _very_ awful and sad.

**Comment by emilevauge** [comment]
@timoreimann 
>Use the github.com/multiplay/glide-pin plugin to pin all versions in the manifest file to the ones given in the lock file.

Looking at the modified `glide.yaml` does not show any new pinned packages :thinking:

**Comment by timoreimann** [comment]
@emilevauge yeah sorry, I forgot to mention that I undid the pinning again.

Added one point [to my list](https://github.com/containous/traefik/pull/1278#issuecomment-286696714).

**Pull request merged**
