### PR TITLE
UPXd Traefik

### PR DESCRIPTION
**Pull request by steigr**
Reduced Size from ~20MiB to ~6MiB

Signed-off-by: Mathias Kaufmann <me@stei.gr>

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @steigr, thanks for your contribution.
I'm not sure that this should be merged, indeed, I intentionally not used UPX because of:

- higher launch time
- possible risk of false positive detected by antivirus

WDYT?

**Comment by steigr** [comment]
Hi @emilevauge,

I don't have any experiences regarding UPX and antivirus scanners. Maybe I can investigate a little bit.

With the launch time there is a tradeoff between initial download time and possible container restart time. On dev machines frequent restarts will take a little bit longer but I think Traefik is more like a long running process/container thus launch time impacts should not be a problem. I don't care if launch take a few more milliseconds if the download will finish within a third of the time.

The PR should be more like an suggestion if size reduction of the (already small) container is needed a some later point.

**Comment by errm** [comment]
This might be premature optimization, but clearly in any production environment download time is going to exceed any additional startup time...  Clearly the image is already quite small so ...

I would say for safeties sake it would be better to install upx in the builder using the os package https://packages.debian.org/jessie/upx-ucl its just not secure to download a binary over an insecure http connection without doing a checksum or something, installing from a package is the safe way to go, plus it should ensure any security updates needed in the future.

**Comment by shouze** [comment]
BTW docker containers are already compressed too... so ok not with the same pressure that upx can make on binaries... but looks sufficient so far... I would appreciate to have all of my containers having a similar size that the traefik one! ;)

**Comment by joonas-fi** [comment]
I'm not sure about this. While I do encourage keeping things as small as possible (Alpine + Docker = FTW), along with a minimal layer count, I think Traefik is already small enough not to justify the longer startup time and (negligibly small, though) uncertainty about UPX'ing bringing surprising issue.

**Comment by vdemeester** [comment]
I'll close this for now as this is not really something we think we would merge… The current image/binary is not that big :angel: 

Thanks @steigr for your contribution though :wink:

**Pull request closed without merging**
