### PR TITLE
Simplify dashboard rule example

### PR DESCRIPTION
**Pull request by sosoba**
### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

PathPrefix carries out the logical or himself.

### CODE REVIEW

**Review by tomMoulard — APPROVED** [review]
LGTM :ok_hand:

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Comment by netsandbox** [comment]
@sosoba this PR missed to update other places, like https://github.com/traefik/traefik/blob/master/docs/content/operations/include-dashboard-examples.md

**Comment by tfny** [comment]
@netsandbox, Thanks for catching that.  You are right, while the current documentation is true, it is not optimized.  Will you be willing to open a PR to help us update?

**Pull request merged**
