### PR TITLE
Capability to remove selected headers from all responses on the entrypoint

### PR DESCRIPTION
**Pull request by aabramchuk**
### What does this PR do?

Adds header removal support on entrypoint level

### Motivation

I want to be able to remove any desired header from all responses of the entrypoint

### More

- [X] Added/updated tests
- [X] Added/updated documentation

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @aabramchuk, thanks for this contribution!
Could you explain why you need this?

**Comment by aabramchuk** [comment]
Hi @emilevauge 
I want to ensure that certain headers never leave the boundary of the gateway. I can either do it for every front-end by setting the header to empty string or I can define these headers on the entry point.

**Comment by emilevauge** [comment]
Hey @aabramchuk, thanks for your feedback!
We had a discussion with maintainers about your PR. We are currently working on a big refactor on the `master` branch, and this feature will be natively supported after this refactor.
Therefore, we can close this PR and just wait for our next release :)
Thanks again for your contribution!

**Comment by aabramchuk** [comment]
k, thnx @emilevauge.  By next release you mean 1.8, correct?

**Pull request closed without merging**
