### PR TITLE
Stickiness cookie name.

### LINKED ISSUE #2249: "expected value but found '\n' instead" consul_catalog
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

added tag on service / app `traefik.backend.loadbalancer.stickiness=true`

### What did you expect to see?

Sticky session cookie name.

### What did you see instead?

have this error:
```
level=error msg="Failed to create config" error="Near line 42 (last key parsed 'Backends.backend-myappl.LoadBalancer.Stickiness.cookieName'): expected value but found '\n' instead"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
version:v1.4.0-rc5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### PR DESCRIPTION
**Pull request by ldez**
### Description

- Add missing quotes. 😞 
- Add retro compatibility with 1.3

Related to #2232
Fixes #2249

### CODE REVIEW

**Comment by ldez** [comment]
@emilevauge 
1. `hasStickinessLabel` implementations differ because each providers have a different way to get label
2. only one provider: `k8s` (double hash)
3. yes because all providers are not testable on this part

**Comment by MichaelErmer** [comment]
Is this on docker yet?

**Comment by ldez** [comment]
@MichaelErmer @gabrielfsousa could you try  `ldez/traefik:sticky` ?

**Comment by MichaelErmer** [comment]
@ldez it "works" however it doesnt enable stickiness using these labels:
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.stickiness.cookiename=_TRAEFIK_BACKEND"

**Comment by lvnilesh** [comment]
Need stickiness and cookieName working with Docker Swarm backend as well, please. Thank you.

**Comment by MichaelErmer** [comment]
oh yes, im using docker swarm maybe thats the issue...

**Comment by ldez** [comment]
please look #2266 😉

**Pull request merged**
